import-js/eslint-plugin-import

lib/core/resolve.js
tests/files/jsx/MyUnCoolComponent.jsx
tests/lib/core/resolve.js

This pull request fixes an issue we've dealt with internally. We primarily use OS X as our development OS and deploy to Linux. OS X is case-insensitive, meaning that given a file called `MyUnCoolComponent.jsx`, the following import will work without issue on OS X:
```js
// Note the casing error in the file name
import MyUnCoolComponent from "./MyUncoolComponent.jsx"
```
However, this import will fail on a case-sensitive OS such as Linux. This PR adds functionality to check the casing in the file path before reporting a successful file match.

Reporting wrongly-cased file imports in case-insensitive operating systems

---

README.md
appveyor.yml
package.json
src/core/resolve.js
src/rules/no-unresolved.js
tests/src/core/resolve.js
tests/src/rules/named.js
tests/src/rules/no-unresolved.js

Attempted fix for #44, two-fold:
- `case-sensitive` option for `no-unresolved`. defaults to false.
- added an untested drive-letter regex base case to `fileExistsWithCaseSync`
@doctyper and @illinar, looking for comments from you two before I merge this to master and release.

optional case sensitivity

---

.babelrc
config/README.md
config/es7-jsx.js
package.json
src/core/parse.js
src/rules/default.js
src/rules/export.js
src/rules/imports-first.js
src/rules/named.js
src/rules/namespace.js
src/rules/no-duplicates.js
src/rules/no-errors.js
src/rules/no-named-as-default.js
src/rules/no-require.js
src/rules/no-unresolved.js
tests/src/core/getExports.js
tests/src/rules/default.js
tests/src/rules/export.js
tests/src/rules/named.js
tests/src/rules/namespace.js
tests/src/rules/no-errors.js
tests/src/rules/no-unresolved.js

Updated to Babel 6 for compile + runtime, and switching to Babylon directly as default parser.

Babel 6 + Babylon

---

src/core/getExports.js
src/core/parse.js
src/core/resolve.js
tests/files/jsx/App.js
tests/files/redux.js
tests/src/core/getExports.js
tests/src/rules/default.js

Consider `ecmaFeatures.jsx` during dependency parse

---

.eslintrc
README.md
src/.eslintrc
src/core/parse.js
src/rules/default.js
src/rules/export.js
src/rules/imports-first.js
src/rules/named.js
src/rules/namespace.js
src/rules/no-duplicates.js
src/rules/no-errors.js
src/rules/no-named-as-default.js
src/rules/no-require.js
src/rules/no-unresolved.js
tests/src/rules/no-unresolved.js

Fixes #90 by adding a `commonjs` boolean option to `no-unresolved`.

Optionally resolve single-argument `require` calls.

---

.travis.yml
appveyor.yml
package.json
src/core/getExports.js
src/rules/no-unresolved.js
tests/files/mutator.js
tests/src/core/getExports.js

two-stage caching: level one on hash of settings object, level 2 on path.
- also: using mtime to invalidate cache entries for long processes (fixes #117)
Need to investigate using a short blackout to avoid the overhead of calling `fs.statSync` on every import. Even <1s would be useful, likely.

Cache correctness

---

.gitignore
.npmignore
appveyor.yml
package.json
resolvers/node/index.js
resolvers/node/package.json
resolvers/webpack/index.js
resolvers/webpack/package.json
resolvers/webpack/test/package-mains/jam/package.json
resolvers/webpack/test/package-mains/jsnext/package.json
resolvers/webpack/test/package-mains/package.json
resolvers/webpack/test/package-mains/webpack.alt.config.js
resolvers/webpack/test/package-mains/webpack/package.json
resolvers/webpack/test/packageMains.js
src/core/getExports.js
tests/files/node_modules/a/index.js
tests/files/node_modules/es6-module/index.js
tests/src/rules/named.js

Closes #103.
- node resolver defers to `jsnext:main` in `package.json`.
- webpack resolver will as well, in addition to respecting Webpack's `resolve.packageMains` field properly.
- **breaking**: `import/ignore` patterns are checked only once export parsing has yielded no results. 
This means `node_modules` with `jsnext:main` (i.e. Redux) will have names collected in spite of `node_modules` being ignored by default.

jsnext:main

---

resolvers/webpack/index.js
resolvers/webpack/test/config.js
resolvers/webpack/test/files/some/absolute.path.webpack.config.js

As the title, I have a project structure akin to:
```
node/webpack.config.js
node/package.json
src/module1/submodule/...
src/module2/submodule/...
```
And I alias each src/moduleX folder to something more succinct. Names have been changed to keep identity of real code secret etc ;)
Hence, it would be handy for me to be able to just specify an absolute webpack location. This change makes that possible and tests it.
Thanks for the great plugin!

Allow 'absolute' specification of webpack config.

---

README.md
docs/rules/default.md
docs/rules/export.md
docs/rules/imports-first.md
docs/rules/named.md
docs/rules/namespace.md
docs/rules/no-duplicates.md
docs/rules/no-named-as-default.md
docs/rules/no-require.md
docs/rules/no-unresolved.md

in traditional ESLint `docs/rules/[rule name].md` fashion.
closes #128 
Style guide:

separate rule docs

---

resolvers/webpack/resolve-alias.js
resolvers/webpack/test/alias.js

In my project, I have nested my private aliases in a namespace-ish manner.
My `resolve.alias` looks somewhat like:
```javascript
resolve: {
alias: {
'ns/module1': path.resolve('...'),
'ns/module2': path.resolve('...')
}
}
```
This functions in webpack but wasn't functioning with the slightly simpler implementation of `matchAlias` in the webpack resolver.
This patch looks for a common prefix in the `source` and `alias` in `matchAlias` and fixes configs as above.

Allow 'nested' aliases in resolve config

---

.npmignore
config/stage-0.js
docs/rules/no-deprecated.md
package.json
src/core/declaredScope.js
src/core/getExports.js
src/core/parse.js
src/index.js
src/rules/export.js
src/rules/namespace.js
src/rules/no-deprecated.js
tests/files/deprecated-file.js
tests/files/deprecated.js
tests/src/core/getExports.js
tests/src/rules/no-deprecated.js

mostly just seeing if tests pass. will continue work inside `master`, probably.

rule: no-deprecated

---

gulpfile.js
src/core/getExports.js
src/rules/default.js
src/rules/export.js
src/rules/named.js
src/rules/namespace.js
src/rules/no-deprecated.js
src/rules/no-named-as-default.js
tests/files/deep/cache-1.js
tests/files/deep/cache-2a.js
tests/files/deep/cache-2b.js
tests/files/issue210.config.js
tests/files/issue210.js
tests/files/narcissist.js
tests/src/cli.js
tests/src/core/getExports.js
tests/src/rules/export.js
tests/src/rules/named.js
tests/src/rules/namespace.js

Use full `ExportMap` as deep namespace name maps. Stats on every access for cache correctness under `eslint_d`/`eslint-loader`. (fixes #200)
Explicitly detect and exit 0-deep self-exports. (fixes #210)

deep namespaces: correct caching

---

src/core/resolve.js

In a project where I have import/no-unresolved enabled, I get the
following results with ESLint's TIMING=1 environment variable enabled:
```
Rule                          | Time (ms) | Relative
:-----------------------------|----------:|--------:
import/no-unresolved          | 18563.065 |    40.6%
react/sort-comp               |  1621.646 |     3.5%
no-irregular-whitespace       |  1386.958 |     3.0%
react/prop-types              |  1197.552 |     2.6%
no-implied-eval               |   829.967 |     1.8%
react/jsx-uses-vars           |   765.702 |     1.7%
keyword-spacing               |   765.665 |     1.7%
no-eval                       |   578.730 |     1.3%
semi-spacing                  |   549.684 |     1.2%
no-whitespace-before-property |   477.285 |     1.0%
```
To speed up this …

Cache fileExists in core/resolve

---

.babelrc
package.json
src/core/getExports.js
src/core/parse.js
src/core/resolve.js
src/rules/export.js
src/rules/namespace.js
src/rules/no-deprecated.js
src/rules/no-duplicates.js
src/rules/no-unresolved.js
tests/src/core/getExports.js
tests/src/package.js
tests/src/rules/no-unresolved.js
tests/src/utils.js

Lost babel-runtime. Switched to loose ES2015.

Simpler babel settings

---

CHANGELOG.md
README.md
docs/rules/no-namespace.md
src/index.js
src/rules/no-namespace.js
tests/src/rules/no-namespace.js

Reports if namespace import is used.
Valid:
```js
import defaultExport from './foo'
import { a, b }  from './bar'
import defaultExport, { a, b }  from './foobar'
```
...whereas here imports will be reported:
```js
import * as foo from 'foo';
import defaultExport, * as foo from 'foo';
```
One should only import names which are needed in current scope, nothing more.
Additonally, users of tools like [rollup.js](http://rollupjs.org/) or [webpack](https://webpack.github.io/) 2.0 which support tree shaking would benefit in a smaller bundle size because unused exports that are not imported can be eliminated.
If all names are required in addition to separate named exports, developer might export default object with all required members:
```js
export const FOO = 1;
export const BAR = 2;
export …
```

Add no-namespace rule

---

CHANGELOG.md
README.md
docs/rules/no-named-as-default-member.md
src/index.js
src/rules/no-named-as-default-member.js
tests/src/rules/no-named-as-default-member.js

Add rule no-named-as-default-member

---

CHANGELOG.md
README.md
docs/rules/no-extraneous-dependencies.md
package.json
src/core/importType.js
src/core/staticRequire.js
src/index.js
src/rules/no-extraneous-dependencies.js
tests/.eslintrc
tests/files/importType/index.js
tests/files/package.json
tests/src/core/importType.js
tests/src/rules/no-extraneous-dependencies.js

Add `no-extraneous-dependencies` rule
(kinda) Continuous of https://github.com/jfmengels/eslint-plugin-import-order/pull/9.
I've added two files : `core/importType` and `core/staticRequire`. I use those in `import-order` for the import-order` rule, and will also use them in the no builtin rule probably.
Let me know if there's anything I need to change :)
(If this gets merged, I'll get started on the PRs for `import-order` and no builtin, but this reuses some of the same code)

Add `no-extraneous-dependencies` rule

---

CHANGELOG.md
resolvers/webpack/index.js
resolvers/webpack/test/fallback.js
resolvers/webpack/test/files/webpack.array-root.config.js
resolvers/webpack/test/files/webpack.config.js

Add [resolve.fallback](https://webpack.github.io/docs/configuration.html#resolve-fallback) to the paths used to resolve modules in webpack.

Consider also resolve.fallback while resolving modules with webpack

---

src/rules/imports-first.js
tests/src/rules/imports-first.js

Fixes #255. Per discussion in that issue, directives need to appear at the top of a file in order to be considered directives. This isn't usually a problem because modules remove the need for `'use strict'`, but we use a custom directive as part of our build system. This PR makes `imports-first` understand directives and not throw errors when those appear above import statements.
cc/ @benmosher, let me know if anything else is needed; I didn't see a contributing file in the repo so not sure what the best practices are.

Make imports-first treat directives as an exception

---

CHANGELOG.md
README.md
docs/rules/no-nodejs-modules.md
src/index.js
src/rules/no-nodejs-modules.js
tests/src/rules/no-nodejs-modules.js

Add `no-nodejs-modules` rule (fixes #158)
(I've taken the liberty of naming it this way, as I find it to be more explicit than the proposed `no-core`)

Add `no-nodejs-modules` rule (fixes #158)

---

CHANGELOG.md
src/core/getExports.js
src/rules/named.js
tests/files/re-export-default.js
tests/src/rules/named.js

fixes #251: will assume you know what you're doing when you re-export from a non-ES-module.

named: should ignore ignored modules for re-exported names

---

.eslintrc.yml
src/core/getExports.js
src/core/hash.js
src/core/parse.js

I missed those quotes while doing other PR: https://github.com/benmosher/eslint-plugin-import/pull/245#discussion_r61135535 :)
Now it should be harder to miss that :)

Enable `quotes` rule for eslint

---

package.json
resolvers/webpack/index.js
resolvers/webpack/test/config.js
resolvers/webpack/test/files/webpack.config.babel.js

from the excellent work by @gausie just trying to get it across the finish line.

compile webpack.configs

---

package.json
resolvers/webpack/package.json

Users downloading the package from npm might have had problems since it wasn't downloading this required dependency.
Fixes #286

Move 'interpret' to webpack loader's package.json.

---

.travis.yml
CHANGELOG.md
appveyor.yml
src/core/resolve.js
src/rules/no-named-as-default-member.js
tests/src/rules/no-named-as-default-member.js
tests/src/utils.js

Track progress against this PR. 
Known issues:
- #272: don't pass null to path functions

Support Node v6

---

CHANGELOG.md
src/rules/no-named-as-default-member.js
tests/src/rules/no-named-as-default-member.js
tests/src/utils.js

added syntax battery to test utils for future use

---

CHANGELOG.md
docs/rules/no-extraneous-dependencies.md
src/rules/no-extraneous-dependencies.js
tests/files/package.json
tests/src/rules/no-extraneous-dependencies.js

`no-extraneous-dependencies`: add both support for and an option to disable `optionalDependencies' (fixes #266).
I've changed the error message a bit, as I don't see how the previous one actually made sense (for the `devDependency` error).

`no-extraneous-dependencies`: add support/option for `optionalDependencies'

---

CHANGELOG.md
docs/rules/order.md
src/rules/order.js
tests/src/rules/order.js

Checks existence of new lines between and inside import groups.
Implements #282.

Add `newlines-between` option to `order` rule

---

CHANGELOG.md
docs/rules/extensions.md
gulpfile.js
src/core/importType.js
src/rules/extensions.js
tests/src/rules/extensions.js

Fixes #295 and #271. 
Actually made the rule work report on violations in spite of file resolution; it will use the source path if the file doesn't exist. I think this is probably ideal, in contrast to other rules that ignore unresolved files (in spite of my previous comments).
I also added an early exit for builtins (i.e. `path`) regardless of the options, built on @jfmengels' `importType` infrastructure. I figure even with `always` mode enabled, it should be possible to import from core modules.
Also, note that `extension` is `""` when the provided path is `null` or has no extension, thus the added `!extension` check for the extension-enforcing branch.
Feedback from @vvo, @lo1tuma, @sindresorhus, @jfmengels appreciated.

Unresolved extensions

---

src/rules/no-mutable-exports.js
tests/src/rules/no-mutable-exports.js

`no-mutable-exports`: Handle ES7 export extensions. Fixes #317 :)

`no-mutable-exports`: Handle ES7 export extensions. Fixes #317

---

CHANGELOG.md
src/rules/no-extraneous-dependencies.js
tests/files/package.json
tests/src/rules/no-extraneous-dependencies.js

`no-extraneous-dependencies`: Handle scoped packages. Fixes #316 and #323
cc @krainboltgreene @stipsan

`no-extraneous-dependencies`: Handle scoped packages. Fixes #316

---

CHANGELOG.md
src/core/getExports.js
src/rules/export.js
tests/files/deep-es7/b.js
tests/files/deep/b.js
tests/files/re-export.js
tests/src/rules/default.js
tests/src/rules/export.js
tests/src/rules/named.js
tests/src/rules/namespace.js

Supersedes #331, handles `export * from '...'` suppression of `default` in all static analysis rules.
cc @jkimbo

fix #328: properly suppress `default` when looking at * exports.

---

src/rules/no-duplicates.js
tests/src/rules/no-duplicates.js

Fix #225
If import is a flow `type` import, add to separate map for duplicate checking.

Check duplicates for normal imports and flow type imports separately

---

package.json
src/rules/newline-after-import.js
tests/src/rules/newline-after-import.js

This PR fixes #318.
Actually I’m not convinced that this rule really makes sense for commonjs, there are just too many edge-cases and no way to say which to exclude from this rule, e.g. the following:
```js
require('a');
foo(require('b'), require('c'), require('d'));
var assign = Object.assign || require('object-assign');
const nightwatchConfig = { seleniumPath: require('selenium-standalone').path };
```
I’ve tried my best to handle those cases.

Fix newline-after-import rule for require

---

CHANGELOG.md
docs/rules/order.md
src/rules/order.js
tests/src/rules/order.js

Fixes all issues mentioned in #313:
1. Empty lines between multiline import statements are detected correctly.
2. Not assigned imports are ignored (see comments).
3. `require` used inside objects are ignored.
It also changes requirement - there's no specific limit about 1 empty line between groups. Now it has to be **at least** 1. If one would like to have only one, then `no-multiple-empty-lines` core rule can be used (thx @lo1tuma for hint!).
I'm not 100% sure about implementation for last one - it works for provided test cases, yet I could use another pair of eyes.

Fix order's `newlines-between` edge cases

---

CHANGELOG.md
resolvers/webpack/README.md
resolvers/webpack/index.js
resolvers/webpack/test/config.js
resolvers/webpack/test/files/webpack.config.multiple.js

If the Webpack config is an array, then this change will use the first config that includes a resolve section.

Adding handling for multiple Webpack configs

---

CHANGELOG.md
docs/rules/prefer-default-export.md
src/rules/newline-after-import.js
src/rules/prefer-default-export.js
tests/src/rules/prefer-default-export.js

Builds off of #343, but adds support for
- deep destructuring (`export const { foo: { bar } } = ...`)
- re-export (`export * from './foo'`)
- no exports (threw an error)
CC @scottnonnenberg, @gavriguy

Fix prefer default

---

src/rules/newline-after-import.js
src/rules/prefer-default-export.js
tests/src/rules/prefer-default-export.js

Fixes #342. Instead of counting the number of `ExportNamedDeclaration` nodes, we count the number of properties in its child `ObjectPattern`.
A couple other style fixes.

Fix prefer default in multiple named export case

---

CONTRIBUTING.md

Given the recent uptick in interest, I figure the time has come to get something like this into `master`. Feels a little goofy to do something like this for a project that is just a plugin for something much larger, but at the same time, this is my primary open source project and it's been getting a lot of great contributions lately.
Comments are encouraged. I've not tried to write anything like this before and in general my written voice can be confusing and pedantic at the best of times.
(closes #257)

first draft of CONTRIBUTING.md

---

CHANGELOG.md
package.json
resolvers/webpack/package.json

Releasing bugfixes + minor improvements to core plugin + Webpack resolver.
#332 feels semver-minor because it's large, but in all likelihood it just hasn't impacted anyone before @jkimbo brought it up. So probably valid semver-patch.
Tasks:

Release v1.8.1, webpack/0.2.5

---

CHANGELOG.md
src/rules/prefer-default-export.js
tests/src/rules/prefer-default-export.js

Fixes #358.
The fixes to support multiple declarations left out a crucial else case.

prefer-default-export: Support 'export function foo() {}; export const x = 4;'

---

CHANGELOG.md
docs/rules/no-deprecated.md
src/core/getExports.js
tests/files/tomdoc-deprecated.js
tests/src/rules/no-deprecated.js

Add TomDoc support to no-deprecated rule

---

CHANGELOG.md
README.md
package.json
src/core/resolve.js

With this PR users will be able to require resolvers:
1) With absolute paths (`/Volumes/...`, user can include them as computed property in `.eslintrc.js` config)
2) With paths, relative to closest package.json (`./eslint-plugins/webpack-resolver`)
3) With custom npm modules names (`@myorg/webpack-resolver`)
4) With conventional npm modules names (`webpack` -> `eslint-import-resolver-webpack`)

Custom resolver path

---

src/core/resolve.js
tests/files/foo-bar-resolver.js
tests/src/core/resolve.js

You cannot call resolve without a 2nd argument - but because we now pass the source directory, not the modulePath, it will always be absolute so you don't need to.
Added a test as well, covering the situation this fixes and also the situation I use the custom resolver for.

do not resolve the source directory. Fixes #367

---

CHANGELOG.md
README.md
package.json
src/core/resolve.js

There are more things I had hoped to complete during this release, but it's been a while so probably best to ship what's done, first.
officially broken, can't release as-is

v1.9.0 bump

---

CHANGELOG.md
src/rules/newline-after-import.js
tests/src/rules/newline-after-import.js

Fix crash with `newline-after-import` related to the use of switch cases (fixes #386)
The error came because a switch case has a scope
- I've added a small safe-guard that should prevent the same kind of crash in this part of the code
- I have made it so no errors can come from inside switch cases. I tried returning the switch case `cases` items, but then it reports an error even if I space them correctly. Maybe someone wants to take a further look into it, but I'm out of time right now.
cc @ljharb @singles

Fix crash with `newline-after-import` related to the use of switch cases (fixes #386)

---

README.md

Adds a missing `s` to the path.

fix link to no-restricted-paths docs

---

CHANGELOG.md
package.json

release v1.10.1

---

CHANGELOG.md
package.json
src/core/getExports.js
src/core/resolve.js
src/rules/export.js
src/rules/namespace.js
src/rules/no-duplicates.js
src/rules/no-mutable-exports.js
src/rules/no-named-as-default-member.js
src/rules/no-unresolved.js
tests/src/package.js

There appear to be complications due to pollution of global scope with `Symbol` polyfill on Node 0.10.
Seems like the gentle thing is to fix it in 1.x, since 2.x will (a) be released soon and (b) support Node LTSs >= 4.
(fixes #415, hopefully)

remove for-of syntax from rules

---

.babelrc
.gitignore
appveyor.yml
gulpfile.js
package.json
src/core/getExports.js
tests/src/cli.js
tests/src/package.js

mostly just validating my test/coverage improvements with Travis + Appveyor

merge release 1.10.3

---

CHANGELOG.md
docs/rules/no-extraneous-dependencies.md
src/rules/no-extraneous-dependencies.js
tests/files/package.json
tests/src/rules/no-extraneous-dependencies.js

`no-extraneous-dependencies`: add support/option for `peerDependencies` (#423)

`no-extraneous-dependencies`: add support/option for `peerDependencies` (#423)

---

resolvers/node/package.json

eslint-import-resolver-node is not intended to be installed as a sibling of eslint-plugin-import, which is the sole purpose of `peerDependencies`
closes #437

Remove peerDependency on eslint-plugin-import

---

resolvers/webpack/index.js
resolvers/webpack/test/files/webpack.config.js

index.js contains the fix
webpack.config.js contains code that trips an error if fix not present.
Initial git clone test gave two errors which are not related to this fix.

Fixes #411

---

resolvers/webpack/index.js
resolvers/webpack/test/files/node_modules/webpack-resolver-plugin-test/index.js
resolvers/webpack/test/files/webpack.config.js
resolvers/webpack/test/plugins.js

Hello.
I use `webpack.ResolverPlugin` in my project in order to add my own resolvers:
https://github.com/webpack/docs/wiki/list-of-plugins#resolverplugin
`eslint-import-resolver-webpack` is not supporting such a way adding plugins now. This pull request solves the problem (see the code).

Webpack resolver plugin

---

CHANGELOG.md
README.md
docs/rules/order.md
src/core/importType.js
tests/src/core/importType.js

In one project we wanna use `order` rule with configuration
```json
{
"groups": [
["builtin", "external"],
["internal", "parent", "sibling", "index"]
],
"newlines-between": "always"
}
```
but our frontend uses `bower` and `webpack` aliases.

consider modules from `bower_components' and 'jspm_modules` as external modules

---

CHANGELOG.md
src/rules/no-nodejs-modules.js
tests/src/rules/no-nodejs-modules.js

Modified error message to include the module's name (fixes #453)

Modified error message to include the module's name (fixes #453)

---

CHANGELOG.md
docs/rules/namespace.md
src/rules/namespace.js
tests/src/rules/namespace.js

Changed my mind, too much work to make this a separate rule, and it can easily be exposed as an option in v1.x. 😅
I'm not even sure if it should default to `true` in v2...

add `allowComputed` option to `namespace` (fixes #456)

---

resolvers/webpack/index.js
resolvers/webpack/package.json
resolvers/webpack/test/package-mains/module/package.json
resolvers/webpack/test/packageMains.js

Closes #265
Fixed some lint failures in the plugin along the way.
I don't have test coverage because it seems like it'd be a bunch of additional work to scaffold it into place, because it would require tooling to install dependencies for the test fixtures.
I tested manually and it works on my project, though.

Add webpack 2 support

---

CHANGELOG.md
package.json
src/core/getExports.js
src/core/ignore.js
tests/files/typescript.ts
tests/src/core/getExports.js

Fixes #478 by always respecting `import/extensions`, in spite of file content.

make import/extensions great again

---

CHANGELOG.md
README.md
package.json
src/core/getExports.js
src/core/ignore.js
src/core/parse.js
tests/files/typescript.ts
tests/src/core/getExports.js
tests/src/core/parse.js

Closes #407. Allows TypeScript or other alt-JS dependencies to be configured via [`import/parsers` setting](https://github.com/benmosher/eslint-plugin-import/tree/typescript#importparsers).
cc @santiagoaguiar, @denneulin for feedback since you two 👍'd the original issue I created. 😎

support alt-JS dependencies

---

CHANGELOG.md
README.md
docs/rules/namespace.md
docs/rules/no-extraneous-dependencies.md
import.sublime-project
package.json
resolvers/node/CHANGELOG.md
resolvers/node/index.js
resolvers/node/package.json
resolvers/webpack/CHANGELOG.md
resolvers/webpack/index.js
resolvers/webpack/package.json
resolvers/webpack/test/package-mains/module/package.json
resolvers/webpack/test/packageMains.js
src/core/getExports.js
src/core/ignore.js
src/core/parse.js
src/rules/namespace.js
src/rules/no-nodejs-modules.js
tests/files/commonjs-namespace/a.js
tests/files/commonjs-namespace/b.js
tests/files/typescript.ts
tests/src/core/getExports.js
tests/src/core/parse.js
tests/src/rules/namespace.js
tests/src/rules/no-nodejs-modules.js
tests/src/utils.js

cc @jfmengels. I want to get `import/parsers` published so I can use it at work.
Also I clearly forgot to do this for 1.13.0 😳, only changes are the bugfix for #416 (PR #499) and `import/parsers` via #503. I have QA'd.
**PR summary:**
- #499: fix #416 
- #503: add `import/parsers` to support ES-module-compliant alt-JS interop
It'd probably be good if you took a look at the `import/parsers` config schema. Though v2 is on the horizon so we could break it if needed/desired as part of that release... only thing I'm thinking is whether it should be glob- or regex-based instead of array-of-extensions. I like AoE mostly for consistency with `import/extensions`, and it's easy to grok. Con: less powerful, but could be enhanced to support glob/regex later if desired.

release v1.14.0

---

CHANGELOG.md
docs/rules/no-nodejs-modules.md
src/rules/no-nodejs-modules.js
tests/src/rules/no-nodejs-modules.js

Add `allow` option to `no-nodejs-modules` rule (fixes #452)
cc @ljharb

Add `allow` option to `no-nodejs-modules` rule (fixes #452)

---

resolvers/webpack/README.md

Took a while to hunt down why my config wasn't working and figured out that I needed to add this dependency only after reading through [#238](https://github.com/benmosher/eslint-plugin-import/issues/238) and noticing [this line in a linked example](https://gist.github.com/ravasthi/abcfee465411fc45a8bc28decb9d8e5e#file-package-json-L24).
I think adding this line may add some clarity and save time for several other webpack / eslint noobs (like me 😄 ).

Suggested change to readme

---

CHANGELOG.md
README.md
docs/rules/no-absolute-path.md
src/core/importType.js
src/index.js
src/rules/no-absolute-path.js
tests/src/core/importType.js
tests/src/rules/no-absolute-path.js

Add `no-absolute-path` rule (fixes #530)

Add `no-absolute-path` rule (fixes #530)

---

docs/rules/no-extraneous-dependencies.md
package.json
src/rules/no-extraneous-dependencies.js
tests/src/rules/no-extraneous-dependencies.js

Following the suggestion in https://github.com/benmosher/eslint-plugin-import/issues/470#issuecomment-237035169.
Fixes #470.

Allow filename patterns for rule no-extraneous-dependencies.

---

CHANGELOG.md
README.md
docs/rules/max-dependencies.md
docs/rules/no-absolute-path.md
docs/rules/no-extraneous-dependencies.md
docs/rules/no-nodejs-modules.md
docs/rules/prefer-default-export.md
package.json
resolvers/webpack/README.md
src/core/importType.js
src/index.js
src/rules/max-dependencies.js
src/rules/no-absolute-path.js
src/rules/no-extraneous-dependencies.js
src/rules/no-named-as-default-member.js
src/rules/no-nodejs-modules.js
tests/files/default-export-default-property.js
tests/src/core/importType.js
tests/src/rules/max-dependencies.js
tests/src/rules/no-absolute-path.js
tests/src/rules/no-extraneous-dependencies.js
tests/src/rules/no-named-as-default-member.js
tests/src/rules/no-nodejs-modules.js

Should've really just done this last week 😳

release v1.15.0

---

resolvers/webpack/index.js
resolvers/webpack/test/files/webpack.function.config.js
resolvers/webpack/test/root.js

Webpack 2 supports webpack configuration files that export a function (see https://webpack.github.io/docs/roadmap.html). This commit adds support for this by testing if the `require`ed config is a function, and if so, executing it.

Support webpack configs that export a function

---

docs/rules/no-extraneous-dependencies.md

Updated docs with glob example to prefix with `**/`
https://github.com/benmosher/eslint-plugin-import/pull/527#issuecomment-247046156

#527: Correct docs for rule no-extraneous-dependencies

---

docs/rules/no-named-as-default.md

Since [Additional export-from statements in ES7](https://github.com/leebyron/ecmascript-more-export-from) has been separated repo in [export-ns-from](https://github.com/leebyron/ecmascript-export-ns-from) and [export-default-from](https://github.com/leebyron/ecmascript-export-default-from), reference link need to update.

docs: Update obsoleted reference

---

tests/src/rules/export.js

Fix #564: Fix tests not running due to Espree bump.
I changed the tests to use babel-eslint, because they are now invalid with Espree 3.2.0.
One of the tests didn't work correctly with both parsrs, so I just disabled it.
Blocks #555
cc @ljharb

Fix #564: Fix tests not running due to Espree bump

---

docs/rules/extensions.md
package.json
resolvers/webpack/index.js
src/rules/extensions.js
tests/src/rules/extensions.js

[New] `extensions`: accept both a string, and an object to override it.

---

CHANGELOG.md
README.md
docs/rules/no-dynamic-require.md
src/index.js
src/rules/no-dynamic-require.js
tests/src/rules/no-dynamic-require.js

Add `no-dynamic-require` rule (fixes #567)

Add `no-dynamic-require` rule (fixes #567)

---

CHANGELOG.md
README.md
docs/rules/no-webpack-loader-syntax.md
src/index.js
src/rules/no-webpack-loader-syntax.js
tests/src/rules/no-webpack-loader-syntax.js

[Webpack allows specifying loaders](https://webpack.github.io/docs/loaders.html#introduction) and their configuration inline in imports using a non-standard syntax in the path. This rule allows disabling imports like this.
It can be useful for people using Webpack who don't want their code to rely on this Webpack-specific feature and we can possibly use it in Create React App to fix https://github.com/facebookincubator/create-react-app/issues/733.

Add new rule `no-webpack-loader-syntax`

---

CHANGELOG.md
docs/rules/newline-after-import.md
src/rules/newline-after-import.js
tests/src/rules/newline-after-import.js

Breaking change - newline-after-import: Do not require empty line after inline `require` (fixes #570).
cc @singles @sindresorhus
I made two commits:
- One applying the change and making the new tests pass
- One simplifying the implementation by removing the whole usage of scopes (redundant with the level system I picked from the order rule, and a bit more complex IMO)

Fix #570: No newline after inline require

---

src/rules/no-internal-modules.js
tests/src/rules/no-internal-modules.js

Fixes #577 by counting the steps that do not start with `@`

[no-internal-modules] allow importing @-scoped modules

---

CHANGELOG.md
docs/rules/order.md
src/rules/order.js
tests/src/rules/order.js

Fix #519: Add option `newlines-between: "ignore"` to `order`
I haven't yet changed the default option, which I think we should, as I have not yet see any comments from others. That can be done in a second time, but should it be done, it should be done before the v2 release

Fix #519: Add option `newlines-between: "ignore"` to `order`

---

CHANGELOG.md
README.md
docs/rules/no-unassigned-import.md
src/index.js
src/rules/no-unassigned-import.js
tests/src/rules/no-unassigned-import.js

Fix #529: Add rule `no-unassigned-import`
Just wanted to work on this rule. If you feel like adding it to v2.0, feel free to do so, or we can wait a bit and include it then. Either way is fine.

Fix #529: Add rule `no-unassigned-import`

---

CHANGELOG.md
resolvers/node/index.js
resolvers/node/package.json
resolvers/webpack/index.js
resolvers/webpack/package.json
src/rules/extensions.js
src/rules/max-dependencies.js

Fixes #604.
I replaced `object-assign` and `es6-set` by native `Objct.assign` and `Set`. Since we dropped support for Node < v4, this should not break anything.

#604: Fixed code that relied on removed dependencies

---

resolvers/webpack/README.md
resolvers/webpack/index.js
resolvers/webpack/test/config.js

...because my Webpack config is generated by an API (and not written to disk) and `.eslintrc.js` allows us to use complex JavaScript objects.

Update webpack resolver to allow passing a config object rather than filename

---

src/core/staticRequire.js
tests/src/rules/no-extraneous-dependencies.js

Fixes #610: Fix crash when calling require() with a number

(#610): Fix crash when calling require() with a number

---

CHANGELOG.md
src/rules/prefer-default-export.js
tests/src/rules/prefer-default-export.js

(#609) Make prefer-default-export count re-exported default exports
The rule didn't count re-exporting default exports, which led to it reporting where it shouldn't have.
I also moved out the `captureDeclaration` function declaration because I easily could and so that it wouldn't get re-declared for every encountered `ExportNamedDeclaration`.

(#609) Make prefer-default-export count re-exported default exports

---

CHANGELOG.md
src/rules/newline-after-import.js
tests/src/rules/newline-after-import.js

This fixes the crash outlined in #592, when using a `require` statement inside a decorator.
While I was in there I also noticed that `newline-after-import` wasn't properly reporting if the next line was a decorator. I added this so it would be properly reported, but I can remove that if decorator support isn't something you want to add (I know it's still experimental).

newline-after-import with decorators

---

src/rules/no-extraneous-dependencies.js
tests/src/rules/no-extraneous-dependencies.js

Fixes #602.
This should be semver-minor.

[New] `no-extraneous-dependencies`: check both the absolute and relative filename

---

src/index.js
src/rules/imports-first.js
tests/src/package.js

Over on [eslint-find-rules](https://github.com/sarbbottam/eslint-find-rules), there has been some discussion about being able to detect deprecated rules in order to [not report them as unused](https://github.com/sarbbottam/eslint-find-rules/issues/172) and to [report when they are still being used](https://github.com/sarbbottam/eslint-find-rules/issues/188).
In order to implement those features, there needs to be a way to detect that a rule has been deprecated.  Core ESLint rules that are deprecated are marked as such in their metadata.
This PR adds the same `deprecated` flag to the metadata of the deprecated rule in this plugin.
I added a very specific spec for this rule to make sure that `imports-first` is marked as deprecated, but `first` (which is its new name) is not.  There might be …

Add deprecated flags to imports-first metadata

---

CHANGELOG.md
src/rules/prefer-default-export.js
tests/src/rules/prefer-default-export.js

Ignoring flow type exports

---

src/ExportMap.js
tests/files/malformed.js
tests/src/core/getExports.js
tests/src/rules/named.js
utils/unambiguous.js

Key notes:
- used a `&&` instead of `||` for the auto-ignore (fail) so it wasn't even used unless the file is ignored anyway, and then it would ignore the ignore if the regex passed
- did not set regex to `multiline` mode, so it would fail on files unless `import`/`export` is the first line (double fail)
I also had to comment out a parser error test for CoffeeScript that should never have passed in v2 if I had implemented this correctly to begin with.
To publish this, need to bump+publish `eslint-module-utils`, then bump the dep in the plugin and publish it too.
I'm thinking this should be semver-minor since it's a large enough fix that it's nearly a feature.
Technically a breaking change to `eslint-module-utils`, but that's [not a big …

fix unambiguous regex

---

tests/src/package.js

From https://github.com/benmosher/eslint-plugin-import/pull/696#issuecomment-268664237

[Tests] make package tests more robust by only checking .js files

---

CHANGELOG.md
README.md
docs/rules/no-anonymous-default-export.md
src/index.js
src/rules/no-anonymous-default-export.js
tests/src/rules/no-anonymous-default-export.js

Forbids exporting anonymous functions, literals, class expressions, or arrow functions as module default.
This is intended to improve the grepability of codebases by encouraging the re-use of identifiers at their declaration site and at their import sites.
```js
export default []
export default () => {}
export default class {}
export default function () {}
export default 123
export default {}
```
```js
const foo = 123
export default foo
export default class MyClass() {}
export default function foo() {}
/* eslint import/no-anonymous-default-export: [2, {"allowArray": true}] */
export default []
/* eslint import/no-anonymous-default-export: [2, {"allowArrowFunction": true}] */
export default () => {}
/* eslint import/no-anonymous-default-export: [2, {"allowAnonymousClass": true}] */
export …
```

Add `no-anonymous-default-export` rule

---

CHANGELOG.md
docs/rules/order.md
src/rules/order.js
tests/src/rules/order.js

New option to allow newlines inside import groups. See #627.

Add 'always-and-inside-groups' value to order's newlines-between option to allow newlines inside import groups

---

CHANGELOG.md
docs/rules/newline-after-import.md
src/rules/newline-after-import.js
tests/src/rules/newline-after-import.js

My team likes to maintain two newlines after import statements instead of just one. In the interest of making that convention enforceable, these changes add a `newlines` option to the `newline-after-import` rule. This option defaults to `1` to maintain full backwards compatibility.

Add `count` option to `newline-after-import`

---

CHANGELOG.md
package.json

Fix "default is a reserved keyword" error no-named-default tests

---

docs/rules/no-extraneous-dependencies.md

Docs required a close reading to realize that the glob array actually *disables* errors for the config option for matching files. This changes the description to be more explicit about what "activation" means for matching files.

Clarify docs for glob arrays

---

tests/src/rules/no-mutable-exports.js

This adds a test for the bug reported in issue #758 and #660, which was already fixed by https://github.com/benmosher/eslint-plugin-import/commit/bfdc2bbfa16c2d27fa24ee0665ffb41040ef696c. :)
If I revert that commit, the test fails with this error:
```
1) no-mutable-exports valid type Foo = {}
export type {Foo}:
TypeError: Cannot read property 'kind' of null
at checkDeclaration (src/rules/no-mutable-exports.js:7:37)
at checkDeclarationsInScope (src/rules/no-mutable-exports.js:19:15)
at EventEmitter.handleExportNamed (src/rules/no-mutable-exports.js:41:11)
at NodeEventGenerator.applySelector (node_modules/eslint/lib/util/node-event-generator.js:265:26)
at NodeEventGenerator.applySelectors (node_modules/eslint/lib/util/node-event-generator.js:294:22)
at NodeEventGenerator.enterNode …
```

Add test for flow type export

---

CHANGELOG.md
docs/rules/no-extraneous-dependencies.md
src/rules/no-extraneous-dependencies.js
tests/files/with-syntax-error/package.json
tests/src/rules/no-extraneous-dependencies.js

Add support for nested package.json, projects with a folder architecture with internals package.json files (see https://github.com/benmosher/eslint-plugin-import/issues/458).
Actually change the behavior of use the closest package.json to use the root package.json breaks the rule when you _want_ to check the dependencies from an internal package.json, so I have this two paths in mind:
1) Per default get the dependencies from the closest package.json and if the option `getPkgFromRoot` is true get the dependencies from the root package.json file.
2) Add an option like `pkgPath` to the rule to be able to specify the package.json path and if is null just find the closest package.json like the last version. IMHO this looks better, it's more flexible.
**What do you think about this?**
I choose …

Add support to specify the package.json for no-extraneous-dependencies rule

---

src/ExportMap.js

- ignore deep CJS imports/exports
fixes #717

fix null pointer exception (#717)

---

.travis.yml
appveyor.yml

investigating #838 + probably a good idea anyway

update CI to build on Node 6+7

---

CHANGELOG.md
docs/rules/no-unassigned-import.md
src/rules/no-unassigned-import.js
tests/src/rules/no-unassigned-import.js

Add `allow` option to `no-unassigned-import` to fix #671.
I basically follow the same logic from `no-extraneous-dependencies`. With the glob matching start from `process.cwd()`. I'm not sure that this is the best solution (maybe use regexp like webpack do?), but it works. Please let me know if there is something need to be improved. Big thanks!

Support `allow` option in `no-unassigned-import`, fix #671

---

docs/rules/newline-after-import.md
src/rules/newline-after-import.js
tests/src/rules/newline-after-import.js

A PR for https://github.com/benmosher/eslint-plugin-import/issues/686
Will add autofixer for newline-after-import rule.

Autofixer for newline-after-import. Fixes #686

---

.travis.yml
appveyor.yml
package.json
src/rules/no-named-default.js
tests/src/rules/default.js
tests/src/rules/named.js
tests/src/utils.js

chore(eslint): upgrade to eslint@4

---

docs/rules/no-extraneous-dependencies.md

replace *find* with *isArray* in loadash import

fix: Written wrong

---

src/ExportMap.js
tests/files/flowtypes.js
tests/src/rules/named.js

This fixes #708 without ignoring all type imports.

Fix flow interface imports giving false-negative with `named` rule

---

src/core/importType.js
src/rules/no-absolute-path.js
tests/src/core/importType.js

See my reply here for a detailed analysis on why I made this change: https://github.com/benmosher/eslint-plugin-import/issues/803#issuecomment-303754437
I remove the call to `resolve()` in `no-absolute-path` rule. That should make this rule faster when it is used as a standalone rule or with other rules that are not dependent on having to resolve file paths.
As I currently see no reason to have to call `resolve()` for this rule at all. However, I am new to the code, so I may be wrong. :)

Performance increase for no-absolute-path

---

CHANGELOG.md
src/core/importType.js
tests/src/core/importType.js

I was having problems with the order rule and scoped modules. It was returning NaN for the rank. I discovered the regex was not matching our scope name which contained hyphens.
This regex should match the full range of scoped module names I think. Please check it though.

Support scoped modules containing hyphens

---

src/core/importType.js
tests/src/core/importType.js

Closes #886.
Lets users add packages to `core-modules` such as `electron`, then import resources from paths such as `electron/some/path/to/resource.json` without encountering lint errors.
You have edit access to this branch – let me know if there is anything else you're looking for. Thanks!

Allow core modules to resolve files inside declared modules

---

tests/src/core/resolve.js
utils/resolve.js

Simply prevent eslint to check any parent folder of current working directory.
Fixes #720

Fix issue #720

---

CHANGELOG.md
README.md
docs/rules/exports-last.md
src/index.js
src/rules/exports-last.js
tests/src/rules/exports-last.js

Hey,
I am currently working on #620 and would like some feedback.
Currently my implementation only checks for ES Modules export declaration but I would also like to support CommonJS modules as well. Does anybody has an idea how to check if an ExpressionStatement is an CommonJS export?

exports-last

---

src/ExportMap.js

Fixes `Cannot read property 'some' of undefined`

---

resolvers/node/CHANGELOG.md
resolvers/node/index.js
resolvers/node/package.json
resolvers/node/test/native.js
resolvers/node/test/native.mjs
resolvers/node/test/paths.js

I'm assuming this is not controversial but thought it'd be good to run it through CI and get feedback just in case.

fix #939 by adding `.mjs` to stock Node resolver

---

src/rules/newline-after-import.js
tests/src/rules/newline-after-import.js

This PR simply updates the `newline-after-import` error message which was misleading when `count` was set to anything other than 1.

newline-after-import: update error message in case multiple empty lines are expected

---

CHANGELOG.md
README.md
docs/rules/group-exports.md
src/index.js
src/rules/group-exports.js
tests/src/rules/group-exports.js

Adds a new rule which prefers a particular style in exporting named members from modules.
Looking forward to hearing your feedback. Let me know if I have forgotten anything.

New: `group-exports` rule

---

docs/rules/extensions.md
src/core/importType.js
src/rules/extensions.js
tests/src/rules/extensions.js

For issue #414
Unfortunately I cannot run the tests from this repo on my machine (lots of unexplained failures) so I will have trouble writing additional tests for this new behavior.

import/extensions should have a ignorePackages option.  Fixes #414

---

docs/rules/no-extraneous-dependencies.md
src/rules/no-extraneous-dependencies.js
tests/files/package.json
tests/src/rules/no-extraneous-dependencies.js

`no-extraneous-deps` assumes, that every package that lives in a `node_modules` folder or *cannot be resolved* is an external package. This happens because of [that line](https://github.com/benmosher/eslint-plugin-import/blob/master/src/core/importType.js#L32).
If project uses aliasing, or transforms imports, this assumption is wrong, as they may not be resolvable by import plugin, but also, they should not be defined in package.json.
Changing `isExternalPath` will make any ordering lints unstable (order may change depending if you ran `npm install` or not). My proposal, is that `no-extraneous-deps` ignores packages that cannot be resolved, as otherwise it's impossible to test whether they live in `node_modules` or somewhere else.
In #903, we talked about using `import/ignore` setting, …

Make `no-extraneous-deps` lint only dependencies that can be resolved

---

resolvers/webpack/package.json

this change allows `node-libs-browser@^2.0.0` in  `eslint-import-resolver-webpack`'s deps since that's the version `webpack@^3.0.0` is using (otherwise one ends up with ^1.0.0 and ^2.0.0 installed)

allow newer version of node-libs-browser

---

package.json
src/core/importType.js

many libraries use main lodash package and a few use module-separated package, the pr is to reduce size of `node_modules` folder a bit
i was going to change to `lodash@^4.3.0`, but i just notice `eslint` use the latest version, it'll got resolved to that version anyway, so i think we can safely use that version

use main lodash package

---

docs/rules/unambiguous.md

Fix Unambiguous JavaScript Grammar link

---

src/index.js
src/rules/no-useless-path-segments.js
tests/files/bar/index.js
tests/src/rules/no-useless-path-segments.js

add no-useless-path-segments rule Fixes #471

add no-useless-path-segments rule Fixes #471

---

src/rules/no-commonjs.js
tests/src/rules/no-commonjs.js

I've added a fix for false positives for no-commonjs when `exports` is in scope.
Fixes #940.

`no-commonjs`: Fix false positive when `exports` is in scope

---

tests/src/rules/exports-last.js
utils/parse.js

See #910 and eslint/typescript-eslint-parser#346.

Always include comments when parsing

---

package.json
src/ExportMap.js
tests/files/typescript.ts
tests/src/core/getExports.js

This ensures that code using `export enum Foo {}` or `export abstract class Bar {}` registers those as exports that can be imported in other files.

Register TypeScript nodes as exports

---

src/rules/no-commonjs.js
tests/src/rules/no-commonjs.js

IMO, `a && require('a')` should be allowed.

no-common-js: allow conditional requires

---

package.json

I think there is no reason to pin the `rimraf` version to `2.5.2` strictly.

loosen the version of `rimraf` module

---

docs/rules/newline-after-import.md

Fix missing error level in “Example options usage” and add JS highlighting.

[docs] Fix `newline-after-import` example

---

docs/rules/no-anonymous-default-export.md
src/rules/no-anonymous-default-export.js
tests/src/rules/no-anonymous-default-export.js

Call expressions are not handled by the `no-anonymous-default-export` rule... not anymore!
Previously:
```js
// No error
export default foo(bar)
```
After the PR:
```js
// Error: Assign call result to a variable before exporting as module default
export default foo(bar)
```

Handle call expressions in the no-anonymous-default-export rule

---

docs/rules/order.md

This change allow copy-paste value from 1st example into eslintrc. 
It's impossible now cause valid value is `builtin` but not `buildins`.

Change 1st order's example's label to valid value

---

package.json
src/ExportMap.js
tests/files/typescript.ts
tests/src/rules/named.js

Addresses issues raised in #726 regarding TypeScript-specific AST nodes

Support named TypeScript enums/interfaces/modules

---

src/docsUrl.js
tests/src/core/docsUrl.js

This uses the version present in package.json for generating the URL to rule documentation if no [commit-ish](https://stackoverflow.com/questions/23303549/what-are-commit-ish-and-tree-ish-in-git) value is passed. I think this is good because the documentation will match the version the user has installed. This way, even if a rule is changed or removed in the future, the user can find the documentation with ease.

Use link to tagged version for rule docs

---

tests/src/rules/extensions.js

When there are multiple files with same names and different extensions, the resolver will go by extensions in the order specified in `import/resolve` settings.
This test case ensures that the `extensions` rule is correctly forcing the extension when omitting it would cause it to resolve to the wrong file.
Closes #965.

Add test case for import/resolve extensions order

---

tests/files/bar.coffee
tests/src/rules/extensions.js

Sending this PR just in case it's useful and connects some dots, feel free to close otherwise.
---
Add a test for a more unconventional extension to prove that the `extensions` rule can take anything as long as the extension resolve order is correct, i.e. it can only remove the extension if it would resolve to the correct file.
I was thinking about documenting this behavior, but [it's already documented](https://github.com/benmosher/eslint-plugin-import/blob/bc50394ce45c33f4ee54f86216270700ed329a53/docs/rules/extensions.md#exception).
Ref. #965.
Closes #583.

Add a .coffee test proving extension resolve order

---

src/rules/extensions.js
tests/src/rules/extensions.js

Support export declarations in extensions rule

---

CHANGELOG.md

Looks like it got merged into the wrong section in `CHANGELOG.md`

no-self-import is unreleased

---

tests/files/load-error-resolver.js
tests/src/core/resolve.js
utils/resolve.js

Put `try...catch` around `require.resolve()` (not `require()`)

Fixes #1023 - Load exceptions in user resolvers are not reported

---

CHANGELOG.md
docs/rules/no-default-export.md
src/index.js
src/rules/no-default-export.js
tests/src/rules/no-default-export.js

Add `no-default-export` + docs/tests

---

resolvers/webpack/index.js
resolvers/webpack/package.json

Updated resolve to ^1.4.0, where it introduced option to not preserve
symlinks when resolving, matching node's behavior.

Fix eslint-import-resolver-webpack with pnpm

---

src/rules/namespace.js
tests/src/rules/namespace.js

Fixes #656.
This is the one of long standing issue, where ESLint crashes when you are trying to use object-rest on namespace import:
```js
import * as names from './named-exports';
const {a, b, ...rest} = names; // Cannot read property 'type' of undefined
```
Also, I have noticed that it's only caused on variable declarations (in the other words, it does not crash on assignment expressions):
```js
import * as names from './named-exports';
let a, b, rest;
({a, b, ...rest} = names); // Nothing happens
```
I don't know if this is a right solution, but I think it's going to be okay ever since I found that it does not crash when it's not using variable declarations.
I will add notes to changelog and documents once this has confirmed.

#656: Fix crashes that caused when using object-rest properties in `namespace` rule

---

resolvers/webpack/index.js
resolvers/webpack/test/config.js
resolvers/webpack/test/files/webpack.function.config.js

Following https://github.com/benmosher/eslint-plugin-import/pull/938, I am facing a problem where my project is composed of a several applications and each them might define a "custom" webpack configuration which extends a common configuration which is defined in the root of the project.
```
/
apps/
- app1/
webpackConfig.js  <-- specific to app1
.eslintrc
- app2/
webpackConfig.js  <-- specific to app2
.eslintrc
- app3/
webpackConfig.js <-- specific to app3
.eslintrc
webpack.config.js <-- common configuration
```
A custom webpack configuration looks like so:
__apps/app1/webpackConfig.js__
```JS
export function (baseConfig) => {
newConfig = baseConfig
// Some custom manipulation
....
return newConfig
}
```
**Note that the common webpack configuration is responsible for determining which …

add-missing-env-variable-in-webpack-config

---

docs/rules/extensions.md

Hi there! We just started using the `import/extensions` rule from this plugin and ran into a problem caused by not understanding the options the rule accepted. I have added a couple more examples to the docs to make the 3 forms of the rule clearer.
Please let me know if you need me to run a changeset command or adhere to a commit message convention. Thanks!

adds more examples to the import/extensions rule docs

---

docs/rules/extensions.md

Fixes weird red highlighting on docs.
Before: 
After:

[Docs] fixes problem with weird highlighting

---

docs/rules/first.md
src/rules/first.js
tests/src/rules/first.js

Add autofixer for rule `first`. Refer issue #1040.

add fixer for `first`

---

docs/rules/no-commonjs.md
src/rules/no-commonjs.js
tests/src/rules/no-commonjs.js

Add `allow-require` option to `no-commonjs` rule

---

docs/rules/no-cycle.md

In the  [`import/no-cycle`](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-cycle.md#maxdepth) docs, there's an example for using options. 
this is the current text: 
```js
/*eslint import/no-unresolved: [2, { maxDepth: 1 }]*/
```
this PR updates it to: 
```js
/*eslint import/no-cycle: [2, { maxDepth: 1 }]*/
```

minor typo in import/no-cycle rule docs

---

package.json
src/core/importType.js

`resolve` has a much more thorough list of builtins, and since I maintain it, we can keep it updated more easily than with `builtin-modules`.

[patch] use `resolve` instead of `builtin-modules`

---

CHANGELOG.md
README.md
docs/rules/no-useless-path-segments.md

Adds no-useless-path-segments documentation.

---

README.md
docs/rules/dynamic-import-chunkname.md
src/index.js
src/rules/dynamic-import-chunkname.js
tests/src/rules/dynamic-import-chunkname.js

This PR adds a new rule `dynamic-import-chunkname,` which reports on any dynamic-import usages without a properly formatted webpackChunkName leading comment as mentioned in [this tweet](https://twitter.com/lencioni/status/973957708968706050).
This is a useful rule to have, since explicitly defining the webpackChunkName will provide a consistent file name for the code split boundary.
cc @lencioni @ljharb

Dynamic import chunkname rule

---

CHANGELOG.md
README.md
docs/rules/first.md
docs/rules/no-commonjs.md
docs/rules/no-cycle.md
package.json
src/ExportMap.js
src/core/importType.js
src/rules/first.js
src/rules/no-commonjs.js
src/rules/no-cycle.js
tests/src/rules/first.js
tests/src/rules/no-commonjs.js

Release 2.11.0

---

CHANGELOG.md
docs/rules/named.md
src/rules/named.js
tests/src/rules/named.js

This fixes #931 for the named rule. This was done to play nice with flow-typed in the following situation:
```js
/*
* Import an NPM module and grab the type definition from flow-typed
*/
import Something from 'my-npm-package';
// This type isn’t actually in the npm package but in the flow-typed directory, so eslint-import cannot resolve it.
import type { SomethingType } from 'my-npm-package';
```
Closes #1060.

Ignore type imports for named rule.

---

README.md
docs/rules/no-extraneous-dependencies.md
package.json
src/rules/no-extraneous-dependencies.js
tests/files/monorepo/package.json
tests/files/monorepo/packages/nested-package/package.json
tests/files/node_modules/left-pad
tests/files/node_modules/react
tests/src/rules/no-extraneous-dependencies.js

Continuation of @hulkish's work on #1016, but removes `import/paths` setting and instead supports both a single string or an array of string paths for the existing `packageDir` option.
Closes #1016.
Closes #1053.
Closes #935.
Closes #458.

no-extraneous-dependencies: multiple packageDir(s)

---

resolvers/webpack/index.js

is not the root cause of #767, but it at least makes it possible for folks to figure out real fast what is causing the error (use log because eslint swallows thrown errors)
fix #767

log a useful error in a module bug arises

---

src/rules/named.js
tests/files/flowtypes.js
tests/src/rules/named.js

#1057 has fixed #921 for the basic case, in which an import is the only thing imported from a specific file.
Sometimes types and functions/classes need to be imported from the same file. This PR fixes also that specific instance:
```
import  { type MyOpaqueType, MyClass } from "./flowtypes"',
```
I have added some tests for all these cases
Fixes #1115.

Fixed flow types imports

---

src/rules/no-relative-parent-imports.js
tests/src/rules/no-relative-parent-imports.js

This changes the rule to resolve paths before emitting an error. While this means the error will trigger less often (before we could report an error even if the file didn't exist on disk yet) I think it's a fine tradeoff so that it can be useful in more situations.
Fixes #1123.

[no-relative-parent-imports] Resolve paths

---

src/rules/order.js
tests/src/rules/order.js

Addresses https://github.com/benmosher/eslint-plugin-import/issues/1086#issuecomment-383093638
When using `typescript-eslint-parser`, AST nodes have a `range` trie but not `start` and `end`. Apparently `eslint` prefers using `range` instead of `.start` and `.end` as well, see https://github.com/eslint/eslint/issues/8956.
Replace use of `.start` and `.end` with `range[0]` and `range[1]` respectively in the `order` rule.
I added a test to reproduce the error and then a separate commit to prove this fixes it. All other tests pass.

Fix import/order autofixer when using typescript-eslint-parser

---

src/rules/no-useless-path-segments.js
tests/src/rules/no-useless-path-segments.js

make rule `no-useless-path-segments` work with commonjs

---

src/rules/namespace.js
tests/src/rules/namespace.js

Add JSX check to namespace rule

---

docs/rules/dynamic-import-chunkname.md
src/rules/dynamic-import-chunkname.js
tests/src/rules/dynamic-import-chunkname.js

As briefly discussed in #1130, current webpack comment parsing logic (without taking styling into account) is severely flawed, reporting valid comments as errors while also allowing invalid syntax.
This PR adds
* checking for valid syntax the way webpack itself parses these comments
* support for multiple keys in these comments, both in a single comment and in several comments (see examples in docs or tests)
Styling requirements have not been relaxed by these changes.
The main topic of #1130 - allowing single quotes in strings in webpack comments - will be implemented on top of these changes once they are merged.

fix(dynamic-import-chunkname): Add proper webpack comment parsing

---

src/core/importType.js

make rule `no-relative-parent-imports` support windows
as you see, appveyor ci failed in master branch, i think because windows uses `\` as a directory delimiter
so i change path check to use regular expression `[\\/]`

[no-relative-parent-imports] support windows

---

CHANGELOG.md
src/rules/no-extraneous-dependencies.js
tests/files/monorepo/package.json
tests/src/rules/no-extraneous-dependencies.js

Fix packageDir array support

---

resolvers/webpack/CHANGELOG.md
resolvers/webpack/index.js
resolvers/webpack/test/config.js
resolvers/webpack/test/files/webpack.function.config.multiple.js

PR for #1219 
+ aded test for the case

Webpack Resolver fix for case config is an array of functions

---

src/ExportMap.js
tests/files/named-exports.js
tests/src/core/getExports.js
tests/src/rules/named.js

This PR fixes #718.
The fix is simple, just recognize the `AssignmentPattern` and put the name into the exports map.

[import/named] fix destructuring assignemnt

---

resolvers/webpack/index.js
resolvers/webpack/test/config.js
resolvers/webpack/test/files/webpack.function.config.js

Some people may rely on the map of options passed to webpack (as I do), thus it would be nice to be able to provide this second parameter instead of just an empty object.

Added support for argv parameter of webpack`s config-as-a-function

---

CHANGELOG.md
docs/rules/no-deprecated.md
src/ExportMap.js

Leak was caused by V8 unnecessarily retaining the `SourceCode` object used to parse comments for `@deprecated` tags. It has no reason to stick around.
Also I have been using `no-deprecated` for years and it has been very helpful, so I removed the "Stage 0" warning.
Will merge and release once CI passes.

fix memory leak (#1266)

---

tests/src/core/importType.js
tests/src/rules/export.js
tests/src/rules/extensions.js
tests/src/rules/named.js
tests/src/rules/no-default-export.js
tests/src/rules/no-named-export.js
tests/src/rules/no-unresolved.js
tests/src/rules/prefer-default-export.js
tests/src/utils.js

@ljharb I went took a look at the tests that were failing. seemed like all but one of them existed because there were exports for things that didn't exist, i.e. `export { bar}`, when `bar` isn't defined. 
There is one test currently failing. However, after reading it, I think it should be deleted because what it says isn't true. The test reads: `should return 'internal' for module from 'node_modules' if 'node_modules' missed in 'external-module-folders'. However, the check for isExternalPath checks whether or not the `path` argument is falsy. If it is falsy, or if it is found in the import/external-module-folders, then it returns true. In the case of that test, the path is undefined (because that file doesn't exist), and therefore the test is failing.

fix a bunch of tests that were failing

---

CHANGELOG.md
package.json
src/core/importType.js
tests/files/@importType/index.js
tests/files/order-redirect-scoped/module/package.json
tests/files/order-redirect-scoped/package.json
tests/files/order-redirect/module/package.json
tests/files/order-redirect/package.json
tests/src/core/importType.js

Checklist:
Fixes #793
It was fixed by making `isExternalPath` search for  `<module_dir>/<package_name>` (e.g. `node_modules/redux-saga`) instead of `<module_dir>/<package_name>/<file_name>` (e.g. `node_modules/redux-saga/effects`) in the resolved path.
I'd argue that the new solution is still not optimal, as it will fail if an external module has a `main` field which links to another external module.
Should we instead just check that the beginning of the resolved path is the resolved path for the external module folder ? I can make a PR with that alternate solution if requested.
You also might want to check the way I implemented the tests as they might not be an optimal solution.
Edit: The build is failing but was already failing before I started writing code, should I be worried about …

Fix interpreting some external modules being interpreted as internal modules

---

src/core/importType.js
tests/src/core/importType.js

@ljharb as we talked about in the issue, here is the fix. Please let me know if there are any issues. Or if you think we need more tests for this case. I added one. There were already a ton that didn't pass and didn't think I should fix them in this PR.
Fixes #1293. Unblocked by #1295.

closes #1293. allows aliases that start with @ to be caught as internal

---

README.md
docs/rules/no-useless-path-segments.md
src/rules/no-useless-path-segments.js
tests/src/core/ignore.js
tests/src/rules/no-useless-path-segments.js
utils/ignore.js

As discussed in #394, this PR adds an option `noUselessIndex` to detect (and fix) paths containing unnecessary `index` parts (with or without file extension):
Given the following file structure:
```
my-project
├── foo.js
└── foo
└── index.js
└── bar
└── index.js
```
Before:
```
import 'foo/index' // No warning
import 'bar/index' // No warning
```
After:
```
import './foo/index.js' // Warning (fixable to `./foo/`)
import './foo/index' // Warning (fixable to `./foo/`)
import './bar/index' // Warning (fixable to `./bar`)
```
I've replaced the `sumBy` function with `reduce` to get rid of Lodash (not necessary in this case IMO). A benchmark which compares these 2 alternatives shows no difference between them or a slight advantage for `reduce`: …

No useless index in import paths

---

CHANGELOG.md
docs/rules/no-duplicates.md
src/rules/no-duplicates.js
tests/src/rules/no-duplicates.js

This adds autofix to `no-duplicates`. The autofix merges duplicate imports into the first one. It bails if there are multiple default import names, or comments associated with the (non-first) duplicate imports (since it's unclear how the user wants to move them).

no-duplicates: Add autofix

---

README.md
package.json
src/ExportMap.js
tests/dep-time-travel.sh
tests/src/core/getExports.js
tests/src/rules/named.js
tests/src/rules/order.js
tests/src/utils.js

Adds support so that `export type` named imports work with this plugin.
Resolves #1282

support export type named exports from typescript

---

resolvers/webpack/index.js
src/core/importType.js
tests/files/constants/index.js
tests/src/core/importType.js

Update `isBuiltIn` to return `false` if a path is returned from a resolver. 
Previously an alias like 'constants/foo' would be classified as a builtin rather than internal since 'constants' is a core module of node. Fixes one of the issues mentioned in #1034.
Update webpack resolver to attempt to resolve modules internally before classifying them as builtin.
Add several tests to cover these cases.
```
project
└── src
└── constants
└── index.js
```
```json
{
"settings": {
"import/resolver": {
"node": {
"paths": ["/project/src"]
}
}
}
}
```
Result:
```js
// BEFORE
import { FOO } from 'constants/index'
import { isObject } from 'lodash'
// AFTER
import { isObject } from 'lodash'
import { FOO } from 'constants/index'
```

fix: aliased internal modules that look like core modules

---

src/rules/namespace.js
tests/files/re-export-common.js
tests/src/rules/namespace.js

This PR fixes #1144 .
The issue happens when the dependency has `null` `ExportMap`, which happens for ignored or ambiguous modules.
This PR adds a check before doing more verification on the `ExportMap`.
Test is added following the issue.

[Namespace] add check for null ExportMap

---

src/ExportMap.js
tests/src/core/getExports.js

This PR fixes #1233 .
Before the code uses `\n` as line ending to check if the comment is block comment. This PR changes to use `comment.type` which is more reliable.
https://github.com/benmosher/eslint-plugin-import/blob/798eed7e559adab2eac07bf1b3e3518d4b7a4296/src/ExportMap.js#L233
Tests are added for both `\n` and `\r\n`

[ExportMap] fix condition for checking if block comment

---

src/rules/no-cycle.js
tests/src/rules/no-cycle.js
tests/src/rules/no-relative-parent-imports.js
tests/src/rules/no-unresolved.js
tests/src/rules/no-useless-path-segments.js
utils/moduleVisitor.js

Closes #1035
Closes #1166
So turns out, dynamic imports were already supported in `moduleVisitor` but they were being overwritten if `commonjs` or `amd` options were set.
- Fixed by saving the current `CallExpression` and including it in the function that's overwriting it.
- Added test cases for `import()` in rules using the `moduleVisitor`. Not sure why, but I couldn't get the `no-cycle` rule to throw errors with `import()`.
- Fixes issues with parser `babel-eslint` not working with `no-cycle`, due to the "flow workaround" for `eslint@<5`
This might be breaking for some users, though.
Also since `import()` can work with URLs, maybe we should use something like [`isURL` from `validator`](https://github.com/chriso/validator.js#validators) to ignore URL imports?

Fix overwriting of dynamic import() CallExpression

---

package.json
src/rules/export.js
tests/src/rules/export.js
tests/src/utils.js

fix: false positives for typescript type + value export

---

docs/rules/no-default-export.md
docs/rules/no-deprecated.md
docs/rules/no-named-export.md
docs/rules/no-relative-parent-imports.md
docs/rules/no-self-import.md

Renamed the title of this page to be the full name of the rule, like on the rest of the docs.

doc(no-relative-parent-imports): rename title

---

src/rules/export.js
tests/src/rules/export.js

Fixes #1300
- Added nested export scope support
- Fixed broken test on ESLint v3 caused by old typescript parser

fix(export): Support typescript namespaces

---

package.json
src/rules/no-unused-modules.js
tests/src/rules/no-unused-modules.js

Currently rule is failing in console, if no options are provided, but none of them is required, as `src` has preset fallback for it, other params are optional (even though without setting `missingExports` or `unusedExports`, to true this rule is not really used).

no-unused-modules: make sure that rule with no options will not fail 

---

src/rules/no-unused-modules.js
tests/src/rules/no-unused-modules.js

[fix] `no-unused-modules`: make `import { name as otherName }` work

---

CHANGELOG.md
docs/rules/named.md
src/rules/named.js
tests/src/rules/named.js

Expand the cases added by #1057 and #1106 to handle the other forms of Flow import/export.

[fix] `named`: ignore Flow import typeof and export type

---

src/rules/no-unused-modules.js
tests/src/rules/no-unused-modules.js

[fix] `no-unused-modules`: don't crash when lint file outside src-folder

---

src/rules/no-commonjs.js
tests/src/rules/no-commonjs.js

`var x = require("x")` will throw an error, but `var x; x = require("x")` does not.

Fix apparent corner case with `import/no-commonjs` rule

---

README.md
docs/rules/no-unused-modules.md

Indicates usage, and that plugin defaults to no-op

---

resolvers/webpack/README.md

Minor PR to address issue #1258
Explains that a config expecting environment variables can be used by providing `env`
Fixes #1258

Issue #1258: Document `env` option for `eslint-import-resolver-webpack`

---

src/ExportMap.js
tests/files/typescript-declare.d.ts
tests/files/typescript-export-assign.d.ts
tests/src/rules/named.js
utils/unambiguous.js

This change improves support various forms used in Typescript declaration files. It's often necessary to change import resolution to prefer '.d.ts' files over '.js' files, but doing so breaks existing import resolution for certain types of UMD modules (React, for example).
This patch has two improvements:
* It adds support for the `export declare function foo()` syntax, which wasn't previously recognized
* It adds support for the `export = Namespace` syntax for exporting everything in a namespace.
The `import/named` tests were updated to add both variations as additional test files.

Improve support for Typescript declare structures

---

docs/rules/no-cycle.md

Making it more obvious that the code examples are individual files.

Docs: no cycle, split code examples so file separation is obvious

---

src/rules/order.js
tests/src/rules/order.js

[New] `order`: add fixer for destructuring commonjs import

---

CHANGELOG.md
docs/rules/order.md
src/rules/order.js
tests/src/rules/order.js

We figured out that the auto-fix feature of the "order" rule destroyed our custom imports which are using a custom `babel-module` resolver. Settings for the resolver:
```js
'import/resolver': {
'babel-module': {
extensions: ['.js', '.jsx', '.ts', '.tsx', '.json'],
alias: {
'-': './src/',
},
},
},
```
Until now, unknown import types were sorted problematically by the "order" feature. These were not assigned to a common group but loosely added or kept between the other imports. This was especially problematic when using the 'newlines-between'-feature. In this case there was an additional line feed after each unknown import. See examples below.
Example:
```js
import { get } from 'lodash'
import { FormError } from '-/components/Product/Configuration/FormError'
import React, { PureComponent } …
```

Added support for correctly ordering unknown types e.g. custom aliases

---

.travis.yml
package.json
src/rules/no-unused-modules.js
tests/src/core/getExports.js
tests/src/core/parse.js
tests/src/rules/default.js
tests/src/rules/dynamic-import-chunkname.js
tests/src/rules/export.js
tests/src/rules/max-dependencies.js
tests/src/rules/named.js
tests/src/rules/namespace.js
tests/src/rules/newline-after-import.js
tests/src/rules/no-amd.js
tests/src/rules/no-commonjs.js
tests/src/rules/no-cycle.js
tests/src/rules/no-default-export.js
tests/src/rules/no-duplicates.js
tests/src/rules/no-extraneous-dependencies.js
tests/src/rules/no-mutable-exports.js
tests/src/rules/no-named-as-default.js
tests/src/rules/no-named-default.js
tests/src/rules/no-named-export.js
tests/src/rules/no-namespace.js
tests/src/rules/no-relative-parent-imports.js
tests/src/rules/no-unresolved.js
tests/src/rules/no-useless-path-segments.js
tests/src/rules/order.js
tests/src/rules/prefer-default-export.js
tests/src/rules/unambiguous.js
tests/src/utils.js

The main issues are:
To test:
```
npm i eslint@6
npm test
```
The only failing tests should be related to the TypeScript issue above.
Related to https://github.com/airbnb/javascript/issues/2036.
Fixes #1362.

Support ESLint v6

---

package.json
src/core/importType.js
src/rules/no-extraneous-dependencies.js
tests/dep-time-travel.sh
tests/src/rules/no-amd.js
tests/src/rules/no-commonjs.js

This removes a large dep that often has CVEs, in exchange for using native JS which is clearer and more maintainable.
Closes #1224.

[Refactor] use native JS instead of lodash

---

src/rules/export.js
tests/src/rules/export.js

Fixes #1357.
Fixes false positives like this: 
```ts
export function foo(a: number) {}
export function foo(a: string) {}
```

[fix] `export`: false positive for typescript overloads

---

docs/rules/no-unused-modules.md
package.json
src/rules/no-unused-modules.js
tests/files/no-unused-modules/bin.js
tests/files/no-unused-modules/binObject/index.js
tests/files/no-unused-modules/binObject/package.json
tests/files/no-unused-modules/browser.js
tests/files/no-unused-modules/browserObject/index.js
tests/files/no-unused-modules/browserObject/package.json
tests/files/no-unused-modules/main/index.js
tests/files/no-unused-modules/package.json
tests/files/no-unused-modules/privatePkg/index.js
tests/files/no-unused-modules/privatePkg/package.json
tests/src/rules/no-unused-modules.js

Implements a solution for #1327

Exclude pkg main files from `no-unused-modules`

---

src/rules/prefer-default-export.js
tests/src/rules/export.js
tests/src/rules/named.js
tests/src/rules/no-deprecated.js
tests/src/rules/order.js
tests/src/rules/prefer-default-export.js
tests/src/utils.js

Attempt at fixing #1332 
Skips warning on a single type declaration or type alias. ~Remove the check for `node.exportKind` as it is `undefined` in all test cases.~ I believe this is used in eslint v2 & 3
This should work with `@typescript-eslint/parser` too, but I'm not testing that here because this repo is still using `typescript-eslint-parser`.
cc. @ljharb

[bugfix] Re: #1332 - skip warning on a type declaration or alias. 

---

utils/parse.js

Fixes #1408
See the above issue for justification.

fix: Improve parse perf when using `@typescript-eslint/parser`

---

src/rules/prefer-default-export.js
tests/src/rules/prefer-default-export.js

Similar to https://github.com/benmosher/eslint-plugin-import/pull/1377,
we don't want this rule to apply to exported interfaces.

[bugfix] Skip warning on type interfaces

---

CHANGELOG.md
tests/src/core/eslintParser.js
tests/src/core/parse.js
utils/parse.js

feat: support `parseForESLint` from custom parser

---

CHANGELOG.md
src/rules/default.js
tests/src/rules/default.js

[feat] `default`: make message less confusing

---

CHANGELOG.md
docs/rules/group-exports.md
package.json
src/rules/group-exports.js
tests/src/rules/group-exports.js

Make aggregating modules valid in group-exports

---

CHANGELOG.md
docs/rules/no-extraneous-dependencies.md
src/rules/no-extraneous-dependencies.js
tests/files/bundled-dependencies/as-array-bundle-deps/package.json
tests/files/bundled-dependencies/as-object/package.json
tests/files/bundled-dependencies/race-condition/package.json
tests/files/package.json
tests/src/rules/no-extraneous-dependencies.js

Add support for bundledDependencies

---

CHANGELOG.md
README.md
docs/rules/no-namespace.md
src/rules/no-namespace.js
tests/src/rules/no-namespace.js

This PR adds support for `--fix` to the `no-namespace` rule, in the case where all references to the namespace can be statically resolved:
```js
import * as foo from 'foo';
florp(foo.bar);
florp(foo.baz);
```
```js
import { bar, baz } from 'foo';
florp(bar);
florp(baz);
```
The motivation for this is to make it easier to opt in to `no-namespace` in codebases that are already using this pattern. It sure beats having to do it all by hand! 😄 
Note that this will only work under ESLint 5+, as older versions don't allow for traversing upward from variable references. That is, in this code `identifier.parent` is `undefined`. I haven't been able to figure out a good way to support this under ESLint 4 (let me know if you have any ideas!), so I've added a note for this in the rule's documentation.

 Make no-namespace rule fixable

---

CHANGELOG.md
src/ExportMap.js
tests/files/typescript-export-assign-merged.d.ts
tests/src/rules/named.js

Fixes a bug where not all of the declarations from multiple `declare namespace` copies would be merged together when the namespace was assigned as the export. I couldn't see any issue reported for this bug already.

Fix ExportMap for a merged typescript namespace

---

.travis.yml
CHANGELOG.md
README.md
src/rules/export.js
tests/dep-time-travel.sh
tests/src/rules/export.js
tests/src/rules/named.js
tests/src/rules/no-deprecated.js
tests/src/rules/prefer-default-export.js
utils/CHANGELOG.md

Changes “Typescript” and “typescript” to “TypeScript”.

Fix spelling of “TypeScript”

---

src/rules/prefer-default-export.js
tests/src/rules/prefer-default-export.js

[Fix] false positive for prefer-default-export with type export

---

src/rules/no-extraneous-dependencies.js
tests/src/core/getExports.js
tests/src/core/resolve.js
tests/src/rules/no-duplicates.js
tests/src/rules/no-unresolved.js

It appears recent changes to `comma-dangle` (https://github.com/eslint/eslint/pull/12462) with ESLint v6 have started to make recent PR's in this repo fail:
- 🔴 http://travis-ci.org/benmosher/eslint-plugin-import/jobs/603696351 (#1519)
- ✅ https://travis-ci.org/benmosher/eslint-plugin-import/jobs/603703318 (this PR)
This PR runs `eslint --fix .` to resolve the errors.

Fix eslint comma-dangle violations

---

CHANGELOG.md
src/ExportMap.js

I was debugging a project trying to understand better how the `import/no-deprecated` rule works. While doing this I discovered that `ExportMap.for` will do a I/O hit to read the `path` _even_ if the `path` is ignored:
https://github.com/benmosher/eslint-plugin-import/blob/112a0bf442e52b25cd7029a9905df2508e191ac1/src/ExportMap.js#L313-L320
When the `path` is ignored, the function early exits and the `content` variable is not referenced, so it's essentially a wasted I/O hit.
This PR tweaks the condition to do the ignore check in one block, and check ambiguity in another.  
In theory this should result in a performance boost for projects that ignore many paths as they will be skipped based off the ignore, rather than being loaded from the file system. It also cleans up the log a little bit …

When populating ExportMap, only load file if it's not ignored

---

CHANGELOG.md
src/rules/extensions.js
tests/src/rules/extensions.js

Closes #1518 
@ljharb By "never" I mean literally never, even the test produced zero error before fixing `buildProperties()`. (I found this in https://github.com/w3c/respec/pull/2555)

Fix ignorePackages to produce errors

---

CHANGELOG.md
docs/rules/no-useless-path-segments.md

[Docs] `no-useless-path-segments`: add docs for option `commonjs`

---

CHANGELOG.md
README.md
docs/rules/order.md
src/core/importType.js
tests/src/core/importType.js

fixes #1125
We are developing packages in a monorepo and packages depend on each other so we need to separate our package from external dependency. We used to [tslint/ordered-imports](https://palantir.github.io/tslint/rules/ordered-imports/) which allow custom group by regex pattern.
This PR added a new setting which allowed user to provide a regex pattern and packages that match that pattern will be marked internal.

[core]: regex marking packages as internal

---

CHANGELOG.md
src/rules/no-unused-modules.js
src/rules/order.js
utils/CHANGELOG.md
utils/resolve.js

LGTM.com often identifies some issues not found by ESLint; this PR fixes the issues found at https://lgtm.com/projects/g/benmosher/eslint-plugin-import/?mode=list . In this case, they are just some harmless superfluous arguments and redundant checks, but helpful to fix both for clarity and to reduce noise among the lgtm alerts.
(The site has a [Github integration](https://lgtm.com/help/lgtm/github-apps-integration) which I find worth adding to check PRs.)

[Refactor] Avoid superfluous calls and code

---

CHANGELOG.md
src/rules/no-unused-modules.js
tests/files/no-unused-modules/flow-0.js
tests/files/no-unused-modules/flow-1.js
tests/files/no-unused-modules/flow-2.js
tests/src/rules/no-unused-modules.js

Adds support for reporting flow type exports. Fixes #1540

[flow] `no-unused-modules`: add flow type support

---

CHANGELOG.md
src/rules/no-unused-modules.js
tests/files/no-unused-modules/cjs.js
tests/files/no-unused-modules/filte-r.js
tests/src/rules/no-unused-modules.js

fix #1382 
After investigating, It comes from this line
https://github.com/benmosher/eslint-plugin-import/blob/5e143b23f3b89096e1b6a268af723f60c1ecb22f/src/ExportMap.js#L316
In my case, `export * from 'redux-starter-kit'` is not detected as unambigous and it `return null` which crash no-unused-modules
I didn't find any good way to test it. I'm looking forward for some advices on how I can test this issue :)

Fix crash due to export * with no-unused-modules

---

CHANGELOG.md
src/ExportMap.js
tests/files/cycles/flow-types-depth-one.js
tests/files/cycles/flow-types-depth-two.js
tests/files/cycles/flow-types.js
tests/src/rules/no-cycle.js

The changes fix a complex circular dependency where Flow type imports are transient dependencies of the checked module. Basically such imports can be ignored too since they will be stripped anyway
Fixes #1343

fix: import/no-cycle triggering errors for Flow imports

---

CHANGELOG.md
src/rules/no-extraneous-dependencies.js
tests/src/rules/no-extraneous-dependencies.js

Fixes #1049, since this one ended up biting me today!

[fix] #1049: Add support for export-from to no-extraneous-dependencies

---

CHANGELOG.md
docs/rules/order.md
src/rules/order.js
tests/src/rules/order.js

Well there are multiple issues and pull requests open regarding the ordering of groups by paths.
Because I saw that the proposed approach in https://github.com/benmosher/eslint-plugin-import/issues/795 was "accepted" I implemented it this way.
But if @ljharb has changed his mind in the mean time and would prefer something like custom groups as proposed in https://github.com/benmosher/eslint-plugin-import/issues/1015#issuecomment-388573720 I can also rework this.

`order` rule: add pathGroups option to add support to order by paths

---

CHANGELOG.md
src/core/importType.js
tests/src/core/importType.js

Hi !
Fix #1379 
The bug was related to the `internal` regex which didn't accept a module with only one word.
This is the case in Typescript when you use the tconfig `paths` to accept the import of `@myModule` in replacement of `/src/someFolder/myModule`.
Thanks for developing this library!

fix(importType): Accept '@example' as internal

---

resolvers/webpack/CHANGELOG.md
resolvers/webpack/index.js
resolvers/webpack/test/example.js
resolvers/webpack/test/root.js

This enables users to change the lookup of the webpack module
for the resolve functionality should it not be in the user's
local node_modules. This pertains to the case of a CLI where the
CLI may be in charge of webpack, and the user's repo doesn't have it.
Related to https://github.com/benmosher/eslint-plugin-import/issues/1502

feat: enable passing cwd as an option to webpack resolve

---

CHANGELOG.md
docs/rules/no-commonjs.md
src/rules/no-commonjs.js
tests/src/rules/no-commonjs.js

Fixes #1437
Currently:
1. `if (typeof window !== "undefined") require("x")` is reported by default
1. `if (typeof window !== "undefined") { require("x") }` is never reported (scope)
1. `typeof window !== "undefined" && require("x")` is never reported (conditional require)
After this PR, all cases will be treated the same (as conditional requires). A follow up PR will add an option for users to configure whether conditional requires should be reported.

[no-commonjs] add allowConditionalRequire option

---

src/rules/order.js
tests/src/rules/order.js

Hello!
I tested the new `alphabetize` rule, and when used with `newlines-between: "always"`, the plugin mark as invalid any lines which have not newline around.
For example : 
```
import Constants from '@constants';
import Logger from '@server/tools/logger';
```
These lines are OK with this plugin configuration (1) : 
```
'import/order': [
'error',
{
groups: [['builtin', 'external'], 'internal', 'parent', 'sibling'],
'newlines-between': 'always',
},
],
```
but are invalid with this plugin configuration (2) : 
```
'import/order': [
'error',
{
alphabetize: { order: 'asc' },
groups: [['builtin', 'external'], 'internal', 'parent', 'sibling'],
'newlines-between': 'always',
},
],
```
And the configuration (2) mark these lines as valid : 
```
import Constants from '@constants';
import Logger …
```

[import/order] Fix alphabetize bug with newlines-between

---

CHANGELOG.md
src/core/importType.js
src/rules/extensions.js
tests/src/rules/extensions.js

[Fix] import/extensions: ignore non-main modules

---

CHANGELOG.md
src/rules/no-unused-modules.js
tests/files/no-unused-modules/jsx/file-jsx-a.jsx
tests/files/no-unused-modules/jsx/file-jsx-b.jsx
tests/files/no-unused-modules/typescript/file-ts-a.ts
tests/files/no-unused-modules/typescript/file-ts-b.ts
tests/src/rules/no-unused-modules.js

[Fix] `no-unused-modules`: fix usage of `import/extensions` settings

---

CHANGELOG.md
docs/rules/order.md
src/rules/order.js
tests/src/rules/order.js

Enhancement alphabetize case insensitive

---

CHANGELOG.md
docs/rules/no-restricted-paths.md
src/rules/no-restricted-paths.js
tests/src/rules/no-restricted-paths.js

Closes #834
Allow exceptions to be defined for restricted path zones.

[no-restricted-paths] Allow exceptions to zones

---

CHANGELOG.md
config/typescript.js
tests/src/config/typescript.js

When using TypeScript an external module can be resolved to its type definition file located in `node_modules/@types` from `eslint-import-resolver-typescript@2.0.0`. At the moment, that module would be marked as "internal" because the module is not found directly inside `node_modules`, but instead nested inside `@types`.
This PR just adds the `node_modules/@types` folder to lookup for external modules when using the TypeScript config.
Fixes #1525. Fixes #1541.

[Typescript] Lookup for external modules in @types folder.

---

CHANGELOG.md
src/rules/extensions.js
tests/src/rules/extensions.js

[extensions] Ignore query strings when checking for extensions.

---

CHANGELOG.md
docs/rules/order.md
src/rules/order.js
tests/src/rules/order.js

… ordering of external import types
To fix the issue https://github.com/benmosher/eslint-plugin-import/issues/1565 and have no BC break I added a new option to also allow sorting of external imports.
Fixes #1565.

[New] `order`: add option pathGroupsExcludedImportTypes to allow ordering of external import types

---

tests/files/node_modules/eslint-import-resolver-foo/index.js
tests/src/core/resolve.js
tests/src/rules/no-unresolved.js
utils/CHANGELOG.md
utils/resolve.js

The current logic uses `require.resolve` in order to locate the resolver modules. The problem is that `require.resolve` semantically operates based on the currently evaluated module. That makes the resolution incorrect, as the loaders aren't dependencies of `eslint-module-utils`. It probably works thanks to the hoisting, but hoisting is on its way out and such problems will start to reveal themselves.
To fix that, the resolution simply needs to use `createRequireFromPath` so that the loaders are located based on the dependencies of the package that contains the source file being linted - which I think was the intent.

utils: Uses createRequireFromPath to resolve loaders

---

CHANGELOG.md
docs/rules/extensions.md

I was curious of how this rule worked, so I went the easiest way and wrote a bunch of unit tests for the buildProperties (a method that returns the options from the config for the extensions rule) method.

[extensions] Better document. Add unit tests. (#1248)

---

tests/files/load-error-resolver.js
tests/src/core/resolve.js
utils/CHANGELOG.md
utils/resolve.js

Resolve errors are most likely caused by invalid configuration, and the reason is easier to determine with the full details rather than just `err.message`.
See https://github.com/benmosher/eslint-plugin-import/issues/536
With this change, it reports something like:
```
import/no-unresolved: Resolve error: SyntaxError: Unexpected token import
at exports.runInThisContext (vm.js:53:16)
at Module._compile (module.js:387:25)
at Object.Module._extensions..js (module.js:422:10)
at Module.load (module.js:357:32)
at Function.Module._load (module.js:314:12)
at Module.require (module.js:367:17)
at require (internal/module.js:16:19)
at module.exports (/__censored__/webpack/configFactory.js:216:3)
at configProdClient (/__censored__/webpack/configProdClient.js:5:36)
at Object.<anonymous> …
```

utils: [Fix] report the error stack on a resolution error

---

src/core/importType.js
src/rules/extensions.js
tests/src/rules/extensions.js

When checking for extensions we got a bunch of error dues to the linter checking the name of packages like ‘import Decimal from “decimal.js”’ because we are using ‘never’. The opposite is true too, as seen in #414, when using ‘always’ will trigger linting is you do ‘import query form “query”’.
So what this does is change the ‘checkExtension’ method to check if a file is an external module and if it is then check if its a root one, in which case it is ignored. In that ticket there was a conversation about adding different options but I actually think that this behaviour makes more sense. Naming of packages is a bit weird and will always be so its probably safer just ignore them completely in this case.
A ton of things may be wrong as I’m not familiar with eslint and there may be a better …

Ignore root external modules when checking for extensions

---

utils/CHANGELOG.md
utils/resolve.js

In order to avoid: `DeprecationWarning: Module.createRequireFromPath() is deprecated. Use Module.createRequire() instead.` when using Node >= `v12.2.0`.

Use createRequire instead of createRequireFromPath if available

---

utils/CHANGELOG.md
utils/resolve.js

(Sorry @iamnapo, it was very late at night and I initially opened this PR against your repo ... 😅)
Assuming that the repro provided by https://github.com/benmosher/eslint-plugin-import/issues/1604#issuecomment-573364743 will be valid, a simple solution would be to be too laxist for now and just fallback to the hoisting resolution if the file-relative one doesn't find the loader - while still using the expected resolution as primary code path.
And then the next time eslint-import-utils receives a major bump, revert the try/catch block and go back to using exclusively createRequire.
cc @ljharb, fixes #1604, fixes #1603

Makes the loader resolution more tolerant

---

CHANGELOG.md

I found duplicated `Added` sections in CHANGELOG for the latest release.
This pull request will merge them into one.
By the way, I also found a missing link in the CHANGELOG.
It is the second line of "Fixed" section, "[`import/extensions`]: ignore non-main modules".
`import/extensions` does not link to anywhere.
But I'm not sure it should be "`import/extensions` setting" or `extensions`.
I'll fix the link in this pull request if you tell the right link and you'd like. Or feel free handling it yourself.
Thanks!

Merge duplicated `Added` section in CHANGELOG

---

CHANGELOG.md
README.md
package.json
src/core/importType.js
tests/files/symlinked-module/index.js
tests/files/symlinked-module/package.json
tests/src/core/importType.js
tests/src/rules/order.js

Fixes #1597.
This PR changes the logic of [`isExternalPath`] function so that it doesn't consider the import name. For a path to be external, it's now sufficient that it matches one of the items in the `import/external-module-folders` array specified in settings.
This is to support a setup where some of the modules are symlinked from `node_modules` into directories elsewhere in the project (called ["workspaces"] in Yarn terminology). For example, it's common to have a monorepo setup like this:
```
node_modules
@my-scope
core -> ../../packages/core
utils -> ../../packages/utils
packages
core
package.json
index.js
utils
package.json
index.js
package.json
```
Usually, one wants these packages to be treated as external since they're normally installed from a registry. Intuitively, this should …

Fix import type determination for monorepo setup w/ webpack resolver

---

CHANGELOG.md
src/core/importType.js
tests/src/rules/extensions.js

Fix scope regex

---

CHANGELOG.md
src/rules/no-duplicates.js
tests/src/rules/no-duplicates.js

It is a syntax error to put both namespace and non namespace import on the same line, so allow it.
Fix issue #1538

no-duplicates: allow duplicate if one is namespace and other not

---

README.md

This updates the Tidelift language to the new enterprise language. This will make you eligible to receive a referral bonus for workable leads generated by your project!

[Docs]: Update Tidelift language to enterprise

---

CHANGELOG.md
src/ExportMap.js
tests/files/re-export-common-star.js
tests/files/re-export-node_modules.js
tests/src/rules/named.js

Fixes #1446 
Based on #1447 
When re-exporting `*` from a commonjs module, or a module in node_modules which comes through as a commonjs module, do not error since the commonjs exports cannot be evaluated. Treat with similar logic to ignored modules or directly importing from a commonjs module.
When re-exporting `*`, the module is listed in dependencies instead of `reexports`. There is similar logic for when re-exporting a named export, to check for a null from the exportCache, which I understand to mean an ignored or unparseable es5/commonjs module:
https://github.com/benmosher/eslint-plugin-import/blob/master/src/ExportMap.js#L91
There is a todo in this location, and I'm not sure if this code satisfies that todo and it can be removed or not.
Also, when logging the value of `innerMap`, I …

fix [import/named] for importing from a module which re-exports `*` from node_modules or commonjs module

---

tests/files/re-export-node_modules.js
tests/src/rules/named.js

This adds a failing test for #1446
I'm not sure how to proceed, but hopefully this helps someone diagnose the issue.

fix [import/named] for importing from a module which re-exports named exports from a node_modules module

---

CHANGELOG.md
src/rules/export.js
tests/src/rules/export.js

I'm trying to use this rule to validate `*.d.ts` files and they contain only `TSDeclareFunction` and can't contain `FunctionDeclaration`.

export: Handle function overloading in '*.d.ts'

---

CHANGELOG.md
src/rules/order.js
tests/src/rules/order.js

Fixes #1625
The ranks of require items (which are +100) were being lost due to the algorithm not using the group rank when recalculating the alphabetized ranks.
To fix this, make the alphabetized rank of the item the group rank plus the alphabetization rank.
Run new unit tests. Before the change the tests would fail. After the change the tests pass.

[Fix] `order`: Fix alphabetize for mixed requires and imports

---

CHANGELOG.md
appveyor.yml
src/core/importType.js
tests/src/core/importType.js

`isExternalModule` is not right, when use `\` as separator.
This cause external module detected as `internal`.
Seems we are not running test on windows. I add a test on `isExternalModule`

[Fix] `order`: fix `isExternalModule` detect on windows

---

appveyor.yml

This fixes the package installation and test running on Windows to expose failing tests related to #1643.
More details in the commit messages.

Fix build on Windows

---

CHANGELOG.md
src/core/importType.js
tests/src/rules/order.js

[fix] `order`: recognize ".." as a "parent" path

---

resolvers/node/CHANGELOG.md
resolvers/node/index.js
resolvers/node/test/paths.js

Fixes #802
I can't decide if this is semver-minor or breaking for the node resolver - ie, whether it'd be included in v0.3.4 or v0.4.0.

`resolvers/node`: [New] add `.node` extension

---

CHANGELOG.md
src/rules/no-duplicates.js
tests/src/rules/no-duplicates.js

fixes #1504, fixes #1403, fixes #1432.

[fix] `no-duplicates`: fix fixer on cases with default import

---

utils/CHANGELOG.md
utils/parse.js

If parsing fails, the only message printed to the console is vague and
mostly unhelpful. Print some information about the source of the error
to make debugging easy.

Print more helpful info if parsing fails

---

CHANGELOG.md
src/rules/first.js
tests/src/rules/first.js

Fixes #1661 .
Not sure if the alternative should be just an empty string or an explicit disable option. Went for the second for now.

Add a way to disable absolute-first option explicitly

---

.travis.yml
src/rules/dynamic-import-chunkname.js
tests/src/rules/exports-last.js
tests/src/rules/no-absolute-path.js
tests/src/rules/no-cycle.js
tests/src/rules/no-default-export.js
tests/src/rules/no-dynamic-require.js
tests/src/rules/no-extraneous-dependencies.js
tests/src/rules/no-named-export.js
tests/src/rules/no-nodejs-modules.js
tests/src/rules/no-self-import.js
tests/src/rules/no-unassigned-import.js
tests/src/rules/no-unused-modules.js
tests/src/rules/no-useless-path-segments.js
tests/src/rules/order.js
tests/src/rules/prefer-default-export.js

The relevant breaking changes in eslint 7 are:
1. Test cases that contains unrecognized properties are now failed.
2. Test cases that have fixed code but missing `output` are now failed.
3. The method `sourceCode.getComments` is deprecated.

Add eslint 7 to CI

---

CHANGELOG.md
docs/rules/group-exports.md
package.json
src/rules/group-exports.js
tests/src/rules/group-exports.js

Fix for [#1702].
Now `export` and `export type` statements are handled separately with the same logic.

[Fix] `group-exports`: Flow type export awareness

---

CHANGELOG.md
src/rules/order.js
tests/src/rules/order.js

Here, if `group` is `external` or `builtin` then the returned rank will be `0`:
```javascript
if ((0, _minimatch2.default)(path, pattern, patternOptions || { nocomment: true })) {
return ranks[group] + position / maxPosition;
}
```
...and then, there we would erroneously throw it away, as if `0` was not a valid rank (which isn't true):
```javascript
if (!rank) {
rank = ranks.groups[impType];
}
```
Making the comparison more strict fixes the bug:
```javascript
if (rank === undefined) {
rank = ranks.groups[impType];
}
```

Bug in order.js preventing from assigning `external` to patterns using `pathGroups`

---

CHANGELOG.md
src/rules/order.js
tests/src/rules/order.js

With the config
```js
'import/order': [
'warn',
{
groups: ['builtin', 'external', 'internal', 'parent', 'sibling', 'index'],
alphabetize: {
order: 'asc',
},
pathGroups: [{ pattern: 'react', group: 'builtin' }],
pathGroupsExcludedImportTypes: ['builtin'],
},
],
```
, react wasn't being recognized as a part of the "builtin" group, since the rank would end up being `0`, which is a falsy value. The fix here, is to check for `undefined` instead.
My current workaround is to define
```
pathGroups: [{ pattern: 'react', group: 'builtin', position: 'before' }],
```
instead, (which results in a rank `-0.1`, so it's not falsy).

[Fix] `order`: Recognize pathGroup config for first group

---

CHANGELOG.md
config/typescript.js

As I was linting our projects, I noticed a few violations across them:
```ts
import { IconName } from '@fortawesome/free-solid-svg-icons';
import { GetTrackProps } from 'react-compound-slider';
import { SliderItem } from 'react-compound-slider';
import { InjectedIntl } from 'react-intl';
```
Looking around, it seems the recommendations are to either use `import type` (I haven't tried) or disabling the rule locally.
I was wondering what this rule brings when used in a TypeScript setup and realized [I am not the only one](https://github.com/typescript-eslint/typescript-eslint/issues/154#issuecomment-517037192).
Since it makes sense to disable the rule when using TypeScript, and this rule is enabled by the `recommended` preset, would it be a ridiculous idea to disable it in the `typescript` …

Disable import/named in the TypeScript configuration

---

CHANGELOG.md
src/rules/no-unused-modules.js
tests/files/no-unused-modules/import-export-1.js
tests/files/no-unused-modules/import-export-2.js
tests/src/rules/no-unused-modules.js

Closes #1722 
This PR makes sure `aa` below is correctly counted as usage:
```js
import { a } from './a';
export { aa } from './a';
```
In addition to the attached test, this fix was tested against a previous false negative in a private project which now worked.
I found the existing tests quite hard to read and understand, so I went a bit off the beaten path and tried to isolate this test in new files to avoid coupling them too much to the existing ones. I also named the files descriptively as opposed to following the existing standard of letters. This was just best effort after finally grokking what was going on, so I'm happy to take any pointers on how to improve or tweak!

Fix counting re-export as usage when used in combination with import

---

CHANGELOG.md
package.json
tests/src/rules/no-duplicates.js

Fixes #1667 
~~Don't merge yet!~~ 
This PR contains a new test for TypeScript 3.8's new `import type` syntax. However, TypeScript 3.8 is still not supported yet for TypeScript ESLint! See https://github.com/benmosher/eslint-plugin-import/issues/1667#issuecomment-594306928. 
Updates the following TypeScript packages.
```json
"@typescript-eslint/parser": "^2.22.0",
"eslint-import-resolver-typescript": "^2.0.0",
"typescript": "^3.8.3",
```
As of this TypeScript ESLint package version, it will continue to produce the following error until TypeScript ESLint gains support for TypeScript 3.8 (progress can be tracked [here](https://github.com/typescript-eslint/typescript-eslint/issues/1436)):
```
AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: A fatal parsing error occurred in autofix: Parsing …
```

[Fix] `no-duplicates`: Handle TS import type

---

CHANGELOG.md
README.md

Remove no-unused-modules from Static analysis because it is already mentioned in Helpful warnings

Remove duplicate no-unused-modules from docs

---

CHANGELOG.md
appveyor.yml
src/rules/newline-after-import.js
tests/src/rules/newline-after-import.js

Hi, this is my fix issue https://github.com/benmosher/eslint-plugin-import/issues/1004

[Fix] `newline-after-import`: recognize decorators

---

CHANGELOG.md
src/rules/no-unused-modules.js
tests/files/no-unused-modules/flow-0.js
tests/files/no-unused-modules/flow-1.js
tests/files/no-unused-modules/flow-2.js
tests/src/rules/no-unused-modules.js

#1542 was intended to fix issue #1540 but introduced a more critical issue, #1564. In my case, it blocks upgrading to the latest version with all the fancy features like alphabetical sorting.
This PR just reverts it
Fixes #1564. Reopens #1540.

Revert "[flow] `no-unused-modules`: add flow type support"

---

CHANGELOG.md
docs/rules/order.md

`alphabetize` option in `order` rule, does not permit boolean

[Docs] `order`: fix bad inline config

---

CHANGELOG.md
appveyor.yml
utils/resolve.js

This PR will add support for Windows Subsystem for Linux.
Windows Subsystem for Linux seems to have quite a weird treatment with file and directory-names.
While directories are case-sensitive (directory `./tests` exists while `./TeSts` doesn't), files don't seem to be (both `reSOLVE.js` and `resolve.js` exist).
This PR adds WSL-support by checking whether both directories and files are case-sensitive before setting `CASE_SENSITIVE_FS`.

Add fix for Windows Subsystem for Linux

---

CHANGELOG.md
src/ExportMap.js
tests/files/typescript-declare-nested.d.ts
tests/src/rules/namespace.js

Relates to #1673
Add nested namespace declaration handling for Typescript.

Add nested namespace handling for TS

---

CHANGELOG.md
tests/src/rules/order.js

Add TypeScript `import type` tests for `import/order` rule in #1667.

[Tests] `order`: Add TS import type tests

---

CHANGELOG.md
src/ExportMap.js
tests/files/typescript-declare-interface.d.ts
tests/src/rules/namespace.js

Relates to https://github.com/benmosher/eslint-plugin-import/pull/1528#discussion_r424564412
With #1528, in some cases, interface declaration crashed this plugin. This PR fixes it.

Fix interface declarations for Typescript

---

CHANGELOG.md
src/rules/no-unused-modules.js
tests/files/no-unused-modules/renameDefault-2/ComponentA.js
tests/files/no-unused-modules/renameDefault-2/ComponentB.js
tests/files/no-unused-modules/renameDefault-2/components.js
tests/files/no-unused-modules/renameDefault-2/usage.js
tests/files/no-unused-modules/renameDefault/Component.js
tests/files/no-unused-modules/renameDefault/components.js
tests/files/no-unused-modules/renameDefault/usage.js
tests/src/rules/no-unused-modules.js

[Fix] Fixing typo in IDE section

---

CHANGELOG.md
docs/rules/no-webpack-loader-syntax.md

Updates Webpack URL docs

---

CHANGELOG.md
docs/rules/no-unused-modules.md

First change: 
Change 
```js
import * from  'file-c'
``` 
to 
```js
import * as fileC from  'file-c'
```
The former isn't valid javascript, right?
Second change: Remove example 'file-d', I couldn't see a difference from 'file-c'
Third change: Rename 'file-e' to 'file-d'.

[no-unused-rules]: Fix docs for  unused exports

---

CHANGELOG.md
src/rules/no-extraneous-dependencies.js

Hi.
I start with simple refactoring but I already have few suggestions with code changes and tests that will make no-extraneous-dependencies more flexible for monorepo projects.
This PR is a warmup. I'd like to see if our interaction goes well.
I hope you will enjoy my contribution.
Cheers,
Adam

[Refactor] `no-extraneous-dependencies`: use moduleVisitor

---

appveyor.yml
package.json

~Babel~ `nyc` caused some errors on its currently installed version as seen in the AppVeyor history logs.
Some key modules of the development-environment have been updated:
- `nyc` ("on the fly"-update in AppVeyor-script)
- ~`babel`-modules~
- ~`mocha`~
~Though, applying this PR won't cause any issues when using with older versions of `nodeJS` (unless babel is configured correctly (see below)), after applying this PR, a nodeJS `>=8` is required to develop this project.
As mentioned this should have no impact to the usage of the module, but to the development of the module which then will be performed with more modern module-versions.~
~To ensure, the built module also works for NodeJS `argon`, setting [this option (`targets.node`)](https://babeljs.io/docs/en/babel-preset-env#targetsnode) …

Fix development-environment to work for Windows

---

CHANGELOG.md
docs/rules/no-internal-modules.md
src/rules/no-internal-modules.js
tests/src/rules/no-internal-modules.js

Resolves https://github.com/benmosher/eslint-plugin-import/issues/1481
In the ticket it was suggested to add an option for this behavior. Do you still want this rule behind an option? This behavior with the `export` feels so natural to me that I would feel strange if it wasn't the default behavior. 
I update the documentation, but I didn't know how to update the changelog. I wouldn't be against some guidance or help here :blush:.
I hesitated to clean the code in [`/src/rules/no-internal-modules.js`](https://github.com/benmosher/eslint-plugin-import/blob/5101b73effbf3706495f62121a8719f0ea0e2c68/src/rules/no-internal-modules.js) to use the step down rule, but I don't want to impose my tastes on this. Do you want me to do it?

Update no internal modules with exports

---

appveyor.yml
scripts/GetCI/GetCI.psm1
scripts/ci.cmd

Adding support for `WSL` to AppVeyor caused the `appveyor.yml` file to look quite complicated.
If applied, this PR will simplify the `appveyor.yml`-file by temporarily adding a Cmdlet for invoking commands either using `.` (source)  or `wsl` depending on the current configuration.
This allows us to use the same commands for both `WSL` and `Native`, leaving only `install`-commands as separate sections.
The [`GetCI.psm1`-file](https://github.com/manuth/eslint-plugin-import/blob/0d2fa0031ef81b16b7d22b6b873cdf8b0a815ec8/scripts/GetCI/GetCI.psm1) contains a PowerShell function called `Get-CICommand`. This takes a string containing a command (such as `npm install`, `sudo npm install -g rimraf`) and converts it for the appropriate platform:
- For `WSL`, a `wsl` is prepended  
Example: `sudo npm …

Improve AppVeyor Configuration

---

CHANGELOG.md
package.json
src/ExportMap.js
tests/files/typescript-export-as-default-namespace/index.d.ts
tests/files/typescript-export-as-default-namespace/tsconfig.json
tests/files/typescript-export-assign-default-namespace/index.d.ts
tests/files/typescript-export-assign-default-namespace/tsconfig.json
tests/src/rules/default.js

Possible duplicate of #1528 (but uses `tsconfig.json`)
Aims to fix #1527
For example, I want to import React as `import React from "react"`. I can do this by using `esModuleInterop: true` in `tsconfig.json`, but eslint doesn't know about that.
This is a draft PR as I'm not really familiar with the codebase. I want to share my approach and receive feedback.

[New] `import/default`: support default export in TSExportAssignment

---

CHANGELOG.md
docs/rules/no-restricted-paths.md
src/rules/no-restricted-paths.js
tests/src/rules/no-restricted-paths.js

**Main change**
Adds a `message` configuration param for every `zone`, that will be displayed in case of the rule violation. 
The logic is pretty similar to eslint's [no-restricted-imports](https://eslint.org/docs/rules/no-restricted-imports#options)
**Background**
Sometimes, it is not very clear, why you can not import certain modules in certain scenarios. This is especially the case for newcomers. To be more user friendly, we could display additional info, right in the error message. It would look something like this:
```javascript
//eslint config
'import/no-restricted-paths': [
'error',
{
basePath: './src',
zones: [ {
target: './core',
from: './features',
message: '' +
'\n\nCore should be completely isolated from features.' +
'\nFeatures may use core but not vice versa',
}],
}
],
``` …

[no-restricted-path] Custom error message

---

CHANGELOG.md
src/rules/no-unused-modules.js
tests/files/no-unused-modules/typescript/file-ts-a.ts
tests/files/no-unused-modules/typescript/file-ts-c.ts
tests/files/no-unused-modules/typescript/file-ts-d.ts
tests/files/no-unused-modules/typescript/file-ts-e.ts
tests/src/rules/no-unused-modules.js

Fixes #1680
Note that `babel-eslint` parser does not handle typescript enums and do not produce the same declaration types as `@typescript-eslint/parser`.
`babel-eslint` => `InterfaceDeclaration`, `TypeAlias`
`@typescript-eslint/parser` => `TSInterfaceDeclaration`, `TSTypeAliasDeclaration`, `TSEnumDeclaration`

[New] `no-unused-modules`: consider exported TypeScript interfaces, types and enums

---

CHANGELOG.md
src/rules/no-extraneous-dependencies.js
tests/files/with-typescript-dev-dependencies/package.json
tests/src/rules/no-extraneous-dependencies.js

fixes #1618 
This PR is to avoid error `should be listed in the project's dependencies, not devDependencies.` when only importing typescript types

[Fix] `no-extraneous-dependencies`/TypeScript: do not error when importing type from dev dependencies

---

CHANGELOG.md
tests/src/rules/no-extraneous-dependencies.js

Thanks for your work on this plugin! :heart:
This PR extends `no-extranaeous-dependencies`' check for Flow type imports to also work with TypeScript. This should help with https://github.com/benmosher/eslint-plugin-import/issues/903#issuecomment-549942374.

[Tests] `no-extraneous-dependencies`: add tests for importing types

---

CHANGELOG.md
src/ExportMap.js
tests/files/typescript-export-assign-function.ts
tests/src/rules/default.js

Add test case for https://github.com/benmosher/eslint-plugin-import/issues/1818

[Tests] add test for importing `export =`

---

.babelrc
CHANGELOG.md
docs/rules/order.md
src/rules/order.js
tests/src/cli.js
tests/src/rules/order.js

The changes I've made in PR #1785 caused object-imports to fail.
This happened because the `order`-rule is not able to handle `null` as an import-name and I totally forgot to add tests for object-imports.
This PR will fix the support of object-imports by introducing a new import-type in addition to `require` and `import`: The `import:object`-type.
In order to match the `order`-rule's behavior perfectly, the object-literal being imported acts as the name which means following:
```ts
import log = console.log; // name: "console.log"
import debug = console.debug; // name: "console.debug"
```
Additionally there is a new import-`group` you can set for the `order`-rule called `"object"`, which includes all object-imports.
This new `"object"` group is in the `pathGroupsExcludedImportTypes`-array …

Fix Object-Import Errors

---

CHANGELOG.md
src/rules/newline-after-import.js
src/rules/order.js
tests/src/rules/newline-after-import.js
tests/src/rules/order.js

This PR adds support for TypeScript's "export import", typically used to re-export things.
In current `eslint-plugin-import` they are treated as imports rather than exports.
Related: #1829.
cc. @ljharb

`order`/`newline-after-import`: Add support for TypeScript's "export import"

---

.travis.yml
CHANGELOG.md
package.json
src/rules/dynamic-import-chunkname.js
tests/src/rules/dynamic-import-chunkname.js

This PR add supports for the `@typescript-eslint/parser` parser to the `dynamic-import-chunkname` rule. This parser use newer ES Tree spec `ImportExpression` from dynamic imports instead of `CallExpressions`.
This might fix #1771 but I haven't tried bumping `babel-eslint` to try it.
cc @ljharb

[Fix] `dynamic-import-chunkname`/TypeScript: support `@typescript-eslint/parser`

---

CHANGELOG.md
src/rules/order.js
tests/src/rules/order.js

Forcing object-imports to be alphabetized might lead to issues as they might depend on each other.
***Example:***
```ts
import { ESLint } from "eslint";
// Object-imports
import A = ESLint;
import OutputFixes = A.outputFixes;
OutputFixes([]);
```
Currently, this piece of code will report an error because `A.LintResult` has a lower rank than `ESLint`.
Alphabetizing these imports would cause this code to fail:
```ts
import { ESLint } from "eslint";
// Object-imports
import OutputFixes = A.outputFixes;
import A = ESLint;
OutputFixes([]);
```
```
Cannot read property 'outputFixes' of undefined
```
I see three different approaches to fix this:
* ~~Sort object-imports with following conditions:~~
1. ~~Number of dots (e.g. `ts` comes before `ts.protocol` and `ts.protocol` comes before …

[patch] `order`/TypeScript: ignore ordering of object imports

---

CHANGELOG.md
src/rules/no-default-export.js

Added docsUrl to `no-default-export` rule
Closes #1769
Signed-off-by: Beatriz Rezener <beatrizrezener@gmail.com>

[docs] `no-default-export`: Fix docs url

---

CHANGELOG.md
docs/rules/imports-first.md

This PR recreates the `imports-first` docs, since, although deprecated, it has not yet been removed from project.
In the document it's informed that the rule is deprecated, has been replaced by `first` and provides a link to the new one.
Closes #1638.
Signed-off-by: Beatriz Rezener <beatrizrezener@gmail.com>

[docs] `imports-first`: deprecation info and link to `first` docs

---

CHANGELOG.md
src/core/importType.js
tests/src/core/importType.js
tests/src/rules/extensions.js

Fixes #1851
Before this commit, @/abc was being wrongly detected as a scoped module.
This was a problem when somebody had a webpack alias `@`. (eg. @ -> ./src)
In general, scoped modules can't start with @/, I think they have to be like @abcd/sometext.

Fix @/abc being treated as scoped module

---

CHANGELOG.md
src/ExportMap.js
tests/files/named-exports.js
tests/src/core/getExports.js
tests/src/utils.js

Named export supports rest operator, but when using with eslint-plugin-import, it throws `TypeError: Cannot read property 'type' of undefined` because `RestElement` is not handled and the value is treated as a `ObjectProperty` type

[Fix] allow using rest operator in named export

---

CHANGELOG.md
docs/rules/dynamic-import-chunkname.md
src/rules/dynamic-import-chunkname.js
tests/src/rules/dynamic-import-chunkname.js

Single quotes are supported by Webpack at least in v4.43.0, which is the
version I'm currently using. Since my eslint style prefers single 
quotes, I naturally wrote my Webpack magic comments to match, which 
worked w/o issue until I tried to enable this rule.
Implemented as a non-breaking relaxation of the existing rule to avoid 
complexity per
https://github.com/benmosher/eslint-plugin-import/issues/1130#issuecomment-464365363
but please let me know if you prefer a different approach!
Fixes #1130.

[Fix] `dynamic-import-chunkname`: allow single quotes to match Webpack support

---

resolvers/webpack/README.md
resolvers/webpack/index.js
resolvers/webpack/test/config.js

**note**: We should probably increment major version, because it'll change the behavior a configPath starting with '.' (in a more 'expected' way, but still different, https://github.com/caub/eslint-import-resolver-webpack-bug demonstrates this)

[resolvers/webpack] [breaking] Allow to resolve config path relative to working directory

---

src/rules/no-unused-modules.js
tests/files/no-unused-modules/flow/flow-0.js
tests/files/no-unused-modules/flow/flow-1.js
tests/files/no-unused-modules/flow/flow-2.js
tests/files/no-unused-modules/flow/flow-3.js
tests/files/no-unused-modules/flow/flow-4.js
tests/files/no-unused-modules/typescript/file-ts-a-import-type.ts
tests/files/no-unused-modules/typescript/file-ts-a.ts
tests/files/no-unused-modules/typescript/file-ts-b-unused.ts
tests/files/no-unused-modules/typescript/file-ts-b-used-as-type.ts
tests/files/no-unused-modules/typescript/file-ts-c-unused.ts
tests/files/no-unused-modules/typescript/file-ts-c-used-as-type.ts
tests/files/no-unused-modules/typescript/file-ts-d-unused.ts
tests/files/no-unused-modules/typescript/file-ts-d-used-as-type.ts
tests/files/no-unused-modules/typescript/file-ts-e-unused.ts
tests/files/no-unused-modules/typescript/file-ts-e-used-as-type.ts
tests/src/rules/no-unused-modules.js

Fixes https://github.com/benmosher/eslint-plugin-import/issues/1564 :
- Ignore Flow type exports
- Add tests for Flow type imports/exports
- Remove Typescript tests using "babel-eslint" (because resulting types seems to be Flow types)
- Add some missing cases in Typescript tests
- Add some tests for Typescript type imports

`no-unused-modules`: ignore flow type exports

---

CHANGELOG.md
src/rules/export.js
tests/src/rules/export.js

[Fix] `export`/TypeScript: properly detect export specifiers as children of a TS module block

---

package.json
src/core/importType.js

This PR replaces `resolve/lib/core` by `is-core-module` is suggested in https://github.com/browserify/resolve/commit/1222da1fc7f249d053a9ba30dbab284640f13948
**context**: Babel e2e test is failing because `resolve/lib/core` is deprecated: https://app.circleci.com/pipelines/github/babel/babel/4244/workflows/de314db0-9b52-44c8-b6a5-9ca7d4b2cfd6/jobs/30580
/cc @ljharb

[Refactor] `importType`: use `is-core-module` instead of `resolve/lib/core`

---

CHANGELOG.md
src/rules/order.js
tests/src/rules/order.js

[Fix] `order`: ignore requires in template literal

---

CHANGELOG.md
src/rules/no-webpack-loader-syntax.js
tests/src/rules/no-webpack-loader-syntax.js

Tiny fix 😄 
Every time I was manually adding a `import` on a typescript in vscode file it would trigger this rule, because the parser interprets the code as valid, passing an incomplete AST node down.
The test case seems a bit weird, but it's what naturally happens when typing on the top part of a file, and having eslint constantly running 😄
Logs from a usual session:
```
[Error] ESLint stack trace:
[Error] TypeError: Cannot read property 'indexOf' of undefined
Occurred while linting /redacted/file.tsx:1
at reportIfNonStandard (/redacted/node_modules/eslint-plugin-import/lib/rules/no-webpack-loader-syntax.js:5:12)
at handleImports (/redacted/node_modules/eslint-plugin-import/lib/rules/no-webpack-loader-syntax.js:24:9)
at /redacted/node_modules/eslint/lib/linter/safe-emitter.js:45:58
at …
```

[Fix] `no-webpack-loader-syntax`/TypeScript: avoid crash on missing name

---

CHANGELOG.md
src/rules/no-extraneous-dependencies.js

This rule is super slow in our code base, and it seems it invoke one IO request for every single file..

[patch] `no-extraneous-dependencies`: Add package.json cache

---

resolvers/webpack/index.js
resolvers/webpack/package.json

This significantly shrinks our dependency tree.  Fixes #631.

[resolvers/webpack] Replace node-libs-browser with is-core-module

---

.gitignore
CHANGELOG.md
src/ExportMap.js
src/rules/no-cycle.js
src/rules/no-unused-modules.js
tests/files/no-unused-modules/typescript/file-ts-f-import-type.ts
tests/files/no-unused-modules/typescript/file-ts-f.ts
tests/files/no-unused-modules/typescript/file-ts-g-used-as-type.ts
tests/files/no-unused-modules/typescript/file-ts-g.ts
tests/src/rules/no-unused-modules.js

Fixes #1924
`ExportMap` now keeps track of each imported declaration (`imports.get(path).declarations`) and whether the declarations are only importing types (`isOnlyImportingTypes`). This is used by `no-cycle` to
- ignore only type imports
- report circular dependencies at the correct line
For example (from [this existing test](https://github.com/cherryblossom000/eslint-plugin-import/blob/1924/tests/src/rules/no-cycle.js#L159-L163)):
`depth-zero.js`
```js
import { bar } from './flow-types-depth-one'
```
`flow-types-depth-one.js`
```js
// @flow
// this import declaration doesn't trigger the rule because it's a type import
import type { FooType } from './flow-types-depth-two'
// this declaration does because of the 'bar' import, so the error message refers to this line
import { type …
```

[Fix] `no-unused-modules`: make type imports mark a module as used

---

CHANGELOG.md
src/ExportMap.js
tests/files/typescript-export-assign-property.ts
tests/src/core/getExports.js

Fix import/no-cycle perf regression

---

CHANGELOG.md
src/rules/extensions.js
src/rules/max-dependencies.js
src/rules/no-extraneous-dependencies.js
src/rules/no-internal-modules.js
src/rules/no-nodejs-modules.js
src/rules/no-restricted-paths.js
src/rules/no-self-import.js
src/rules/no-webpack-loader-syntax.js
tests/src/rules/extensions.js

This PR fixes #1230.
Not only for `import/extensions`, this PR also adds supports of all 
1) `ImportDeclaration`, 
2) `ExportNamedDeclaration`, 
3) `ExportAllDeclaration`, 
4) static require `CallExpression` 
for rules `import/extensions`, `import/max-dependencies`, `import/no-extraneous-dependencies`, `import/no-internal-modules`, `import/no-nodejs-modules`, `import/no-restricted-paths`, `import/no-self-import`, `import/no-webpack-loader-syntax` by abstracting out the common part for these callbacks.
Tests are added for `import/extensions`.

[Generic Import Callback] Make callback for all import once in rules

---

CHANGELOG.md
src/rules/first.js
tests/src/rules/first.js

The rule now handles `TSImportEqualsDeclaration`.
This closes #1957.

[Fix] first's handling of import = require

---

CHANGELOG.md
src/rules/no-commonjs.js
tests/src/rules/no-commonjs.js
tests/src/rules/no-dynamic-require.js

Detect require calls with expressionless template literals: ``require(`x`)``
Those are also not detected by the `no-dynamic-require` rule:
https://github.com/benmosher/eslint-plugin-import/blob/bdda0691cf703f13f6472b6e824d5168343dd52e/src/rules/no-dynamic-require.js#L11-L14

[New] `no-commonjs`: Allow expressionless template literals

---

CHANGELOG.md
docs/rules/no-named-as-default.md

[Docs] import/no-named-as-default: Fix typo

---

CHANGELOG.md
docs/rules/no-internal-modules.md
src/rules/no-internal-modules.js
tests/src/rules/no-internal-modules.js

Here is the pull request that implements #1842. 
Without `forbid` option provided, the behavior stay the same. It should be a semver-minor PR.
With `forbid` option provided, the rule check if a given path is explicitly forbidden before testing if it's allowed.

[New] `no-internal-modules`: Add `forbid` option

---

CHANGELOG.md
docs/rules/no-relative-packages.md
src/index.js
src/rules/no-relative-packages.js
tests/files/package-named/index.js
tests/files/package-named/package.json
tests/files/package-scoped/index.js
tests/files/package-scoped/package.json
tests/files/package/index.js
tests/files/package/package.json
tests/src/rules/no-relative-packages.js

Use this rule to prevent importing packages through relative paths.
It's useful in Yarn/Lerna workspaces, were it's possible to import a sibling
package using `../package` relative path, while direct `package` is the correct one.
Given the following folder structure:
```
my-project
├── packages
│   ├── foo
│   │   ├── index.js
│   │   └── package.json
│   └── bar
│       ├── index.js
│       └── package.json
└── entry.js
```
And the .eslintrc file:
```
{
...
"rules": {
"import/no-relative-packages": "error"
}
}
```
The following patterns are considered problems:
```js
/**
*  in my-project/packages/foo.js
*/
import bar from '../bar'; // Import sibling package using relative path
import entry from '../../entry.js'; // Import from parent package using relative path
/**
*  in …
```

New rule: `no-relative-packages`

---

CHANGELOG.md
docs/rules/no-relative-packages.md
src/index.js
src/rules/no-relative-packages.js
tests/files/package-named/index.js
tests/files/package-named/package.json
tests/files/package-scoped/index.js
tests/files/package-scoped/package.json
tests/files/package/index.js
tests/files/package/package.json
tests/src/rules/no-relative-packages.js

Duplicating #966 and hopefully fixed it 🤞 (sorry if this isn't the process).

[New]: add `no-relative-packages`

---

CHANGELOG.md
README.md
docs/rules/no-import-module-exports.md
package.json
src/index.js
src/rules/no-import-module-exports.js
tests/src/rules/no-import-module-exports.js

Fixes #760 
Still a work in progress. 
Updates to the changelog and docs to follow.

[New] Add `no-import-module-exports` rule

---

CHANGELOG.md
docs/rules/no-named-default.md
src/rules/no-named-default.js
tests/src/rules/no-named-default.js

Syncs the behavior of [`no-named-default`](https://github.com/benmosher/eslint-plugin-import/blob/v2.22.1/docs/rules/no-named-default.md) with [`named`](https://github.com/benmosher/eslint-plugin-import/blob/v2.22.1/docs/rules/named.md), which also ignores Flow imports & exports:
> Note that type imports and exports, as used by [Flow], are always ignored.
Without this fix, [`no-named-default`](https://github.com/benmosher/eslint-plugin-import/blob/v2.22.1/docs/rules/no-named-default.md) conflicts with the [`flowtype/type-import-style`](https://github.com/gajus/eslint-plugin-flowtype/blob/e93f1c0102c03b465bce260b6e085b04e1a0f934/.README/rules/type-import-style.md) rule with a default setting of "identifier".
"Identifier syntax":
```js
// @flow
import { type default as Foo } from "./bar"; …
```

[Fix] `no-named-default`: ignore Flow import type and typeof

---

tests/src/rules/extensions.js

Fixes #1851
Before this fix, `'import/extensions': ['warn', 'ignorePackages']` wouldn't warn `import chart from '@/configs/chart'`, this is an improvement over PR #1854.

[Tests] `extensions`: add cases to verify `@/configs/chart` is treated as a package

---

CHANGELOG.md
src/rules/no-extraneous-dependencies.js
tests/src/rules/no-extraneous-dependencies.js

Type imports were already ignored, but `typeof` imports should also be ignored.
For example:
```javascript
// @flow
import typeof TypeScriptModule from 'typescript';
```

Exclude flow `typeof` imports from extraneous dependencies

---

CHANGELOG.md
src/rules/no-unused-modules.js
tests/files/no-unused-modules/destructuring-a.js
tests/files/no-unused-modules/destructuring-b.js
tests/src/rules/no-unused-modules.js

Currently, when using a destructuring assignment with `export`, errors like this are thrown:
```
error  exported declaration 'undefined' not used within other modules  import/no-unused-modules
```
This PR fixes that issue.
Since the reasoning here seemed quite straightforward to me, I figured I'd jump straight to a PR. :)
(Minor question out of sheer curiosity: In tests, why the code duplication with code-to-be-linted in files but then also as strings within the tests?)

[New] `no-unused-modules`: Support destructuring

---

CHANGELOG.md
docs/rules/order.md
src/rules/order.js
tests/src/rules/order.js

[New] `order`: support type imports

---

CHANGELOG.md
src/rules/newline-after-import.js
tests/src/rules/newline-after-import.js

hey! found the bug. here in my pr enjoy!
how do I link it with #1784 ?

[Fix] `newline-after-import`: respect decorator annotations

---

CHANGELOG.md
src/rules/no-restricted-paths.js

**Main changes**
Move exceptions paths resolution and validation to rule create phase. 
**Background**
There was a performance downgrade if `zone` had `except` option defined. On every import every relative exception path had to be resolved to absolute path and validated. See a corresponding issue https://github.com/benmosher/eslint-plugin-import/issues/1758
**Results**
On our SPA we have a lot of zones with exceptions. It turned out that this simple change gives us almost 10 times better performance. Measured with `TIMING=1 eslint` on our project.
Before:
```
Rule                                    | Time (ms) | Relative
:---------------------------------------|----------:|--------:
import/no-restricted-paths              | 94633.358 |    72.2%
@typescript-eslint/no-floating-promises | …
```

[Fix] `no-restricted-paths`: enhance performance for exceptions

---

docs/rules/no-extraneous-dependencies.md
tests/files/no-unused-modules/file-destructured-1.js
tests/files/no-unused-modules/file-destructured-2.js
tests/src/rules/no-unused-modules.js

Fixes https://github.com/benmosher/eslint-plugin-import/issues/2037

Destructured exports no unused modules

---

resolvers/webpack/.eslintrc
resolvers/webpack/CHANGELOG.md
resolvers/webpack/index.js
resolvers/webpack/test/externals.js
resolvers/webpack/test/files/webpack.config.webpack5.async-externals.js
resolvers/webpack/test/files/webpack.config.webpack5.js

This PR allows functions for resolving externals for both webpack 5 and prior to webpack 5 (issue: #1966 )
- To handle configs for both webpack 5 and priors, this PR [checks `externals.length` as webpack does](https://github.com/webpack/webpack/blob/v5.30.0/lib/ExternalModuleFactoryPlugin.js#L166).
- In webpack 5.15, `getResolve` function is added to the object in the first argument, so this PR provides a very simple `getResolve` implementation (using the return value of `getResolveSync`).
- In this PR async 'external functions' are still not supported (as async webpack config not supported; related: #1962)
- [synchronized-promise](https://www.npmjs.com/package/synchronized-promise) might be usable to resolve this, but I haven't tried yet. (If it is OK, I'll try to add using …

[resolvers/webpack] [New] add support for webpack 5 'externals function'

---

CHANGELOG.md
docs/rules/order.md

[Docs] `order`: Document options required to match ordering example

---

CHANGELOG.md
tests/src/rules/no-unresolved.js
utils/moduleVisitor.js

dynamic import has changed in estree
refs: https://github.com/estree/estree/issues/197
Fixes #2024

[Fix] `no-unresolved`: check import() 

---

CHANGELOG.md
tests/src/rules/no-unresolved.js

Dynamic imports landed in EcmaScript 2020, and Eslint now parses it out of the box.
However, the AST `node` containing the dynamic import is an `ImportExpression`, which is ignored by the `no-unresolved` rule.

[Tests] `no-unresolved`: add tests for `import()`

---

CHANGELOG.md
docs/rules/order.md
src/rules/order.js
tests/src/rules/order.js

fixes #1639 
This seems like a pretty simple solution, but does have one weird side effect: The behavior of the newline option changes slightly, in that it can now remove newlines between groups correctly when there are unassigned imports.  This is only the case when the new option is enabled.  Updating this to make that behavior consistent (always allow new-line changes around unassigned imports) would be safe, and easy to implement, but is a breaking change, so leaving it as is seems better.
cc @Alphy11  @ljharb

[New] `order`: Add `warnOnUnassignedImports` option to enable warnings for out of order unassigned imports

---

CHANGELOG.md
README.md

Here's a simple fix to #2032. As suggested, I didn't increase the prominence of `import/recommended` any more than `import/errors` and `import/warnings` already had.  Let me know if you'd like more or less change.

[Docs] Add import/recommended ruleset to README

---

CHANGELOG.md
src/rules/order.js
tests/src/rules/order.js

Fixes #2064
Added a new test for the broken scenario.

[Fix] `order`: fix alphabetical sorting

---

CHANGELOG.md
README.md

Add `no-relative-packages` to list of to the list of rules

[Docs] Add no-relative-packages to list of to the list of rules

---

CHANGELOG.md
package.json
src/rules/no-restricted-paths.js
tests/src/rules/no-restricted-paths.js

Fixes #2089
In this PR I removed `contains-paths` dependency and used node's `path.relative` to identify if a file is inside the `target`. I used an approach similar to the one used in `src/core/importType`

[Fix] `no-restricted-paths`: false-positive matches

---

CHANGELOG.md
src/ExportMap.js
src/rules/no-cycle.js
tests/files/cycles/flow-types-only-importing-multiple-types.js
tests/files/cycles/flow-types-only-importing-type.js
tests/files/cycles/flow-types-some-type-imports.js
tests/src/rules/no-cycle.js

This fixes these two bugs:
```ts
// a.ts
// false positive: reports a cycle even though b.ts is only importing types
import { foo } from './b'
// b.ts
import type { Bar } from './a'
```
```js
// a.js
// @flow
// false negative: doesn't report a cycle even though b.js is importing the value bar
import { foo } from './b'
// b.js
// @flow
import { bar, type Baz } from './a'
```
There isn't an open issue for these, but these issues were relatively quick and easy for me to fix so I don't really mind if this PR gets rejected. Also, these bugs were introduced by me in #1974 (oops), so I wanted to fix them.
If you would like me to split these two bug fixes into two PRs, I'm more than happy to do that as well.

Fix a couple of `no-cycle` bugs

---

CHANGELOG.md
src/rules/order.js
tests/src/rules/order.js

[Fix] `order`: restore default behaviour unless `type` is in groups

---

CHANGELOG.md
src/rules/no-extraneous-dependencies.js
tests/files/node_modules/rxjs/index.js
tests/files/node_modules/rxjs/operators/index.js
tests/files/node_modules/rxjs/operators/package.json
tests/files/node_modules/rxjs/package.json
tests/files/package.json
tests/src/rules/no-extraneous-dependencies.js

- resolve nested package.json problems (a/b/c import will check a, a/b and a/b/c)
- resolve renamed dependencies: checks the import name and the resolve package name
Fixes #2066. Fixes #2065. Fixes #2058. Fixes #2078.

[Fix] `no-extraneous-dependencies`: fix package name algorithm

---

CHANGELOG.md
src/rules/no-duplicates.js
tests/src/rules/no-duplicates.js

Fixes #2027
Each removed import can potentially leave an empty line character. When a module has multiple repeated imports, the output of the autofix includes a gap of empty lines. The number of empty lines are equal to the number of removed imports.
```js
import { One } from '../fragments/one'
import { Two } from '../fragments/two'
import { Three } from '../fragments/three'
import { Four } from '../fragments/four'
import { Five } from '../fragments/five'
import { Six } from '../fragments/six'
import { Seven } from '../fragments/seven'
import { Eight } from '../fragments/eight'
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core'
import { OneDoc } from '../fragments/one'
import { TwoDoc } from '../fragments/two'
import { ThreeDoc } from …
```

[Fix] `no-duplicates`: ensure autofix avoids excessive newlines

---

CHANGELOG.md
docs/rules/extensions.md

When using `'import/extensions': ['error', 'always']`, `import express from 'express'` is allowed.

[Docs] extensions: removed incorrect cases

---

CHANGELOG.md
tests/src/rules/order.js

Issue: https://github.com/benmosher/eslint-plugin-import/issues/2159

Update tests to illustrate `pathGroupsExcludedImportTypes: ['type']`

---

CHANGELOG.md
src/core/packagePath.js
src/rules/named.js
src/rules/newline-after-import.js
src/rules/no-cycle.js
src/rules/no-extraneous-dependencies.js
src/rules/no-import-module-exports.js
src/rules/no-relative-packages.js
src/rules/no-relative-parent-imports.js
src/rules/no-restricted-paths.js
src/rules/no-self-import.js
src/rules/no-unassigned-import.js
src/rules/no-unused-modules.js
src/rules/no-useless-path-segments.js
tests/src/core/getExports.js
tests/src/core/resolve.js
utils/resolve.js

Starting with 7.28.0, ESLint has a new feature [distinguishing the physical filename from the virtual filename](https://eslint.org/blog/2021/06/eslint-v7.28.0-released#contextgetphysicalfilename).
> ## context.getPhysicalFilename()
> Rules can now use the new method getPhysicalFilename() on the context object to get the full path of the file on disk without any code block information.
>
> The difference between getPhysicalFilename and getFilename is observable when ESLint is used with processors:
>
> ```js
> context.getPhysicalFilename() // "/project/example.md"        - original file
> context.getFilename()         // "/project/example.md/0_0.js" - virtual filename assigned to a code block
> ```
When there's a difference, this plugin needs the real, physical filename. (See …

Use getPhysicalFilename() instead of getFilename() if available (ESLint 7.28+)

---

CHANGELOG.md
docs/rules/order.md

Motivation: #1665
> I think there's an opportunity to improve the documentation for the pathGroupsExcludedImportTypes option. The documentation made me think the allowed values for pathGroupsExcludedImportTypes were only groups (e.g., builtin, external, etc.) and not patterns (e.g., react, react-router-dom, etc).
I think this paragraph makes a lot of sense, and for a while, I couldn't figure out how to configure this option.

[Docs] `order`:  improve the documentation for the `pathGroupsExcludedImportTypes` option

---

CHANGELOG.md
src/core/importType.js
tests/src/core/importType.js
tests/src/rules/extensions.js

[Fix] `extensions`/`importType`: fix isScoped treating @/abc as scoped module

---

CHANGELOG.md
src/rules/no-dynamic-require.js
tests/src/rules/no-dynamic-require.js

Requested in [#700](https://github.com/benmosher/eslint-plugin-import/issues/700#issuecomment-268881937).
Adds an option `esmodule` to `no-dynamic-require` that defaults to false.
I think it'd be nice if `no-dynamic-require` was renamed to something like `no-nonliteral-import`, since it is confusing with `import()` being called "dynamic import".

[New] `no-dynamic-require`: add option `esmodule`

---

CHANGELOG.md
src/rules/named.js
tests/src/rules/named.js

Related: #1145
Adds an option `commonjs` to `named` rule, which will check a destructured `require` statement.
Invalid:
```javascript
// ./foo.js
export const foo = 'bar';
// ./bar.js
const {baz} = require('./foo');
```
valid:
```javascript
// ./bar.js
export const bar = 'foo';
export const foo = 'baz';
// ./baz.js
const {bar} = require('./bar');
// ./foo2.js
const {bar, foo} = require('./bar');
// ./foo3.js
let {bar} = require('./bar'), {foo} = require('./bar');
```

[New] `named`: add commonjs option

---

CHANGELOG.md
docs/rules/no-namespace.md
src/rules/no-namespace.js
tests/src/rules/no-namespace.js

Closes #1916
Closes #1903
Hi, we want to use the rule `no-namespace` in our project but we have a `i18n` codegen tool that forces us to use wildcard imports for certain files that follow some pattern (`\S+\.i18n`, to be precise). Also I've seen that there's people with similar issue.
I thought that we can implement something similar to `argsIgnorePattern/varsIgnorePattern` in [core eslint rules](https://github.com/eslint/eslint/blob/master/lib/rules/no-unused-vars.js#L107). 
I made a test for that case and updated the docs as well. Please let me know if there's something else I should do to get this merged.

[New] `no-namespace`: Add `ignore` option

---

CHANGELOG.md
src/rules/max-dependencies.js
tests/src/rules/max-dependencies.js

Adds support for ignoring type imports.
Fixes #1843. Fixes #1136.

[New] `max-dependencies`: add option `ignoreTypeImports`

---

CHANGELOG.md
README.md

Sorry in advance if you find mistakes. Feel free to point me where need to fix

[Docs] add description how to use plugin with pnp/yarn berry

---

CHANGELOG.md
src/ExportMap.js
tests/files/typescript-export-react-test-renderer/index.d.ts
tests/files/typescript-export-react-test-renderer/tsconfig.json
tests/src/rules/default.js

This PR aims to fix #2183 by adding default export if anything is exported and `esModuleInterop` is set to true.
This probably should've been done in #1689 that I originally opened to add `esModuleInterop` support.

[Fix] ExportMap: Add default export when esModuleInterop is true and anything is exported

---

CHANGELOG.md
docs/rules/extensions.md

Add cases to show more accurate behavior of `always`.

[Docs] `extensions`: improved cases for using `@/...`

---

CHANGELOG.md
docs/rules/max-dependencies.md

Adds documentation for the `ignoreTypeImports` option which was introduced here: https://github.com/import-js/eslint-plugin-import/pull/1847

Document `ignoreTypeImports` option for max-dependencies rule

---

tests/src/rules/no-amd.js
tests/src/rules/no-commonjs.js

This PR fixes the no-amd and no-commonjs rule test cases.
See https://github.com/import-js/eslint-plugin-import/pull/2191#discussion_r689245594.
Previous test cases depended on the babel-eslint v8 patch to work. The following command fails because the babel-eslint v8 patch is not used.
```bash
npx cross-env BABEL_ENV=test nyc -s mocha tests/src/rules/no-amd.js
npx cross-env BABEL_ENV=test nyc -s mocha tests/src/rules/no-commonjs.js
```
With this PR, the test cases will work even with the above command.

Fix test cases of no-amd and no-commonjs

---

tests/src/cli.js

This PR fixes the `cli` test case to add the project eslint-plugin-import in CLIEngine and test.
See https://github.com/import-js/eslint-plugin-import/pull/2191#discussion_r690046415.

[Tests] `cli`: test the current plugin, not an installed one

---

CHANGELOG.md
src/rules/no-duplicates.js
tests/src/rules/no-duplicates.js

Fixes #2114, #2130
Note that #2114 suggests the correct fix looks like:
```ts
import type {default as dnajs, AccountQuery} from '@netflix-internal/dnajs';
```
but this PR will generate:
```ts
import type dnajs from '@netflix-internal/dnajs';
import type {AccountQuery} from '@netflix-internal/dnajs';
```
This avoids conflicts with `no-named-default` mentioned in #2130.

[Fix] `no-duplicates`: type import fixer generates valid TypeScript 

---

tests/src/cli.js

This PR change to use the ESLint class in `tests/src/cli.js` test case (when ESLint >= v7).
See https://github.com/import-js/eslint-plugin-import/pull/2191#issuecomment-902143316.

[Tests] use ESLint class in `cli` test

---

CHANGELOG.md
docs/rules/no-restricted-paths.md
package.json
src/rules/no-restricted-paths.js
tests/src/rules/no-restricted-paths.js

Connected to https://github.com/import-js/eslint-plugin-import/issues/2123
Added support for glob patterns. More details in `docs/rules/no-restricted-paths.md` in this PR
Although it would be easier to replace the rule so it works with globs only, I tried to don't make any breaking changes 🤞

`no-restricted-paths` support glob patterns

---

CHANGELOG.md
docs/rules/no-unresolved.md
src/rules/no-unresolved.js
tests/src/core/resolve.js
tests/src/rules/no-unresolved.js
utils/CHANGELOG.md
utils/resolve.js

Fix #1259 issue. The code above should be identified as invalid by `import/no-unresolved` rule with enabled `caseSensitiveStrict` option:
```js
/*eslint import/no-unresolved: [2, { caseSensitiveStrict: true }]*/
// Absolute paths
import Foo from `/Users/fOo/bar/file.js` // reported, /Users/foo/bar/file.js
import Foo from `d:/fOo/bar/file.js` // reported, d:/foo/bar/file.js
// Relative paths, cwd is Users/foo/
import Foo from `./../fOo/bar/file.js` // reported
```

[New] `no-unresolved`: add `caseSensitiveStrict` option

---

CHANGELOG.md
docs/rules/no-unused-modules.md
src/ExportMap.js
src/rules/no-unused-modules.js
tests/files/no-unused-modules/dynamic-import-js-2.js
tests/files/no-unused-modules/dynamic-import-js.js
tests/files/no-unused-modules/exports-for-dynamic-js-2.js
tests/files/no-unused-modules/exports-for-dynamic-js.js
tests/files/no-unused-modules/typescript/dynamic-import-ts.ts
tests/files/no-unused-modules/typescript/exports-for-dynamic-ts.ts
tests/src/core/getExports.js
tests/src/core/parse.js
tests/src/rules/no-unused-modules.js
utils/CHANGELOG.md
utils/parse.js
utils/unambiguous.js
utils/visit.js

[New] no-unused-modules: support dynamic imports [2]

---

CHANGELOG.md
docs/rules/no-unused-modules.md
src/ExportMap.js
src/rules/no-unused-modules.js
tests/files/no-unused-modules/dynamic-import-js-2.js
tests/files/no-unused-modules/dynamic-import-js.js
tests/files/no-unused-modules/exports-for-dynamic-js-2.js
tests/files/no-unused-modules/exports-for-dynamic-js.js
tests/files/no-unused-modules/typescript/dynamic-import-ts.ts
tests/files/no-unused-modules/typescript/exports-for-dynamic-ts.ts
tests/src/core/getExports.js
tests/src/core/parse.js
tests/src/rules/no-unused-modules.js
utils/CHANGELOG.md
utils/parse.js
utils/unambiguous.js
utils/visit.js

All occurences of `import('...')` are treated as namespace imports
(`import * as X from '...'`)
Fixes #1951.

[New] `no-unused-modules`: support dynamic imports 

---

CHANGELOG.md
package.json
src/core/packagePath.js
src/rules/no-extraneous-dependencies.js
src/rules/no-import-module-exports.js
src/rules/no-relative-packages.js
src/rules/no-unused-modules.js
tests/files/package.json
utils/CHANGELOG.md
utils/package.json
utils/pkgUp.js
utils/readPkgUp.js

Inspired by #2046, I dug into what [`read-pkg-up`](https://github.com/sindresorhus/read-pkg-up/tree/v2.0.0) provides and found it to be very simple, for this particular case. Its downstream dependencies build in some safety and options that aren't necessary when you already know you're working with a `package.json`, and in this library's case, when you know you don't want to "normalize" it. Since `read-pkg-up` drags several libraries along with it, at least two of which don't actually add any functionality to `eslint-plugin-import`, and its use here is pretty straightforward, it seemed moderately reasonable to me to reproduce the functionality internally.

[Refactor] switch to an internal replacement for `pkg-up` and `read-pkg-up`

---

CHANGELOG.md
config/typescript.js
src/rules/no-unresolved.js
tests/src/rules/no-unresolved.js

I'm getting the following errors when linting TypeScript, without installing eslint-import-resolver-typescript:
```
1:24  error  Unable to resolve path to module 'mdast'  import/no-unresolved
3:24  error  Unable to resolve path to module 'unist'  import/no-unresolved
```
Can `import/no-unresolved: off` be added to the `plugin:import/typescript` preset, by the same logic as in #1726 (TypeScript compilation already confirms that imports are resolved)?

[Fix] no-unresolved: ignore type-only imports

---

CHANGELOG.md
src/rules/order.js
tests/src/rules/order.js

Without this, `import/order` checks if all imports in a file are sorted. The autofix would then move all imports to the type of the file, breaking TypeScript module declarations.
Closes #2217

[Fix] `order`: Fix import ordering in TypeScript module declarations

---

CHANGELOG.md
src/rules/no-extraneous-dependencies.js
src/rules/no-unresolved.js

I overlooked the second moduleVisitor callback parameter (the ImportDeclaration/ImportExpression) in #2220. Doesn't make a functional difference, just tidier than recovering `node` from `node.source`: https://github.com/import-js/eslint-plugin-import/blob/4f0f560544b4d6dcd2d1b7d5880bd5238099f979/utils/moduleVisitor.js#L34

[Refactor] `no-unresolved`, `no-extraneous-dependencies`: moduleVisitor usage

---

CHANGELOG.md
README.md

Make it more discoverable for new TypeScript users that they need  to install the TypeScript resolver.
Addresses this comment: https://github.com/import-js/eslint-plugin-import/issues/2236#issuecomment-949812173

[readme] Add note to TypeScript docs to install appropriate resolver

---

CHANGELOG.md
src/core/importType.js
src/rules/extensions.js
tests/src/core/importType.js

I added a test that was red before the fix (and added some tests for the unix separator)
Fixes #2258.

[Fix] `importType`: fix `isExternalModule` calculation

---

.gitignore
CHANGELOG.md
CONTRIBUTING.md
README.md
docs/rules/first.md
docs/rules/no-duplicates.md
docs/rules/no-mutable-exports.md
docs/rules/unambiguous.md
resolvers/node/CHANGELOG.md
resolvers/webpack/CHANGELOG.md
resolvers/webpack/index.js
resolvers/webpack/test/alias.js
src/rules/namespace.js
tests/files/flowtypes.js
tests/src/rules/no-unresolved.js
utils/CHANGELOG.md
utils/moduleVisitor.js
utils/resolve.js

Checked the links, skipping the redirect HTTP => HTTPS twice and continue using HTTPS once this way 0:-)

[Docs] HTTP => HTTPS

---

CHANGELOG.md
src/core/importType.js
src/rules/no-absolute-path.js
tests/src/core/importType.js

While writing imports in VSCode recently, I started to get errors throwm
from eslint that appear to originate from eslint-plugin-import.
Here's the strack trace from the output panel:
```
[Error - 3:52:43 PM] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
at validateString (internal/validators.js:124:11)
at isAbsolute (path.js:1029:5)
at isAbsolute (/path/to/repo/node_modules/eslint-plugin-import/src/core/importType.js:17:10)
at typeTest (/path/to/repo/node_modules/eslint-plugin-import/src/core/importType.js:92:7)
at resolveImportType (/path/to/repo/node_modules/eslint-plugin-import/src/core/importType.js:105:10)
at reportIfMissing (/path/to/repo/node_modules/eslint-plugin-import/src/rules/no-extraneous-dependencies.js:170:7)
at commonjs …
```

[Fix] `importType`: avoid crashing on a non-string

---

CHANGELOG.md
src/rules/no-default-export.js
tests/src/rules/no-default-export.js
tests/src/utils.js

Instead of reporting the entire export default declaration:
Only reporting the "default" token:

[Fix] `no-default-import`: limit highlight to the word "default"

---

CHANGELOG.md
docs/rules/order.md

Update docs for `import` rule / `newlines-between` option. Default value is taken from:
https://github.com/import-js/eslint-plugin-import/blob/ccb69d9a41e484802ecbfb88c5320defbf803902/src/rules/order.js#L588

[Docs] `order`: Remove duplicate mention of default

---

CHANGELOG.md
src/core/importType.js
src/rules/extensions.js
src/rules/no-cycle.js
tests/src/core/importType.js
tests/src/rules/no-extraneous-dependencies.js
tests/src/rules/no-internal-modules.js
tests/src/rules/order.js

Aims to close #2333.
The issue this PR addresses seems to have cropped up twice before. I've tried to include a new test case that will hopefully help prevent regressions. Also, I've tried to make the various "type" cases more independent, out of the belief that this will be more robust and future-proof. But I'd love any feedback! This is my first contribution, so I'm a little wary that I might be changing too many things at once, without the proper context for the decisions that led the code to be in its present state.
Looking at the code, it seemed like a good idea to have the check for "is this internal" stop being dependent on either "is this scoped" or "is this a module", and also to separate the "is this internal" logic from the "is this external" logic.
In doing so, it seemed …

Recognize properly resolving `@/*`-aliased imports as internal

---

CHANGELOG.md
src/ExportMap.js
src/rules/named.js
tests/files/dynamic-import-in-commonjs.js
tests/src/rules/named.js

Fix #2294
* Modify `ExportMap` to track whether the module is unambiguously ES6
* Add tests for named import with `import` as `require()`
Mark ambiguous (i.e. not unambiguously ESM) modules that contain dynamic import()
so that they can be ignored like other ambiguous modules when analysing named imports.
Previous to https://github.com/import-js/eslint-plugin-import/commit/7c382f02a6cafe676ee754a896092040dad8daf6 this was not necessary because a `null` ExportMap was returned for all ambiguous modules.
Parse the CommonJS exports instead of ignoring the CommonJS modules. Rejected because analysingg CommonJS exports seems out of scope of this plugin.

[Fix] `named`/`ExportMap`: handle named imports from CJS modules that use dynamic import

---

utils/CHANGELOG.md
utils/parse.js

In Babel 8, you won't be able to directly require `@babel/eslint-parser/worker/ast-info.cjs` anymore (there is a reason if the path contains "worker": it's meant to be used in workers after properly setting them up :stuck_out_tongue:). However, `@babel/eslint-parser` exposes the `visitorKeys` on its result object, similarly to how `@typescript-eslint/parser` does: you can access it without requiring any internal file.
We caught this in our integration tests: even if for some reason the error is logged without reporting a failure, in https://app.circleci.com/pipelines/github/babel/babel/8764/workflows/3516a741-7bca-4713-8b12-9f2f20310066/jobs/50483/parallel-runs/0/steps/0-103 you can see
```
Error while parsing /home/circleci/babel/eslint/babel-eslint-tests/test/fixtures/eslint-plugin-impor …
```

[utils] [patch] Fix `@babel/eslint-parser` 8 compatibility

---

CHANGELOG.md
tests/src/rules/no-nodejs-modules.js

[Tests] `no-nodejs-modules`: add tests for node protocol URL

---

CHANGELOG.md
src/ExportMap.js
src/rules/export.js
src/rules/named.js
src/rules/namespace.js
src/rules/no-default-export.js
src/rules/no-named-default.js
src/rules/no-named-export.js
src/rules/no-unused-modules.js
src/rules/prefer-default-export.js
tests/files/.eslintrc.js
tests/files/default-export-namespace-string.js
tests/files/default-export-string.js
tests/files/export-default-string-and-named.js
tests/files/no-unused-modules/arbitrary-module-namespace-identifier-name-a.js
tests/files/no-unused-modules/arbitrary-module-namespace-identifier-name-b.js
tests/files/no-unused-modules/arbitrary-module-namespace-identifier-name-c.js
tests/src/rules/default.js
tests/src/rules/export.js
tests/src/rules/named.js
tests/src/rules/namespace.js
tests/src/rules/no-anonymous-default-export.js
tests/src/rules/no-default-export.js
tests/src/rules/no-mutable-exports.js
tests/src/rules/no-named-as-default-member.js
tests/src/rules/no-named-as-default.js
tests/src/rules/no-named-default.js
tests/src/rules/no-named-export.js
tests/src/rules/no-unused-modules.js
tests/src/rules/prefer-default-export.js

This is still WIP.
Fixes #2355

[New] support ES2022 "Arbitrary module namespace identifier names"

---

CHANGELOG.md
docs/rules/no-unresolved.md

In the `ignore` example the backslash in `'\.img$'` was escaping the "." as a string character, not in the RegExp sense. `'\\.img$'` would be the correct string.

[Docs] `no-unresolved`: Fix RegExp escaping in readme 

---

CHANGELOG.md
src/rules/no-dynamic-require.js
tests/src/rules/no-dynamic-require.js
tests/src/utils.js

Espree now can parse ES2020 dynamic import as `ImportExpression`.

[New] `no-dynamic-require`: support dynamic import with espree

---

CHANGELOG.md
src/rules/export.js
tests/src/rules/export.js

Fixes #1964
Fixes false positives like this:
```ts
export class Foo { }
export namespace Foo { }
```
```ts
export function Foo() { }
export namespace Foo { }
```
```ts
export enum Foo { }
export namespace Foo { }
```

[Fix] `export`: false positive for typescript namespace merging

---

CHANGELOG.md
src/rules/no-duplicates.js
tests/src/rules/no-duplicates.js

Without this the `import/no-duplicates` rule reports imports of the same module inside different module declarations in the same file. It even autofixed them, which break the code.
Closes #2273

[Fix] no-duplicates: Ignore duplicate modules in different TypeScript module declarations

---

CHANGELOG.md
docs/rules/no-relative-packages.md
src/rules/no-relative-packages.js
tests/src/rules/no-relative-packages.js

I was using no-relative packages and noticed it didn't have a fixer. So, this adds a fixer.

[New] `no-relative-packages`: add fixer

---

CHANGELOG.md
tests/src/rules/named.js
tests/src/rules/no-unused-modules.js
tests/src/rules/prefer-default-export.js
tests/src/utils.js

These tests were generated but not executed. At least one test is failing:
```
1) TypeScript named [TypeScript] invalid import {a} from './export-star-3/b';:
AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: Did not specify errors for an invalid test of named [TypeScript]
+ expected - actual
-false
+true
at testInvalidTemplate (node_modules/eslint/lib/rule-tester/rule-tester.js:748:20)
at Context.<anonymous> (node_modules/eslint/lib/rule-tester/rule-tester.js:997:29)
```

[Tests] `named`: Run all TypeScript tests

---

tests/files/typescript-export-assign-object.ts
tests/src/rules/named.js

This pattern is valid typescript, but `import/named` can't find resolve the imports. Relevant issue: #1984 
[Here's a demo showing that it should work in TS](https://codesandbox.io/s/ts-export-assignment-demo-l2mym?file=/src/index.ts)
This test currently does not run, as no TS tests in `named.js` are currently running: waiting for #2427 
Once the test is wired up, it fails with:
```
1) TypeScript named [TypeScript] valid import { FooBar } from './typescript-export-assign-object':
AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: Should have no errors but had 1: [
{
ruleId: 'named [TypeScript]',
severity: 1,
message: "FooBar not found in './typescript-export-assign-object'",
line: 1,
column: 10,
nodeType: 'Identifier',
endLine: 1,
endColumn: 16
}
]
+ expected - actual
-1
+0
```

[Test] import/named should support export = assignment of object in TS

---

CHANGELOG.md
docs/rules/newline-after-import.md
src/rules/newline-after-import.js
tests/src/rules/newline-after-import.js

Closes #2151 
Initially, the rule only checked whether some piece of code succeeded the imports. This PR alters the rule to check for any comments on the line following the imports too and enforces the `newline` rule for the same.
However, my confusion here is:
Out of the two code snippets below, which one is valid?
First Block:
```
import path from 'path';
//  some comment
import foo from 'foo';
```
Second Block:
```
import path from 'path';
//  some comment
import foo from 'foo';
```
Right now, the code I have added parses the second block to be correct.
Side note: Ran existing tests as well, nothing breaks.

[New] `newline-after-import`: add `considerComments` option

---

CHANGELOG.md
src/rules/order.js
tests/src/rules/order.js

Closes #2385 
Hey @ljharb! Have added a fix for the linked issue, also added 4 basic tests.
Might need to add more tests, but would like to get the solution reviewed first.
Ran all tests, nothing breaks.

[Fix] `order`: move nested import entries closer to the main import entry

---

CHANGELOG.md
README.md

Add note mentioned at https://github.com/import-js/eslint-plugin-import/issues/2340#issuecomment-1105578590

[docs] note use of typescript in readme `import/extensions` section

---

CHANGELOG.md
docs/rules/order.md

Hai~,
In the source, the [default values](https://github.com/import-js/eslint-plugin-import/blob/b0e6f7f48945e2533e96d513248bf3e54e0c1aac/src/rules/order.js#L589) includes `"object"` for option `pathGroupsExcludedImportTypes`, but this is not reflected in the docs
This discrepancy been mentioned in [this comment](https://github.com/import-js/eslint-plugin-import/issues/2291#issuecomment-1050199872)

[Docs] `order`: use correct default value

---

CHANGELOG.md
tests/src/rules/no-unresolved.js
utils/moduleVisitor.js

[meta] replace `git.io` link in comments with the original URL

---

CHANGELOG.md
docs/rules/no-cycle.md
src/ExportMap.js
src/rules/no-cycle.js
tests/files/cycles/es6/depth-one-dynamic.js
tests/src/rules/no-cycle.js

Hi,
as discussed in #2265, I added a new option, `allowUnsafeDynamicCyclicDependency`. I've tested all cases I could.
Unfortunately, I did not managed to write tests using the `TS_OLD` parser. I don't know if this is important.
Feedbacks are welcome ! Have a nice day
Fixes #2265.

[New] `no-cycle`: add option to allow cycle via dynamic import

---

CHANGELOG.md
README.md

as said in the docs, In eslint v6+, users have to install the plugins locally.
refs: https://eslint.org/docs/user-guide/migrating-to-6.0.0#-plugins-and-shareable-configs-are-no-longer-affected-by-eslints-location

docs: remove global-install in readme

---

tests/files/no-unused-modules/prefix-child.js
tests/files/no-unused-modules/prefix-parent-bom.js
tests/files/no-unused-modules/prefix-parent-bomhashbang.js
tests/files/no-unused-modules/prefix-parent-hashbang.js
tests/files/no-unused-modules/prefix-parent.js
tests/src/rules/no-unused-modules.js
utils/CHANGELOG.md
utils/parse.js

ESLint does this outside their espree parser, so we need to do it as well. Just like ESLint, the code will convert hashbang to comments and strip off the BOM completely before handing the content to the parser.
Fixes: https://github.com/import-js/eslint-plugin-import/issues/1369

[Fix] Ignore hashbang and BOM while parsing

---

CHANGELOG.md
README.md

Add a real example usage for `eslint-import-resolver-typescript`, it seems a lot of users just ignore the non-example part...

[readme] clarify `eslint-import-resolver-typescript` usage

---

CHANGELOG.md
src/rules/order.js
tests/src/rules/order.js

Resolves #2494 
Creates more space (numerically) between consecutive groups to allow for what would have been overlapping path groups.
The issue occurs when there are enough (9-10) before/after `pathGroups` in consecutive `groups` where the rankings start to overlap with the previous/next group. See the repro in #2494 for one example of this.
I think a better fix would be to rework some of the ranking logic in `convertPathGroupsForRanks`. However, this change was a non-invasive easy workaround that doesn't introduce any regressions (as far as I can tell).

[Fix] `order`: leave more space in rankings for consecutive path groups 

---

utils/CHANGELOG.md
utils/package.json

This allows it to find eslint from module-require.js when the package manager is strict.

eslint-module-utils: add peer dependency on eslint

---

CHANGELOG.md
src/rules/no-cycle.js

- This leads to about a 5x speed up
Signed-off-by: Sebastian Malton <sebastian@malton.name>

[Refactor] `no-cycle`: Add per-run caching of traversed paths

---

CHANGELOG.md
src/ExportMap.js
tests/files/typescript-declare-module.ts
tests/src/core/getExports.js

[Fix] `ExportMap`: add caching after parsing for an ambiguous module

---

CHANGELOG.md
src/ExportMap.js
tests/files/cycles/es6/depth-one-reexport.js
tests/src/rules/no-cycle.js

This PR is a fix proposal for #2461. It adds `ExportNamedDeclaration`  to dependencies in the same way as `ImportDelcaration` does. I'm not familiar with the logic here, so please review carefully.

[Fix] `no-cycle`: add ExportNamedDeclaration statements to dependencies

---

tests/files/typescript-export-assign-object/index.ts
tests/files/typescript-export-assign-object/tsconfig.json
tests/src/rules/named.js

This pattern is valid typescript, but `import/named` can't find resolve the imports. Relevant issue: #1984 
[Here's a demo showing that it should work in TS](https://codesandbox.io/s/ts-export-assignment-demo-l2mym?file=/src/index.ts)
Test fails with
```
1) TypeScript named [TypeScript] valid import { FooBar } from './typescript-export-assign-object':
AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: Should have no errors but had 1: [
{
ruleId: 'named [TypeScript]',
severity: 1,
message: "FooBar not found in './typescript-export-assign-object'",
line: 1,
column: 10,
nodeType: 'Identifier',
endLine: 1,
endColumn: 16
}
]
+ expected - actual
-1
+0
```
Reopened from #2428

[Tests] `named`: Add direct test for `export =` assignment in TS

---

CHANGELOG.md
src/rules/dynamic-import-chunkname.js
tests/src/rules/dynamic-import-chunkname.js

This PR follows the conversation from https://github.com/import-js/eslint-plugin-import/pull/1411 and aims to add support for all of the magic comments that currently (at the point of opening this pr) supported by webpack itself. [Webpack documentation](https://webpack.js.org/api/module-methods/#magic-comments) and [ImportParserPlugin](https://github.com/webpack/webpack/blob/c181294865dca01b28e6e316636fef5f2aad4eb6/lib/dependencies/ImportParserPlugin.js) are used as reference for rules.
This PR **not yet ready** for merge and more of a PoC (haven't updated docs/changelog yet). The reason why i consider this more of a PoC is because by introducing changes in this PR, IMO rule becomes more than a "check for a correct chunkname in a webpack dynamic import" because it now validates other …

[Fix] `dynamic-import-chunkname`: add handling webpack magic comments

---

CHANGELOG.md
docs/rules/no-useless-path-segments.md

Really not much to say here. Somebody simply overlooked that `../` refers to the parent directory. 🙂
(Had me worried about whether this rule works correctly. Which it does.)
I also added the root `index.js` because of the `import "."` further below.

[Docs] `no-useless-path-segments`: fix paths

---

CHANGELOG.md
tests/files/cycles/ignore/.eslintrc
tests/files/cycles/ignore/index.js
tests/files/cycles/intermediate-ignore.js
tests/src/rules/no-cycle.js

This adds a (currently failing) test case for the issue: https://github.com/import-js/eslint-plugin-import/issues/2439

[Tests] `no-cycle`: add passing test cases

---

CHANGELOG.md
src/rules/extensions.js
src/rules/no-unresolved.js
tests/src/rules/extensions.js
tests/src/rules/no-unresolved.js

In #2220 and #2270, a fix was released that ignored type-only imports for the rules `no-unresolved` and `extensions` respectively.
However type-only **ex**ports are not ignored.
The rules could always be tricked by this code anyway:
```typescript
import type { A } from 'non-existing';
export { A };
```
the code above is equivalent to
```typescript
export type { A } from 'non-existing`;
```
but the second one would throw an error while the first one does not.
This PR fixes this inconsistencies.

[Fix] `no-unresolved`, `extensions`: ignore type-only exports

---

CHANGELOG.md
docs/rules/no-extraneous-dependencies.md
src/rules/no-extraneous-dependencies.js
tests/src/rules/no-extraneous-dependencies.js

…alidate imports of internal dependencies
Fixes #1678

[New] `no-extraneous-dependencies`: added includeInternal option to validate imports of internal dependencies

---

CHANGELOG.md
docs/rules/no-extraneous-dependencies.md
src/rules/no-extraneous-dependencies.js
tests/src/rules/no-extraneous-dependencies.js

Fixes #2542
@ljharb I'm not totally if this will work with Flow or only Typescript, or what the current Flow support is like. I couldn't get a Flow unit test to fail with this new option, but I don't see what in the code would be different between the two type systems.

[New] `no-extraneous-dependencies`: added includeTypes option to validate type imports

---

CHANGELOG.md
docs/rules/order.md
src/rules/order.js
tests/src/rules/order.js

Here's a preliminary PR that resolves #2339. It's my first contribution, so please bear with me! 🙂
- Type imports are now sorted before regular imports, because this appears to be the overwhelming ecosystem standard.
- To reduce ambiguity, error messages can now refer to "type import" instead of just "import".
- I included `typeof` support just in case (though I don't know much about Flow).
- Tests were updated to reflect revised behaviour, and two new tests were added.
I also did some opportunistic code cleanup:
- Some test messages seemed to reflect old non-deterministic rule behaviour with "before" vs. "after" errors. Given this is now predictable, I made the tests easier to understand and maintain.
- Coding style toward the end of the test file was all over the place, so I cleaned it …

[order] Sort type imports

---

CHANGELOG.md
docs/rules/order.md
src/rules/order.js
tests/src/rules/order.js

This PR is inspired by and replacing https://github.com/import-js/eslint-plugin-import/pull/2398 - which has been stale for a while.
Closes https://github.com/import-js/eslint-plugin-import/issues/2339

[order] Sort imports by import kinds

---

CHANGELOG.md
README.md
docs/rules/consistent-type-specifier-style.md
package.json
src/index.js
src/rules/consistent-type-specifier-style.js
tests/src/core/getExports.js
tests/src/rules/consistent-type-specifier-style.js
tests/src/utils.js

Fixes #2469
Adds a new rule as specced in #2469
To test this I had to bump the TS version to 4.5, as that was the first version that supported inline type specifiers.

[New] `consistent-type-specifier-style`: add rule

---

CHANGELOG.md
CONTRIBUTING.md

Update the docs based on a comment https://github.com/import-js/eslint-plugin-import/pull/2544#issuecomment-1237215419
Let's keep the future contributors informed :v:

[meta] `CONTRIBUTING.md`: mention inactive PRs

---

.github/workflows/node-4+.yml
.github/workflows/node-pretest.yml
.github/workflows/packages.yml
.github/workflows/rebase.yml
.github/workflows/require-allow-edits.yml

This PR adds minimum token permissions for the GITHUB_TOKEN in GitHub Actions workflows using https://github.com/step-security/secure-workflows. 
GitHub Actions workflows have a GITHUB_TOKEN with `write` access to multiple scopes. 
After this change, the scopes will be reduced to the minimum needed for each workflow. 
- This is a security best practice, so if the GITHUB_TOKEN is compromised due to a vulnerability or compromised Action, the damage will be reduced. 
- GitHub recommends defining minimum GITHUB_TOKEN permissions. 
https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
- The Open Source Security Foundation (OpenSSF) [Scorecards](https://github.com/ossf/scorecard) also treats not setting token permissions …

[actions] add minimum GitHub token permissions for workflows

---

CHANGELOG.md
docs/rules/order.md

formatting the json makes it more readable instead of everything on a single line

[readme] make json for setting groups multiline

---

CHANGELOG.md
README.md
docs/rules/no-empty-named-blocks.md
src/index.js
src/rules/no-empty-named-blocks.js
tests/files/empty-named-blocks.js
tests/src/rules/no-empty-named-blocks.js

This PR adds the `no-empty-named-blocks` rule, which forbids empty named blocks on imports.
Closes #2538

[New] Add `no-empty-named-blocks` rule

---

CHANGELOG.md
tests/src/rules/no-restricted-paths.js

I wanted to work on https://github.com/import-js/eslint-plugin-import/issues/2450, but decided to add tests for existing behaviour first, to ensure that subsequent work doesn't break it.
I've copied over all existing tests that had `import` and changed it to `import type`.
However, I have one failure currently that I can't figure out how to fix:
```
1) Typescript no-restricted-paths invalid import type a from "../client/a"
import type c from "./c.ts":
AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: Should have 2 errors but had 1: [
{
ruleId: 'no-restricted-paths',
severity: 1,
message: 'Unexpected path "../client/a" imported in restricted zone.',
line: 1,
column: 20,
nodeType: 'Literal',
endLine: 1,
endColumn: 33
}
]
+ expected - actual
-1
+2
at testInvalidTemplate …
```

[Tests] `no-restricted-paths`: `import type` tests

---

CHANGELOG.md
tests/src/rules/no-restricted-paths.js

#2450 
In proposed solution for #2450, there was one test case which was failing. I pulled the changes of that developer, updated repo with latest changes, then fixed one failing test case.

Fix: one failing test case from for `import type` cases in `no-restricted-paths`

---

CHANGELOG.md
README.md

From a discussion with @ljharb in https://github.com/import-js/eslint-plugin-import/issues/2586

Increase clarity around typescript configuration

---

CHANGELOG.md
src/ExportMap.js

Functions are passed more arguments than they have params declared.

[Fix] add missing param to function

---

.npmrc
.travis.yml

[Tests] npm 9 defaults `install-links` to `true`, which breaks us

---

CHANGELOG.md
src/rules/no-unused-modules.js
tests/files/no-unused-modules/browserObject/package.json
tests/src/core/getExports.js
tests/src/core/resolve.js
tests/src/rules/no-unused-modules.js

Fixes the error reported in [this issue](https://github.com/import-js/eslint-plugin-import/issues/1996) where `boolean` fields aren't handled nicely by `path.join`.
According to the `package.json` [browser field spec](https://github.com/defunctzombie/package-browser-field-spec#ignore-a-module), a `false` field denotes an ignored module in the browser.
```
// package.json
"browser": {
"browserObject": "./index.js",
"an-ignored-module": false
}
```

[Fix] `no-unused-modules`: `checkPkgFieldObject` filters boolean fields

---

.github/workflows/node-4+.yml
.github/workflows/node-pretest.yml
.github/workflows/packages.yml
.github/workflows/rebase.yml

This PR bumps GitHub Actions to their latest major versions, which now use Node 16 internally instead of Node 12 (EOL as of end of April 2022, no longer receives security updates):
- Changelog for `actions/checkout` can be [found here](https://github.com/actions/checkout/blob/main/CHANGELOG.md)
- Changelog for `codecov/codecov-action` actions can be [found here](https://github.com/codecov/codecov-action/blob/main/CHANGELOG.md)

[actions] update GitHub Actions

---

tests/files/jsx/bar/baz.jsx
tests/files/jsx/bar/index.js
tests/files/jsx/bar/qux.jsx
tests/files/jsx/re-export.js
tests/src/rules/namespace.js

Closes #2572 .
The main issue was that [ExportMap](https://github.com/import-js/eslint-plugin-import/blob/main/src/ExportMap.js) (lines 323-327) did not crawl exports from .jsx files because it did not pass the [file extension check](https://github.com/import-js/eslint-plugin-import/blob/main/utils/ignore.js). As a result, `ExportMap` class was not created for `.jsx` files. And in export cache map, value for `.jsx` files was simply set to null.
`Namespace` in turn, tried to retrieve `ExportMap` class for `.jsx`, but got null and flagged it as error.

[Tests] `namespace`: add passing test case to close #2572

---

CHANGELOG.md
package.json

First stable [v1.0.0](https://github.com/bmish/eslint-doc-generator/releases/tag/v1.0.0) release of [eslint-doc-generator](https://github.com/bmish/eslint-doc-generator).
Originally added in:
* https://github.com/import-js/eslint-plugin-import/pull/2582
The only change is that one CLI option was renamed.

Update eslint-doc-generator to v1.0.0

---

CHANGELOG.md
README.md
docs/rules/prefer-default-export.md
src/rules/prefer-default-export.js
tests/src/rules/prefer-default-export.js

Solution for #2600.
I have added new option for the `prefer-default-export` that will check any exporting file to have a default export.
```
"import/prefer-default-export": [
( "off" | "warn" | "error" ),
{ "target": "single" | "any" } // default is "single"
]
```
* **single** (current implementation of the rule, I did not change anything here): When there is only a single export from a module, prefer using default export over named export.
All examples from below are from the [rule descriptions](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/prefer-default-export.md).
Considered warnings:
```
// bad.js
// There is only a single module export and it's a named export.
export const foo = 'foo';
```
The following patterns are not warnings:
```
// good1.js
// There is …
```

[New] `prefer-default-export`: add "target" option

---

CHANGELOG.md
docs/rules/no-cycle.md
src/ExportMap.js
tests/files/cycles/flow-typeof.js
tests/src/rules/no-cycle.js

Fixes #2607.
In addition to `import type`, Flow has a syntax `import typeof`. For example ([try-flow link](https://flow.org/try/#0JYWwDg9gTgLgBDAnmAphAZnA3nArgZxQFF10UBjeAXznSghDgHIoUBDSpgbgCgeA3NlFoAuPIRJlKXOAHpZcABZt8CRSjj42IDUlRwVcAErtKAOgLFSFGDyA)):
```js
import typeof { useEffect } from 'react';
var f: useEffect; // has the same type as React.useEffect
```
Like with `import type`, these imports are transpiled away and have no effect at runtime, so they should be given the same treatment as `import type`: that is, they should be ignored.
Currently they're not. This PR fixes that.

[Fix] `no-cycle`: Accept `import typeof`, like `import type`

---

CHANGELOG.md
README.md
docs/rules/no-absolute-path.md
src/rules/no-absolute-path.js
tests/src/rules/no-absolute-path.js

Hello, this is my first contribution to this repo. Should I change anything?

[New] `no-absolute-path`: add fixer

---

CHANGELOG.md
docs/rules/no-duplicates.md
src/rules/no-duplicates.js
tests/src/rules/no-duplicates.js

close https://github.com/import-js/eslint-plugin-import/issues/2470
ref https://github.com/typescript-eslint/typescript-eslint/pull/5050
Typescript `import { type A } from 'util/cool-linter'` was introduced in 4.5 https://devblogs.microsoft.com/typescript/announcing-typescript-4-5/#type-on-import-names
This PR seeks to add TypeScript support to the existing rule `no-duplicates`.
```
❌ Invalid `["error", "prefer-inline"]`
import { AValue, type AType } from './mama-mia'
import type { BType } from './mama-mia'
✅ Valid with `["error", "prefer-inline"]`
import { AValue, type AType, type BType } from './mama-mia'
```

[New] `no-duplicates`: support inline type import with `prefer-inline` option

---

CHANGELOG.md
src/rules/no-import-module-exports.js
tests/src/rules/no-import-module-exports.js

This lets the `no-import-module-exports` rule determine if a variable was defined by an import statement. For #2314

[Fix] `no-import-module-exports`: avoid a false positive for import variables

---

CONTRIBUTING.md

I have added new section to `CONTRIBUTING.md` which intends to help newcomers to our project familiarize with it. It includes one YouTube talk about AST and its implication on ESLINT, guide on using AST explorer tool, and couple of blog posts on creating new custom rules in ESLINT. 
I believe aforementioned resources will greatly aid in understanding the general structure of ESLINT and arm new developers with fundamental knowledge that will help them easily navigate and contribute to the project.

[meta] CONTRIBUTING.md: add resources for newcomers

---

CHANGELOG.md
package.json

The `array.prototype.flatmap` dependency is used as prod dependency after bumping to from [v2.26.0..v2.27.0](https://github.com/import-js/eslint-plugin-import/compare/v2.26.0...v2.27.0) in several of the rules:
Fixes #2663

fix: array.prototype.flatmap as prod dependency

---

CHANGELOG.md
src/rules/order.js
tests/src/rules/order.js

Resolves #2671 
Correctly sorts `groupRanks` in numerical order when alphabetizing. This bug would occur for groups where the `rank` overflowed to double digits (eg. `"10"` is sorted before `"4"`). This is a bug with the original code and not necessarily caused by #2506. There just previously wasn't a case where enough groups were added to get to the double digit ranks.
The test case I made for this is similar to the example case shown in #2671 but it isn't the most general test case. It's just a case that would fail without this change.
I also went ahead and added a description comment to my previous PR's test case since it was missing one

`import/order` Fix group ranks order when alphabetizing

---

CHANGELOG.md
docs/rules/no-duplicates.md

Corrects documentation to match validation schema and options for `no-duplicates` rule.

no-duplicates - Documentation update

---

CHANGELOG.md
src/rules/no-duplicates.js
tests/src/rules/no-duplicates.js

Resolves #2437.
This PR deduplicates import identifiers!

Remove duplicate identifiers in duplicate imports

---

CHANGELOG.md
docs/rules/group-exports.md

These snippets didn't have any syntax highlighting:
First chunk: https://share.cleanshot.com/spXGCRRGJkpBsLGLPk7k
Second chunk: https://share.cleanshot.com/vhRsmDnxCd7PZfFfLLhh
I searched codebase for any other ```flow js code blocks, but there were only these two from this file:
https://share.cleanshot.com/xY7W9TJTXPrJ8ngtf6Kr

[Docs] `group-exports`: fix syntax highlighting

---

CHANGELOG.md
src/rules/consistent-type-specifier-style.js
tests/src/rules/consistent-type-specifier-style.js

Fixes #2753
When passed the second argument - `getTokenAfter` will keep searching until it finds a token that matches that token - so in this bug it meant it kept scanning to the next import declaration.
Using the single-arg form means it will just grab the next token and we can then check to see if that token is a comma or not (it'll either be a `}` or a `,`).

[Fix] `consistent-type-specifier-style`: fix accidental removal of comma in certain cases

---

CHANGELOG.md
docs/rules/extensions.md

This behaviour largely didn't change despite the functionality becoming more widely adopted. Even though the document assumes CJS, It's probably worth including at least a footnote about the resolver behaving differently for ESM.
See: https://github.com/import-js/eslint-plugin-import/issues/2043

[Docs] Add node ESM behaviour in import/extensions

---

utils/CHANGELOG.md
utils/resolve.js

While looking at a larger code base https://gitlab.com/gitlab-org/gitlab, I've came to realize that `fullResolve` takes a lot of CPU cycles, particularly the `hashObject` calls inside it.
I applied the following patch locally to see how often this is called and how many unique hashes were produced:
```diff
diff --git a/utils/resolve.js b/utils/resolve.js
index 4a35c6a..3c28324 100644
--- a/utils/resolve.js
+++ b/utils/resolve.js
@@ -83,13 +83,28 @@ function relative(modulePath, sourceFile, settings) {
return fullResolve(modulePath, sourceFile, settings).path;
}
+let prevSettings = null;
+let nonEqualSettings = 0;
+let totalCalls = 0;
+let uniqueHashes = new Set();
function fullResolve(modulePath, sourceFile, settings) {
// check if this is a bonus core module
const coreSet = new …
```

[utils] [perf] Performance of fullResolve

---

tests/src/core/parse.js
tests/src/rules/no-unused-modules.js
utils/parse.js

Flat ESLint [no longer supports](https://eslint/eslint/issues/16878) `context.parserPath` which is required for [utils/parse](https://github.com/import-js/eslint-plugin-import/blob/d5fc8b670dc8e6903dbb7b0894452f60c03089f5/utils/parse.js#L60).
This PR uses `context.languageOptions.parse` which has the loaded parser as an alternative.
Some notes:
- Backwards compatible as it only checks if `context.parserPath` is unset
- Currently it does check if `parse` or `parseForESLint` in `context.languageOptions.parser` is a function (I do not if "constructed" context objects are officially supported)
- I added a test to the rule to no-unused-modules for testing with flat eslint rule tester

[utils] [new] `parse`: support flat config

---

CHANGELOG.md
src/ExportMap.js

While looking at a larger code base https://gitlab.com/gitlab-org/gitlab, `ExportMap.for` seems to take a significant amount of time. More than half of it is spend on calculating hashes with `hashObject`.
Digging a little deeper, it seems like we are calling it around 500 thousand times. Each iteration calculates the hash of a context object. This context object is created inside of the `childContext` function and consists of four parts:
- `settings` -> an Object itself
- `parserOptions` -> an Object itself
- `parserPath` -> a String
- `path` -> a String.
Interestingly `settings`, `parserOptions` and `parserPath` rarely do change for us, so calculating their hashes on every iteration seems unnecessary. `hashObject` recursively calculates the hashes of each key / value pair.
So instead of …

[perf] Improve ExportMap.for performance on larger codebases

---

CHANGELOG.md
docs/rules/no-extraneous-dependencies.md
src/rules/no-extraneous-dependencies.js
tests/src/rules/no-extraneous-dependencies.js

fixes https://github.com/import-js/eslint-plugin-import/issues/1618
This PR is to avoid error `should be listed in the project's dependencies, not devDependencies.` when only importing inline typescript types

[Fix] `no-extraneous-dependencies`/TypeScript: do not error when importing inline type from dev dependencies

---

README.md

YAML keys can not start with `@` as that will result in such a parser error:
```
bad indentation of a mapping entry (4:5)
1 | settings:
2 |   import/extensions: [.js, .jsx, .ts ...
3 |   import/parsers:
4 |     @typescript-eslint/parser: [ .ts ...
---------^
```

Fix invalid YAML in import/parsers example

---

package.json

Most plugins on npm seem to specify both [eslintplugin](https://www.npmjs.com/search?q=keywords:eslintplugin) and [eslint-plugin](https://www.npmjs.com/search?q=keywords:eslint-plugin) keywords. I have just looked up the list of top plugins using the latter, and got surprised that `eslint-plugin-import` was nowhere to be found.

Add "eslint-plugin" to the list of keywords in package.json

---

CHANGELOG.md
docs/rules/no-duplicates.md
src/rules/no-duplicates.js
tests/src/rules/no-duplicates.js

…refer-inline
Fixes #2834
I would expect that when using [no-duplicates](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-duplicates.md) with "prefer-inline" option, the following would be detected as an error:
```ts
import type { Type } from "mod";
import { value } from "mod";
```
And would fix to:
```ts
import { type Type, value } from "mod";
```

[Fix] `no-duplicates`: Prefer combined type and regular imports when using `prefer-inline`

---

CHANGELOG.md
src/rules/extensions.js
tests/index.js
tests/src/rules/extensions.js

The issue was `isExternalRootModule` was returning `true` for these, since they had no `/` in them. This fixes that.
Closes #2777

[Fix] `extensions`: handle `.` and `..` properly

---

CHANGELOG.md
src/rules/no-unused-modules.js
tests/src/rules/no-unused-modules.js

I noticed when an export declaration has multiple specifiers of which only a subset is unused the rule reports the error on the whole statement. In my code editor this draws a red squiggly under the whole statement. I can read which specifier is unused from the message of the reported error. Wouldn't it be nicer if the error was reported only on the specifier that is unused? That way I wouldn't necessarily need to even read and can let the red squiggly lead my monkey brain.
Consider the following export declaration
```js
export { foo, bar } from './foo';
```
Assume `foo` is used, `bar` is unused. Usually the fix would be to remove `bar`. I'd expect the reported error to point to that node as it would make it slightly more intuitive to attack it directly.
I'd imagine this change isn't …

[import/no-unused-modules] Report error on export specifier node

---

CHANGELOG.md
docs/rules/newline-after-import.md
docs/rules/no-duplicates.md
docs/rules/no-namespace.md
docs/rules/no-relative-packages.md
docs/rules/order.md

I noticed this issue randomly.
The automatic fixable notices are already handled by eslint-doc-generator from:
* https://github.com/import-js/eslint-plugin-import/pull/2582.

[Docs] remove duplicate fixable notices in docs

---

CHANGELOG.md
src/rules/order.js
tests/src/rules/order.js

1fa2971 changed the way groups work when there is only one, leading to single nested groups being treated as though they were unnested. Prior to this, if you wanted to group e.g. builtin and external imports together at the top and everything else together as a second group, a single nested group was the way to do it
[It appears that this change was unintentional][1], and was made to try to fix what seems to be a misunderstanding around nested groups ([#2687]). [The docs][2] continue to suggest that nested groups should be "mingled together" and makes no reference to a single nested group with no other groups being an invalid option
This therefore reverts the change to how groups work when there is only one. No documentation change should be necessary given this is already the described …

[Fix] Revert breaking group change in `order`

---

CHANGELOG.md
config/typescript.js

This PR is pretty self explanatory.
`.cts` and `.mts` are common file extensions used in projects that are not fully CJS or not fully ESM.
So I added those to the config.
I also fixed some of the grammar and made the comments wrap to 100 characters.

[New] TypeScript config: add .cts and .mts extensions

---

CHANGELOG.md
docs/rules/newline-after-import.md
src/rules/newline-after-import.js
tests/src/rules/newline-after-import.js

Fixes #1901. Fixes #514.
added option named `exactCount` of type `Boolean` default `false` that will enforce strict following of the `count` option where the number of newline has to be equal to `count`.
Updated the docs as mentioned in the linked issue accordingly.

[New] `newline-after-imports`: new option `exactCount` and docs update

---

CHANGELOG.md
src/rules/newline-after-import.js
tests/src/rules/newline-after-import.js

This addresses #2882 and adds additional test cases to cover the combination of `exactCount` and `considerComments`

[Fix] `newline-after-import`: fix `exactCount` with `considerComments` false positive, when there is a leading comment

---

CHANGELOG.md
src/rules/no-extraneous-dependencies.js
tests/src/rules/no-extraneous-dependencies.js

The `no-extraneous-dependencies` rule still checks a the dependency of `export type { T } from 'a-dev-dependency'` even when it is supposed to exclude type only imports
This triggers an error
```typescript
export type { T } from "a-dev-dependency";
``` 
This doesn't
```typescript
import type { T } from "a-dev-dependency"; 
export type { T };
``` 
`package.json`
```json
{
"devDependencies": {
"a-dev-dependency": "*"
}
}
```
rule:
```json
{
"devDependencies": false,
"includeTypes": false // false by default
}
```
Check if the export statement's kind is `type` and if so, treat it like an `import type` statement.

[Fix] `no-extraneous-dependencies`: ignore `export type { ... } from '...'` when `includeTypes` is `false`

---

CHANGELOG.md
docs/rules/no-extraneous-dependencies.md

Make glob pattern description more explicit

[Docs] `no-extraneous-dependencies`: Make glob pattern description more explicit

---

docs/rules/dynamic-import-chunkname.md
src/rules/dynamic-import-chunkname.js
tests/src/rules/dynamic-import-chunkname.js

[New] `dynamic-import-chunkname`: add `allowEmpty` option to allow empty leading comments

---

utils/CHANGELOG.md
utils/parse.js

fix: also delete parserOptions.EXPERIMENTAL_useProjectService

---

CHANGELOG.md
src/ExportMap.js

The following procedures:
```
ExportMap.get
ExportMap.for
ExportMap.parse
```
are conceptually static methods of `ExportMap`, but instead of using the `static` keyword they are monkey-patched onto the `ExportMap` class
```
ExportMap.get = function (...) {...}
```
which is surprising.
Lets make them static methods proper.
---
Tip for the reviewer/maintainer:
Use the "Hide whitespace" feature of GitHub's diff.

make exportmap procedures static instead of monkeypatching exportmap

---

.eslintrc

When running the tests / ci, ESLint complains about warnings related to the `no-console` rule.
The places where we have that console make sense to have console, so it's a false-positive.
Lets mark those specific places to be ignored by eslint, to reduce noise from the linter output.

resolve lint warnings

---

.eslintrc
CHANGELOG.md
src/exportMap.js
src/exportMapBuilder.js
src/rules/default.js
src/rules/export.js
src/rules/named.js
src/rules/namespace.js
src/rules/no-cycle.js
src/rules/no-deprecated.js
src/rules/no-named-as-default-member.js
src/rules/no-named-as-default.js
src/rules/no-unused-modules.js
tests/src/core/getExports.js

`ExportMap` is currently a very large file that is hard to follow, and therefore hard to maintain.
I identified that its static methods, which are responsible for building instances of `ExportMap`, can be generalized to the [builder software design pattern](https://en.wikipedia.org/wiki/Builder_pattern).
Lets make the separation, to make it clear that instances of `ExportMap` aren't coupled to any of the globals or procedures that are currently in `ExportMap.js`.
It's also good to rename the files and classes appropriately.

separate export map from its builder

---

CHANGELOG.md
docs/rules/order.md

Having unbound imports mixed among the bound ones causes unexpected and incorrect seeming results. I spent several hours trying to fix this problem only to find it was well known!
Since this is only a change to one markdown file, I assume no other tests are required. Hopefully this is helpful.

Add a quick note on how unbound imports and --fix

---

.eslintrc
CHANGELOG.md
src/exportMapBuilder.js

[`exportMapBuilder.js`](https://github.com/import-js/eslint-plugin-import/blob/38f8d25ef710747fe318d99b3f42e70bd1efc0f4/src/exportMapBuilder.js) currently has [ESLint "no-use-before-define" rule suppressed](https://github.com/import-js/eslint-plugin-import/blob/38f8d25ef710747fe318d99b3f42e70bd1efc0f4/.eslintrc#L232).
Lets fix the lint errors & un-suppress it for the file.

fix lint errors in export map builder

---

.github/workflows/native-wsl.yml
.github/workflows/node-4+.yml
.github/workflows/packages.yml

I personally think this is a good idea especially given this projects CI involves over 250+ jobs but I can understand if someone has an alternative workflow that makes it undesirable so feel free to close if you're not a fan 🙂 
Related docs: https://docs.github.com/en/actions/using-jobs/using-concurrency

ci: cancel in-progress runs when new changes are pushed up

---

CHANGELOG.md
README.md
docs/rules/dynamic-import-chunkname.md
src/rules/dynamic-import-chunkname.js
tests/src/rules/dynamic-import-chunkname.js

The dynamic-import-chunkname rule is useful for catching missing chunk names for imports, however much of our imports use `webpackMode: "eager"` to disable creating a separate chunk (i.e for lazy evaluation). Adding `webpackChunkName` anyway can force webpack to generate a chunk, defeating the purpose of the eager mode. This PR changes the rule to disallow chunk names when `webpackMode: "eager"` is set.
Related issue: https://github.com/import-js/eslint-plugin-import/issues/1904

[dynamic-import-chunkname] Disallow chunk name when eager mode is enabled

---

CHANGELOG.md
src/rules/no-extraneous-dependencies.js
tests/src/rules/no-extraneous-dependencies.js

This rule can potentially fails ( = reports incorrect errors ) in a monorepo settings; this is due to the fact that the building of the map of the available installed dependencies stops when there is an error ( e.g when the path to the package.json does not point to an existing package.json file )
-  If you pass only one path to a package.json file, then this path should be correct, this is ok 
- If you pass multiple paths, there are some situations when those paths point to a wrong path, this happens typically in a nx monorepo. The problem is that the parsing of the package.json files stop is one of the path is wrong, and then the rule will give us false positive. One example is a nx monorepo with a pre-commit hook that runs eslint
-- NX will run eslint in the projects folder, so we need …

[Fix] `no-extraneous-dependencies`: allow incorrect paths in packageDir 

---

CHANGELOG.md
docs/rules/no-unused-modules.md
src/rules/no-unused-modules.js
tests/src/rules/no-unused-modules.js

Fixes: https://github.com/import-js/eslint-plugin-import/issues/2694

[New] `no-unused-modules`: Add `ignoreUnusedTypeExports` option

---

utils/CHANGELOG.md
utils/parse.js

Recently typescript-eslint released version 8. One of the breaking changes introduced there was renaming `EXPERIMENTAL_useProjectService` to `projectService`.
xref: https://typescript-eslint.io/blog/announcing-typescript-eslint-v8-beta/#project-service
This fix deletes the new property as well to let this plugin be compatible with v8. During my testing I didn't encounter any other issues than this.
Change is based on prior change to get project service option working:
ref #2963

[utils] [fix] `parse`: Also delete parserOptions.projectService

---

resolvers/webpack/CHANGELOG.md
resolvers/webpack/index.js
resolvers/webpack/package.json

This PR reduces the amount of code run by using a plain for loop with early return. I was hesitant to make the change at first but I noticed that there are a lot of similar loops in the code so it shouldn't be a problem to use the same here

webpack resolver: Simplify loop

---

CHANGELOG.md
package.json
src/rules/no-cycle.js
src/scc.js
tests/src/rules/no-cycle.js
tests/src/scc.js

Lets make the `no-cycle` rule faster by not running many unnecessary BFSes.
For each dependency graph (aka `ExportMap`) we can run [Tarjan's SCC](https://en.wikipedia.org/wiki/Tarjan%27s_strongly_connected_components_algorithm) once (which is a derivative of DFS = O(n))
That saves us a lot of work because we run a linear-complexity algorithm once, as opposed to for each linted file (which turned us O(n^2))
https://github.com/import-js/eslint-plugin-import/issues/2937

optimize no-cycle rule using strongly connected components

---

CHANGELOG.md
src/rules/no-duplicates.js
tests/src/rules/no-duplicates.js

This PR addresses the issue where multiple import type statements from the same module are not properly combined when the prefer-inline option is enabled. Specifically, the problem arises when importing types with separate import type statements, which should be consolidated into a single import statement with inline type specifiers.
Fixes #3016, fixes #2792.
Given the following code:
```
import type { x } from 'foo';
import { type y } from 'foo';
```
as-is:
```
import type { x, type y } from 'foo';
```
to-be:
```
import { type x, type y } from 'foo';
```

[Fix] `no-duplicates`: Removing duplicates breaks in TypeScript

---

CHANGELOG.md
docs/rules/order.md

See https://github.com/import-js/eslint-plugin-import/pull/2239
PTAL @Mairu

[Docs] order: update the description of the `pathGroupsExcludedImportTypes` option

---

CHANGELOG.md
src/rules/newline-after-import.js
tests/src/rules/newline-after-import.js

fix #2905 
- new var in test file  use multiple space when require
- fix or remove invalid test cases
- add feature considerComments is applied normally when use require

[Fix] `newline-after-import`: fix `considerComments` option when require

---

CHANGELOG.md
src/rules/order.js
tests/src/rules/order.js

Should fix the regression in #2682.
The gist of the fix is that for relative paths, siblings always start with "." and parents always start with "..".  When comparing them, it will always result in "." being first, which was the bug. The sorting based on subpath segments should start from the second path segment, when there is a possibility that one of them is different.

[Fix] `order`: do not compare first path segment for relative paths

---

CHANGELOG.md
README.md

The markup in README.md is misleading, as it puts several alternatives into one block of code while not making it clear where the alternatives begin and end, forcing the reader to think hard about it. The pull request splits the block of code into three isolated ones, preceding each one with a comment and organizing them in a list.

Make it clear how to install the plugin

---

tests/src/rules/dynamic-import-chunkname.js
tests/src/rules/no-duplicates.js
tests/src/rules/no-import-module-exports.js

This ensures that IDEs like Webstorm won't trim trailing whitespace that is expected as part of test output

[Test] add explicit marker for trailing whitespace in cases

---

tests/src/rules/namespace.js

I came across this while working on #2996 - I'm pretty sure it's not intentional 😅
To make it a bit easier to spot, I've also put the closing `)` on a newline for both the `valid` and `invalid` arrays, even though that's not technically required to fix the test itself.
I've also checked the rest of the codebase and found no other instances of comma expressions being "used".

[Test] actually push `namespace` case into `valid` array

---

CHANGELOG.md
src/exportMap/childContext.js
tests/src/exportMap/childContext.js

This change fixes a bug with flat config support.  There is a function called `childContext` that's used by the ExportBuilder to "cleanse" the context object.  This function wasn't including the new `languageOptions` object, which contains the parser.  So by the time this cleansed context made it to the parse function, `languageOptions` wasn't there anymore.
Since `parserPath` was still being included in non-flat config scenarios, the parse function made it through ok and used `parserPath`.  However, once you shift to flat config, `parserPath` is no longer defined, and the actual parser object needs to be there.
Fixes #3051

[Fix] `ExportMap` / flat config: include `languageOptions` in context

---

utils/CHANGELOG.md
utils/contextCompat.d.ts
utils/contextCompat.js
utils/package.json
utils/resolve.js

This change adds helper functions to `eslint-module-utils` in order to add eslint v9 support to `eslint-plugin-import` in a backwards compatible way.
Contributes to #2996

[utils] [new] add context compatibility helpers

---

CHANGELOG.md
docs/rules/order.md
package.json
src/rules/order.js
tests/src/rules/order.js

Changes made in this PR change the `import/order` rule to allow configuring the order of named specifiers in `import`, `export` and `require` statements.
This will report errors and automatically fix expressions as shown in this example:
***Reports error:***
```ts
import { Bravo, Alpha } from 'foo';
const { Delta, Charlie } = require('foo');
export { Foxtrot, Echo } from 'foo';
export { Alpha as Hotel, India, Alpha as Golf };
```
***Fixed code:***
```ts
import { Alpha, Bravo } from 'foo';
const { Charlie, Delta } = require('foo');
export { Echo, Foxtrot } from 'foo';
export { Alpha as Golf, Alpha as Hotel, India } from 'foo';
```
This feature heavily uses the pre-existing functions used for re-ordering import/export statements and thus does not require a lot of changes.
To address the …

[New] `import/order`: add support for named imports

---

CHANGELOG.md
src/rules/no-named-as-default.js
tests/files/no-named-as-default/exports.js
tests/files/no-named-as-default/misleading-re-exports.js
tests/files/no-named-as-default/no-default-export.js
tests/files/no-named-as-default/re-exports.js
tests/files/no-named-as-default/something.js
tests/src/rules/no-named-as-default.js

New behaviour / fix for rule `no-named-as-default`: the rule will **not** show an error if the thing that was imported with `someName` is exported from the source both as `default` and `someName`
There's a big caveat related to how the _thing_ is defined in the imported module. If it's a re-export, then this fix will work. If it's defined in the imported module -- it won't work.
This PR fixes all the issues with 
```ts
import userEvent from '@testing-library/user-event';
```
because, luckily to us, `userEvent` is re-exported there and not defined in the imported file.
Fixes #1594

[Fix] `no-named-as-default`: allow named specifier if equivalent to default

---

utils/CHANGELOG.md
utils/parse.js

I won't admit how many times I'd read this warning while working on #2996 before I realised there were these (cosmetic) double backticks 😅

[utils] [fix] `parse`: remove unneeded extra backticks

---

.nycrc
examples/flat/eslint.config.mjs
examples/flat/src/depth-zero.js
examples/flat/src/es6/depth-one-dynamic.js
examples/legacy/.eslintrc.cjs
examples/legacy/src/depth-zero.js
examples/legacy/src/es6/depth-one-dynamic.js
tests/src/core/parse.js
utils/CHANGELOG.md
utils/parse.js

This change addresses an issue with using the espree parser with flat config.  `keysFromParser` is responsible for finding the `visitorKeys` from a combination of the parser instance, parserPath, and the results of a call to `parseForESLint`.  When using flat config, the `parserPath` will not be on the context object, and when using the espree parser there are no results from `parseForESLint`.  The espree parser _does_ provide visitor keys as a  prop on the parser itself.  However, this logic was only returning it when it found that "espree" was somewhere in the `parserPath` (which doesn't exist on flat config).
I changed it so that it first does the check for the old-school babel parser using parser path, and then just checks the parser instance for the presence of `VisitorKeys`, rather …

[utils] [fix] `parse`: espree parser isn't working with flat config

---

CHANGELOG.md
src/rules/export.js
tests/src/rules/export.js

This currently fails when there is only one `TSDeclareFunction`, this PR fixes that.

[Fix] `export`: False positive for exported overloaded functions in TS

---

CHANGELOG.md
src/scc.js

I noticed that `no-cycle` has a cache miss on SCC very often,
turns out that each linted file builds its own SCC, which is unnecessary.
Lets speed things up, by using the already cached SCC, as long as the context is similar (excluding linted file path)

[Performance] `no-cycle`: dont scc for each linted file

---

CHANGELOG.md
docs/rules/no-cycle.md

https://github.com/import-js/eslint-plugin-import/pull/2998 introduces a `disableScc` option to the `no-cycle` rule, but there's no reference to it in the rule's docs at https://github.com/import-js/eslint-plugin-import/blob/f72f2072f4245f2c3494816d7c14352fc9e07c0a/docs/rules/no-cycle.md
It's an error of omission, and we need to add it to the docs, so that users know about the escape hatch and what it does, without digging through issues/PRs about it.
Fixes #3063

[Docs] `no-cycle`: add `disableScc` to docs

---

CHANGELOG.md
src/exportMap/builder.js
tests/src/core/getExports.js

This change addresses an issue observed with the v9 upgrade, where the `ExportMap` Cache is being tainted with a bad export map, if the parse doesn't yield a `visitorKeys` (which can happen if an incompatible parser is used (e.g. og babel eslint)).  If one run of the no-cycle rule uses an incompatible parser and taints the cache and a subsequent test is run with a compatible parser, then the bad export map will be found in the cache and used instead of attempting to proceed with the parse.   
I don't think this is likely to occur in the wild, but in the event that it does, this should help. One thing to note, though: if someone is using an incompatible parser, then this change will have a performance impact, since it will attempt to create an export map every time, until it yields one …

[Fix] `exportMap`: export map cache is tainted by unreliable parse results

---

CHANGELOG.md
package.json
src/exportMap/childContext.js
tests/src/exportMap/childContext.js
utils/CHANGELOG.md
utils/hash.js
utils/package.json

Discovered this issue in https://github.com/import-js/eslint-plugin-import/pull/2996#issuecomment-2372522774.  
This change improves the logic for generating the cache key used for both the ExportMap cache and the resolver cache when using flat config.  Prior to this change, the cache key was a combination of the `parserPath`, a hash of the `parserOptions`, a hash of the plugin settings, and the path of the file.  When using flat config, `parserPath` isn't provided.  So, there's the possibility of incorrect / stale cache objects being used if someone ran with this plugin using different parsers within the same lint execution, if `parserOptions` and settings are the same.  
For flat config, we can achieve similar results by constructing the cacheKey using `languageOptions` as a component …

[Fix] `exportMap`: improve `cacheKey` when using flat config 

---

CHANGELOG.md
docs/rules/no-restricted-paths.md

I came across a minor mistake while reading the rule in the docs and made a quick correction.

[Docs] `no-restricted-paths`: fix grammar

---

CHANGELOG.md
docs/rules/extensions.md
src/rules/extensions.js
tests/src/rules/extensions.js

Currently, the patterns 
```ts
import type { Foo } from './foo';
export type { Foo } from './foo';
```
are ignored by the `import/extensions` rule.
This adds the `checkTypeImports` option to that rule, so these types of imports can be checked on an opt-in basis.

[New] `extensions`: add the `checkTypeImports` option

---

docs/rules/dynamic-import-chunkname.md

when setting up the rule in my app, I found out that there is a typo in the usage example of the `dynamic-import-chunkname` rule

[Docs] `dynamic-import-chunkname`:  fix typo in usage of the rule

---

.markdownlint.json
CHANGELOG.md
docs/rules/extensions.md
docs/rules/order.md

Resolves #2897 \
Related to #3104 and #3105 \
Potentially related to #2708, #2304, #2540
I can slice and dice this PR in whatever way is most useful.
The changes to the `import/extensions` documentation ([preview](https://github.com/Xunnamius/eslint-plugin-import/blob/main/docs/rules/extensions.md)) are not so massive and should merge cleanly.
The changes to the `import/order` documentation ([preview](https://github.com/Xunnamius/eslint-plugin-import/blob/main/docs/rules/order.md)), however, are much more extensive. I've been referring back to these docs on and off for several months as I've tweaked my linter configurations, and every time I do I pretty much leave confused and fall back on stepping through eslint-plugin-import's source to see what's actually happening. Along with …

[Docs] `extensions`, `order`: improve documentation

---

.markdownlint.json
CHANGELOG.md
README.md
docs/rules/enforce-node-protocol-usage.md
src/index.js
src/rules/enforce-node-protocol-usage.js
tests/src/rules/enforce-node-protocol-usage.js

Fixes #2717
Added a new rule `prefer-node-builtin-imports`.
All test cases are taken from [eslint-plugin-unicorn_test](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/test/prefer-node-protocol.mjs)

[New] add `enforce-node-protocol-usage` rule

---

.github/workflows/node-pretest.yml
CHANGELOG.md
index.d.ts
package.json

For now I've just typed these out manually based on what we're using internally - while it would be good to have some tests at some point, I'm hoping/recommending not blocking on that for now as I think the types are small enough to be easy to maintain manually for the time being.
Resolves #3090

[New] add TypeScript types

---

tests/files/minified/no-newline.js
tests/files/minified/one-line-no-semi-renamed.js
tests/files/minified/one-line-no-semi.js
tests/files/minified/one-line.js
tests/src/core/getExports.js
utils/CHANGELOG.md
utils/unambiguous.js

This change adjusts the regex pattern used to detect modules to support detection on minified code.
Closes #3107

[utils] [fix] `unambiguous`: detect modules exported from minified code

---

CHANGELOG.md
README.md

I added a guide for using the `config()` method from `typescript-eslint` when setting flat config with eslint.config.js in a TypeScript project.
Related issue: #3123

[Docs] add flat config guide for using `tseslint.config()`

---

CHANGELOG.md
README.md

add missing comma in README.md, so it's easier to copy/paste

[Docs] add missing comma

---

CHANGELOG.md
src/rules/extensions.js
tests/src/rules/extensions.js

**This PR implements in `import/extensions`: a new option enabling developers to override the decision to enforce or ignore extensions for imports with matching specifiers.**
A demo package containing this feature is temporarily available for easy testing:
```bash
npm install --save-dev eslint-plugin-import@npm:@-xun/eslint-plugin-import-experimental
```
I already use `import/order` with [custom `pathGroups`](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/order.md#pathgroups-array-of-objects). This allows me to control the grouping of certain paths, such as custom aliases from `tsconfig.json`'s `paths`. This in turn ensures all imports are sorted properly, even when the project is using syntactically sound but otherwise bespoke custom aliases like …

[New] `extensions`: allow enforcement decision overrides based on specifier

---

CHANGELOG.md
README.md

Was having an issue for a few hours trying to get import/no-unresolved not picking up relative imports that don't include the extension like so:
```ts
import { add } from './utils';
```
After asking inside Discord, kkapp helped me by pointing out that I may need to configure the resolver to look for "ts" extensions. After adding it I went on a crusade to figure out how I had managed to miss that when migrating to flat configs.
The example given for non-flat configs tells you to include the typescript config, but the flatConfig variant does not, so for an out-of-the-box experience when migrating, it can cause a headache.

[meta] Update flatConfig example to include typescript config

---

CHANGELOG.md
src/index.js

I am working on the eslint config inspector for my big flat config and I saw many anonymous configs where one of them is related to `import` so I added names in the flat configs

[Fix] configs: added missing name attribute for eslint config inspector

---

CHANGELOG.md
docs/rules/order.md
src/rules/order.js
tests/src/rules/order.js

Depends on #3104
**This PR implements in `import/order`: a new option analogous to `newlines-between` but specifically for controlling newlines between type-only imports.**
A demo package containing this feature is temporarily available for easy testing:
```bash
npm install --save-dev eslint-plugin-import@npm:@-xun/eslint-plugin-import-experimental
```
This is implemented via `newlines-between-types`. The proposed documentation corresponding to this new feature can be previewed [here](https://github.com/Xunnamius/eslint-plugin-import/blob/main/docs/rules/order.md#newlines-between-types).
<details><summary>Example</summary>
Given this code:
```typescript
import type A from 'fs';
import type B from 'path';
import type C from '../foo.js';
import type D from './bar.js';
import type E from …
```

[New] `order`: allow controlling intragroup spacing of type-only imports via `newlines-between-types`

---

.github/issue_template.md

In relation to a bug report about the plugin failing silently in some edge case: https://github.com/import-js/eslint-plugin-import/issues/3107
It's unclear how to make `eslint-plugin-import` show its detailed logs, which would have made the failure not silent, and saved contributor time in triage and debugging.
Lets add an issue template, with instructions that will guide the issue author to:
- Enable debug logging for the plugin, to narrow down what failed
- Provide an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example)

[meta] issue template with guidance for bug reports

---

CHANGELOG.md
src/rules/order.js
tests/src/rules/order.js

Depends on #3127
**This PR implements in `import/order`: a fix to ensure `NaN` is never passed into rank-computing functions, which can result in undefined behavior.**
A demo package containing this fix is temporarily available for easy testing:
```bash
npm install --save-dev eslint-plugin-import@npm:@-xun/eslint-plugin-import-experimental
```
There are certain edge cases where a `NaN` rank gets passed around, such as using an import with an absolute specifier under certain configurations. The fix concerns the `computeRank` function.
This PR includes a unit test to catch potential regressions.

[Fix] `order`: ensure arcane imports do not cause undefined behavior

---

CHANGELOG.md
docs/rules/order.md
src/rules/order.js
tests/src/rules/order.js

Depends on #3128
**This PR implements in `import/order`: a new option enabling the manipulation/consolidation of newlines around imports.**
A demo package containing this feature is temporarily available for easy testing:
```bash
npm install --save-dev eslint-plugin-import@npm:@-xun/eslint-plugin-import-experimental
```
This is implemented via `consolidateIslands`. The proposed documentation corresponding to this new feature can be previewed [here](https://github.com/Xunnamius/eslint-plugin-import/blob/main/docs/rules/order.md#consolidateislands).
<details><summary>Example</summary>
Given this code (which could be the output of a previous `--fix` pass):
```typescript
var fs = require('fs');
var path = require('path');
var { util1, util2, util3 } = require('util');
var async = …
```

[New] `order`: add `consolidateIslands` option to collapse excess spacing for aesthetically pleasing imports

---

CHANGELOG.md
docs/rules/no-restricted-paths.md

Some of the example paths don't match the file trees given. This also cleans up some of the file tree formatting and clarifies the wording to hopefully avoid confusion.

[Docs] `no-restricted-paths`: clarify wording and fix errors

---

CHANGELOG.md
src/rules/order.js
tests/src/rules/order.js

Updating schema wrt https://github.com/import-js/eslint-plugin-import/pull/3127#discussion_r1926534364
EDIT: depends on #3129 for its added tests

[Fix] `order`: codify invariants from docs into config schema
