- src/core/resolve.js
> Windows drive letter case

- README.md
- package.json
- src/rules/no-require.js
- tests/src/rules/no-require.js
Work-in-progress PR to fix #88.
> no-require

- .eslintrc
- src/rules/no-duplicates.js
- tests/src/rules/no-duplicates.js
> no-duplicates: handle unresolved.

- .babelrc
- .coveralls.yml
- .travis.yml
- README.md
- appveyor.yml
- package.json
- src/core/getExports.js
- src/core/parse.js
- src/rules/export.js
- tests/files/named-exports.js
- tests/src/core/getExports.js
- tests/src/core/parse.js
- tests/src/rules/export.js
- tests/src/rules/named.js
- tests/src/rules/no-unresolved.js
- tests/src/utils.js
> Coverage work

- src/core/parse.js
see https://github.com/eslint/eslint/issues/4495. need to publish as 0.10.1 once this passes tests
> don't mutate settings

- appveyor.yml
- resolvers/webpack/index.js
- resolvers/webpack/package.json
- resolvers/webpack/resolve-alias.js
- resolvers/webpack/test/config.js
- resolvers/webpack/test/files/some/absolute.path.webpack.config.js
Extension of #136. Want to ensure tests pass on Windows before merging.
> Feature: absolute webpack config

- resolvers/webpack/index.js
we needed to add support for relative paths. this approach appears to work.
> webpack resolver and eslint-loader (fixes #134)

- README.md
I'm not actually using yaml, so I hope I got the syntax right here. I'm not too sure about the `coffee$`
> update import/ignore documentation

- README.md
> update: add an ignore example for CSS modules

- package.json
avoid useless files to being send through npm
> remove src and doc from npm package

- CHANGELOG.md
Fix and reorder links in the changelog
> Fix and reorder links in the changelog

- README.md
Add an entry for `no-mutable-exports` in the readme.
> Update readme with `no-mutable-exports`

- CHANGELOG.md
As it doesnt display fixed on github
> Fix changelog spacing

- resolvers/webpack/CHANGELOG.md
- resolvers/webpack/index.js
- resolvers/webpack/test/files/webpack.config.js
Fixes #411, builds on #413.
- removed predicate that was failing tests on Windows
- added change log notes
> externals context

- CHANGELOG.md
- README.md
- docs/rules/order.md
- package.json
- src/core/importType.js
- tests/src/core/importType.js
- added `import/external-module-folders` (thanks to @zloirock)
@jfmengels, any concerns?
> release v1.12.0

- config/react-native.js
Make sense when you use react-native and react-native-web.
Not sure if that should go in another config tho.
> Add web.js extension in react-native config

- .eslintrc.yml
- CHANGELOG.md
- docs/rules/no-extraneous-dependencies.md
- docs/rules/no-unresolved.md
- docs/rules/unambiguous.md
- package.json
- resolvers/node/index.js
- resolvers/node/package.json
- resolvers/webpack/index.js
- resolvers/webpack/package.json
- src/core/staticRequire.js
- src/rules/extensions.js
- src/rules/max-dependencies.js
- tests/src/rules/no-extraneous-dependencies.js
Sorry I've been AWOL, haven't gone through all the issues but I figure it'd be good to get this published at least.
@jfmengels: Let me know if I missed anything else that ought to be included as additional minor bugfixes.
> Release v2.0.1

- resolvers/webpack/package.json
> [Fix] add missing `has` to webpack resolver.

- resolvers/webpack/index.js
enhanced-resolve has been bumped to 3.0.
> Fix incompatibility with webpack 2.2.0-rc.0

- .travis.yml
- CHANGELOG.md
- appveyor.yml
- docs/rules/no-unassigned-import.md
- package.json
- src/rules/no-unassigned-import.js
- tests/src/core/parse.js
- tests/src/core/parseStubParser.js
- tests/src/rules/no-unassigned-import.js
- utils/CHANGELOG.md
- utils/package.json
- utils/parse.js
need to move eslint-module-utils@v2.1.0 to `latest` tag before publishing
> Release 2.4.0

- .travis.yml
- appveyor.yml
- package.json
> CI cleanup

- src/rules/no-extraneous-dependencies.js
- tests/files/with-flow-typed/flow-typed/npm/myflowtyped_v1.x.x.js
- tests/files/with-flow-typed/package.json
- tests/src/rules/no-extraneous-dependencies.js
I was running into this issue and was curious if you all would entertain PRs for typing support.
Fixes #931
> Ignore import statements when using 'import type'

- README.md
> Missed a link

- README.md
Use the official project name: https://github.com/webpack/webpack.
> Webpack -> webpack

- CHANGELOG.md
ref: https://github.com/benmosher/eslint-plugin-import/pull/1067
> Fix link to order autofixer in CHANGELOG

- CHANGELOG.md
- package.json
> Release branch merge

- tests/src/utils.js
```diff
- runtinme
+ runtime
```
> Fix typo: 'runtime'

- CHANGELOG.md
> Fix format of changelog

- utils/package.json
Closes #1110.  I hope I interpreted that thumbs up correctly.
> Bump `pkg-dir`.

- src/rules/no-unused-modules.js
> [fix] `no-unused-modules`: make appveyor tests passing

- CHANGELOG.md
- package.json
- src/rules/prefer-default-export.js
- tests/src/rules/prefer-default-export.js
- utils/CHANGELOG.md
- utils/package.json
Also includes a release of eslint-module-utils v2.4.1
> Release 2.18.2

- src/rules/no-unused-modules.js
> [fix] #1364 for `no-unused-modules`: prevent memory overflow

- src/rules/prefer-default-export.js
- tests/src/rules/prefer-default-export.js
> [fix] `prefer-default-export`: fix cases when exporting array destructuring

- CHANGELOG.md
> Add missing changelog links

- README.md
- src/ExportMap.js
- utils/ModuleCache.js
> Fix a few spelling mistakes

- resolvers/webpack/CHANGELOG.md
- resolvers/webpack/index.js
> [reolvers/webpack] [fix] provide config fallback

- resolvers/webpack/CHANGELOG.md
- resolvers/webpack/README.md
- resolvers/webpack/index.js
- resolvers/webpack/test/.eslintrc
- resolvers/webpack/test/config.js
- resolvers/webpack/test/files/webpack.config.async.js
> Add warning about async Webpack configs

- CHANGELOG.md
- docs/rules/no-extraneous-dependencies.md
Kindly confirm that the default really is `true`.
> [Docs] Correcting peerDependencies option default to `true`

- CHANGELOG.md
- package.json
> Release 2.23.2

- docs/rules/named.md
- resolvers/node/CHANGELOG.md
- resolvers/node/index.js
- resolvers/node/test/package-mains/jsnext/package.json
- resolvers/node/test/package-mains/module-and-jsnext/package.json
- resolvers/node/test/package-mains/module/package.json
- resolvers/node/test/package-mains/package.json
- resolvers/node/test/packageMains.js
- resolvers/webpack/test/package-mains/module-and-jsnext/package.json
- resolvers/webpack/test/packageMains.js
Fixes #2163 
I still need to add unit tests (I plan on copying the existing `jsnext:main` tests in the webpack resolver)
I also wonder what's the best way for me to test this...it looks like it's multiple packages all in one repo, and I'm making changes to the webpack resolver. I can build it locally but then would I need to wire up my config for this plugin to use the local version of the resolver? Is that correct?
> [New] support "module" field in dependencies

- .github/workflows/node-4+.yml
- package.json
- tests/dep-time-travel.sh
- tests/src/core/getExports.js
- tests/src/rules/default.js
- tests/src/rules/dynamic-import-chunkname.js
- tests/src/rules/extensions.js
- tests/src/rules/max-dependencies.js
- tests/src/rules/named.js
- tests/src/rules/namespace.js
- tests/src/rules/newline-after-import.js
- tests/src/rules/no-cycle.js
- tests/src/rules/no-default-export.js
- tests/src/rules/no-duplicates.js
- tests/src/rules/no-dynamic-require.js
- tests/src/rules/no-extraneous-dependencies.js
- tests/src/rules/no-mutable-exports.js
- tests/src/rules/no-named-as-default.js
- tests/src/rules/no-named-default.js
- tests/src/rules/no-named-export.js
- tests/src/rules/no-relative-parent-imports.js
- tests/src/rules/no-unresolved.js
- tests/src/rules/no-unused-modules.js
- tests/src/rules/no-useless-path-segments.js
- tests/src/rules/no-webpack-loader-syntax.js
- tests/src/rules/order.js
- tests/src/rules/prefer-default-export.js
- tests/src/rules/unambiguous.js
- tests/src/utils.js
Run tests on [`@typescript-eslint/parser@5`](https://github.com/typescript-eslint/typescript-eslint/releases/tag/v5.0.0)
> [Tests] test on `@typescript-eslint/parser@5`

- CHANGELOG.md
- src/rules/order.js
- tests/src/rules/order.js
> [Fix] `order`: resolve undefined property access issue when using `named.cjsExports`
